package com.mingda.dao.impl;

import com.mingda.dao.ChronicCheckDAO;
import com.mingda.model.ChronicCheck;
import com.mingda.model.ChronicCheckExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ChronicCheckDAOImpl extends SqlMapClientDaoSupport implements ChronicCheckDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public ChronicCheckDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public int countByExample(ChronicCheckExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"CHRONIC_CHECK.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public int deleteByExample(ChronicCheckExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"CHRONIC_CHECK.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public int deleteByPrimaryKey(Integer chroniccheckId) {
		ChronicCheck key = new ChronicCheck();
		key.setChroniccheckId(chroniccheckId);
		int rows = getSqlMapClientTemplate().delete(
				"CHRONIC_CHECK.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public Integer insert(ChronicCheck record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"CHRONIC_CHECK.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public Integer insertSelective(ChronicCheck record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"CHRONIC_CHECK.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<ChronicCheck> selectByExample(ChronicCheckExample example) {
		List<ChronicCheck> list = getSqlMapClientTemplate().queryForList(
				"CHRONIC_CHECK.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public ChronicCheck selectByPrimaryKey(Integer chroniccheckId) {
		ChronicCheck key = new ChronicCheck();
		key.setChroniccheckId(chroniccheckId);
		ChronicCheck record = (ChronicCheck) getSqlMapClientTemplate()
				.queryForObject(
						"CHRONIC_CHECK.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public int updateByExampleSelective(ChronicCheck record,
			ChronicCheckExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update(
						"CHRONIC_CHECK.ibatorgenerated_updateByExampleSelective",
						parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public int updateByExample(ChronicCheck record, ChronicCheckExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"CHRONIC_CHECK.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public int updateByPrimaryKeySelective(ChronicCheck record) {
		int rows = getSqlMapClientTemplate().update(
				"CHRONIC_CHECK.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public int updateByPrimaryKey(ChronicCheck record) {
		int rows = getSqlMapClientTemplate().update(
				"CHRONIC_CHECK.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	private static class UpdateByExampleParms extends ChronicCheckExample {
		private Object record;

		public UpdateByExampleParms(Object record, ChronicCheckExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}