package com.mingda.dao.impl;

import com.mingda.dao.ChronicItemDAO;
import com.mingda.model.ChronicItem;
import com.mingda.model.ChronicItemExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ChronicItemDAOImpl extends SqlMapClientDaoSupport implements ChronicItemDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public ChronicItemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public int countByExample(ChronicItemExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("CHRONIC_ITEM.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public int deleteByExample(ChronicItemExample example) {
        int rows = getSqlMapClientTemplate().delete("CHRONIC_ITEM.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public void insert(ChronicItem record) {
        getSqlMapClientTemplate().insert("CHRONIC_ITEM.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public void insertSelective(ChronicItem record) {
        getSqlMapClientTemplate().insert("CHRONIC_ITEM.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<ChronicItem> selectByExample(ChronicItemExample example) {
        List<ChronicItem> list = getSqlMapClientTemplate().queryForList("CHRONIC_ITEM.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public int updateByExampleSelective(ChronicItem record, ChronicItemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CHRONIC_ITEM.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public int updateByExample(ChronicItem record, ChronicItemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CHRONIC_ITEM.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.CHRONIC_ITEM
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    private static class UpdateByExampleParms extends ChronicItemExample {
        private Object record;

        public UpdateByExampleParms(Object record, ChronicItemExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}