package com.mingda.dao.impl;

import com.mingda.dao.CsempDAO;
import com.mingda.model.Csemp;
import com.mingda.model.CsempExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CsempDAOImpl extends SqlMapClientDaoSupport implements CsempDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    public CsempDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    public int countByExample(CsempExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("CSEMP.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    public int deleteByExample(CsempExample example) {
        int rows = getSqlMapClientTemplate().delete("CSEMP.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    public void insert(Csemp record) {
        getSqlMapClientTemplate().insert("CSEMP.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    public void insertSelective(Csemp record) {
        getSqlMapClientTemplate().insert("CSEMP.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Csemp> selectByExample(CsempExample example) {
        List<Csemp> list = getSqlMapClientTemplate().queryForList("CSEMP.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    public int updateByExampleSelective(Csemp record, CsempExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CSEMP.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    public int updateByExample(Csemp record, CsempExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("CSEMP.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.CSEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:12 CST 2010
     */
    private static class UpdateByExampleParms extends CsempExample {
        private Object record;

        public UpdateByExampleParms(Object record, CsempExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}