package com.mingda.dao.impl;

import com.mingda.dao.ExportxlsDAO;
import com.mingda.model.Exportxls;
import com.mingda.model.ExportxlsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ExportxlsDAOImpl extends SqlMapClientDaoSupport implements ExportxlsDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public ExportxlsDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public int countByExample(ExportxlsExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"EXPORTXLS.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public int deleteByExample(ExportxlsExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"EXPORTXLS.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public int deleteByPrimaryKey(Long eid) {
		Exportxls key = new Exportxls();
		key.setEid(eid);
		int rows = getSqlMapClientTemplate().delete(
				"EXPORTXLS.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public Long insert(Exportxls record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"EXPORTXLS.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public Long insertSelective(Exportxls record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"EXPORTXLS.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<Exportxls> selectByExample(ExportxlsExample example) {
		List<Exportxls> list = getSqlMapClientTemplate().queryForList(
				"EXPORTXLS.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public Exportxls selectByPrimaryKey(Long eid) {
		Exportxls key = new Exportxls();
		key.setEid(eid);
		Exportxls record = (Exportxls) getSqlMapClientTemplate()
				.queryForObject("EXPORTXLS.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public int updateByExampleSelective(Exportxls record,
			ExportxlsExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"EXPORTXLS.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public int updateByExample(Exportxls record, ExportxlsExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"EXPORTXLS.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public int updateByPrimaryKeySelective(Exportxls record) {
		int rows = getSqlMapClientTemplate()
				.update("EXPORTXLS.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	public int updateByPrimaryKey(Exportxls record) {
		int rows = getSqlMapClientTemplate().update(
				"EXPORTXLS.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.EXPORTXLS
	 * @ibatorgenerated  Fri Aug 26 18:26:10 CST 2011
	 */
	private static class UpdateByExampleParms extends ExportxlsExample {
		private Object record;

		public UpdateByExampleParms(Object record, ExportxlsExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}