package com.mingda.dao.impl;

import com.mingda.dao.FensanDAO;
import com.mingda.model.Fensan;
import com.mingda.model.FensanExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class FensanDAOImpl extends SqlMapClientDaoSupport implements FensanDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public FensanDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int countByExample(FensanExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"FENSAN.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int deleteByExample(FensanExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"FENSAN.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public void insert(Fensan record) {
		getSqlMapClientTemplate().insert("FENSAN.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public void insertSelective(Fensan record) {
		getSqlMapClientTemplate().insert(
				"FENSAN.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<Fensan> selectByExample(FensanExample example) {
		List<Fensan> list = getSqlMapClientTemplate().queryForList(
				"FENSAN.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int updateByExampleSelective(Fensan record, FensanExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"FENSAN.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int updateByExample(Fensan record, FensanExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"FENSAN.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.FENSAN
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	private static class UpdateByExampleParms extends FensanExample {
		private Object record;

		public UpdateByExampleParms(Object record, FensanExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}