package com.mingda.dao.impl;

import com.mingda.dao.GuerfileDAO;
import com.mingda.model.Guerfile;
import com.mingda.model.GuerfileExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GuerfileDAOImpl extends SqlMapClientDaoSupport implements GuerfileDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    public GuerfileDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    public int countByExample(GuerfileExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("GUERFILE.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    public int deleteByExample(GuerfileExample example) {
        int rows = getSqlMapClientTemplate().delete("GUERFILE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    public BigDecimal insert(Guerfile record) {
        Object newKey = getSqlMapClientTemplate().insert("GUERFILE.ibatorgenerated_insert", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    public BigDecimal insertSelective(Guerfile record) {
        Object newKey = getSqlMapClientTemplate().insert("GUERFILE.ibatorgenerated_insertSelective", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<Guerfile> selectByExample(GuerfileExample example) {
        List<Guerfile> list = getSqlMapClientTemplate().queryForList("GUERFILE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    public int updateByExampleSelective(Guerfile record, GuerfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("GUERFILE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    public int updateByExample(Guerfile record, GuerfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("GUERFILE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.GUERFILE
     *
     * @ibatorgenerated Tue May 21 15:44:30 CST 2013
     */
    private static class UpdateByExampleParms extends GuerfileExample {
        private Object record;

        public UpdateByExampleParms(Object record, GuerfileExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}