package com.mingda.dao.impl;

import com.mingda.dao.Icd10DAO;
import com.mingda.model.Icd10;
import com.mingda.model.Icd10Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Icd10DAOImpl extends SqlMapClientDaoSupport implements Icd10DAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public Icd10DAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public int countByExample(Icd10Example example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"ICD10.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public int deleteByExample(Icd10Example example) {
		int rows = getSqlMapClientTemplate().delete(
				"ICD10.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public int deleteByPrimaryKey(Integer icdId) {
		Icd10 key = new Icd10();
		key.setIcdId(icdId);
		int rows = getSqlMapClientTemplate().delete(
				"ICD10.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public Integer insert(Icd10 record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"ICD10.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public Integer insertSelective(Icd10 record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"ICD10.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Icd10> selectByExample(Icd10Example example) {
		List<Icd10> list = getSqlMapClientTemplate().queryForList(
				"ICD10.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public Icd10 selectByPrimaryKey(Integer icdId) {
		Icd10 key = new Icd10();
		key.setIcdId(icdId);
		Icd10 record = (Icd10) getSqlMapClientTemplate().queryForObject(
				"ICD10.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public int updateByExampleSelective(Icd10 record, Icd10Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"ICD10.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public int updateByExample(Icd10 record, Icd10Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"ICD10.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public int updateByPrimaryKeySelective(Icd10 record) {
		int rows = getSqlMapClientTemplate().update(
				"ICD10.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	public int updateByPrimaryKey(Icd10 record) {
		int rows = getSqlMapClientTemplate().update(
				"ICD10.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table JL_YLJZ.ICD10
	 * @ibatorgenerated  Thu Sep 30 14:36:57 CST 2010
	 */
	private static class UpdateByExampleParms extends Icd10Example {
		private Object record;

		public UpdateByExampleParms(Object record, Icd10Example example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}