package com.mingda.dao.impl;

import com.mingda.dao.JizhongDAO;
import com.mingda.model.Jizhong;
import com.mingda.model.JizhongExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JizhongDAOImpl extends SqlMapClientDaoSupport implements JizhongDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public JizhongDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int countByExample(JizhongExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JIZHONG.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int deleteByExample(JizhongExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JIZHONG.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public void insert(Jizhong record) {
		getSqlMapClientTemplate().insert("JIZHONG.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public void insertSelective(Jizhong record) {
		getSqlMapClientTemplate().insert(
				"JIZHONG.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<Jizhong> selectByExample(JizhongExample example) {
		List<Jizhong> list = getSqlMapClientTemplate().queryForList(
				"JIZHONG.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int updateByExampleSelective(Jizhong record, JizhongExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JIZHONG.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	public int updateByExample(Jizhong record, JizhongExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JIZHONG.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.JIZHONG
	 * @ibatorgenerated  Wed May 25 16:23:00 CST 2011
	 */
	private static class UpdateByExampleParms extends JizhongExample {
		private Object record;

		public UpdateByExampleParms(Object record, JizhongExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}