package com.mingda.dao.impl;

import com.mingda.dao.JzAddassistdataDAO;
import com.mingda.model.JzAddassistdata;
import com.mingda.model.JzAddassistdataExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzAddassistdataDAOImpl extends SqlMapClientDaoSupport implements JzAddassistdataDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public JzAddassistdataDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public int countByExample(JzAddassistdataExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_ADDASSISTDATA.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public int deleteByExample(JzAddassistdataExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_ADDASSISTDATA.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public int deleteByPrimaryKey(Integer bizId) {
        JzAddassistdata key = new JzAddassistdata();
        key.setBizId(bizId);
        int rows = getSqlMapClientTemplate().delete("JZ_ADDASSISTDATA.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public Integer insert(JzAddassistdata record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_ADDASSISTDATA.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public Integer insertSelective(JzAddassistdata record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_ADDASSISTDATA.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    @SuppressWarnings("unchecked")
    public List<JzAddassistdata> selectByExample(JzAddassistdataExample example) {
        List<JzAddassistdata> list = getSqlMapClientTemplate().queryForList("JZ_ADDASSISTDATA.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public JzAddassistdata selectByPrimaryKey(Integer bizId) {
        JzAddassistdata key = new JzAddassistdata();
        key.setBizId(bizId);
        JzAddassistdata record = (JzAddassistdata) getSqlMapClientTemplate().queryForObject("JZ_ADDASSISTDATA.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public int updateByExampleSelective(JzAddassistdata record, JzAddassistdataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_ADDASSISTDATA.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public int updateByExample(JzAddassistdata record, JzAddassistdataExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_ADDASSISTDATA.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public int updateByPrimaryKeySelective(JzAddassistdata record) {
        int rows = getSqlMapClientTemplate().update("JZ_ADDASSISTDATA.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    public int updateByPrimaryKey(JzAddassistdata record) {
        int rows = getSqlMapClientTemplate().update("JZ_ADDASSISTDATA.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.JZ_ADDASSISTDATA
     *
     * @ibatorgenerated Thu Jul 21 15:18:53 CST 2011
     */
    private static class UpdateByExampleParms extends JzAddassistdataExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzAddassistdataExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}