package com.mingda.dao.impl;

import com.mingda.dao.JzBizcheckDAO;
import com.mingda.model.JzBizcheck;
import com.mingda.model.JzBizcheckExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;
import com.mingda.model.JzBizcheckWithBLOBs;

public class JzBizcheckDAOImpl extends SqlMapClientDaoSupport implements JzBizcheckDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public JzBizcheckDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int countByExample(JzBizcheckExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JZ_BIZCHECK.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int deleteByExample(JzBizcheckExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_BIZCHECK.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int deleteByPrimaryKey(BigDecimal bizcheck) {
		JzBizcheck key = new JzBizcheck();
		key.setBizcheck(bizcheck);
		int rows = getSqlMapClientTemplate().delete(
				"JZ_BIZCHECK.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public BigDecimal insert(JzBizcheckWithBLOBs record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_BIZCHECK.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public BigDecimal insertSelective(JzBizcheckWithBLOBs record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"JZ_BIZCHECK.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<JzBizcheckWithBLOBs> selectByExampleWithBLOBs(
			JzBizcheckExample example) {
		List<JzBizcheckWithBLOBs> list = getSqlMapClientTemplate()
				.queryForList(
						"JZ_BIZCHECK.ibatorgenerated_selectByExampleWithBLOBs",
						example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<JzBizcheck> selectByExampleWithoutBLOBs(
			JzBizcheckExample example) {
		List<JzBizcheck> list = getSqlMapClientTemplate().queryForList(
				"JZ_BIZCHECK.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public JzBizcheckWithBLOBs selectByPrimaryKey(BigDecimal bizcheck) {
		JzBizcheck key = new JzBizcheck();
		key.setBizcheck(bizcheck);
		JzBizcheckWithBLOBs record = (JzBizcheckWithBLOBs) getSqlMapClientTemplate()
				.queryForObject(
						"JZ_BIZCHECK.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int updateByExampleSelective(JzBizcheckWithBLOBs record,
			JzBizcheckExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int updateByExample(JzBizcheckWithBLOBs record,
			JzBizcheckExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int updateByExample(JzBizcheck record, JzBizcheckExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int updateByPrimaryKeySelective(JzBizcheckWithBLOBs record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int updateByPrimaryKey(JzBizcheckWithBLOBs record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByPrimaryKeyWithBLOBs",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public int updateByPrimaryKey(JzBizcheck record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_BIZCHECK.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.JZ_BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private static class UpdateByExampleParms extends JzBizcheckExample {
		private Object record;

		public UpdateByExampleParms(Object record, JzBizcheckExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}