package com.mingda.dao.impl;

import com.mingda.dao.JzMedicalafterBillDAO;
import com.mingda.model.JzMedicalafterBill;
import com.mingda.model.JzMedicalafterBillExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzMedicalafterBillDAOImpl extends SqlMapClientDaoSupport implements JzMedicalafterBillDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public JzMedicalafterBillDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public int countByExample(JzMedicalafterBillExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_MEDICALAFTER_BILL.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public int deleteByExample(JzMedicalafterBillExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_MEDICALAFTER_BILL.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public int deleteByPrimaryKey(String billId) {
        JzMedicalafterBill key = new JzMedicalafterBill();
        key.setBillId(billId);
        int rows = getSqlMapClientTemplate().delete("JZ_MEDICALAFTER_BILL.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public void insert(JzMedicalafterBill record) {
        getSqlMapClientTemplate().insert("JZ_MEDICALAFTER_BILL.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public void insertSelective(JzMedicalafterBill record) {
        getSqlMapClientTemplate().insert("JZ_MEDICALAFTER_BILL.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    @SuppressWarnings("unchecked")
    public List<JzMedicalafterBill> selectByExample(JzMedicalafterBillExample example) {
        List<JzMedicalafterBill> list = getSqlMapClientTemplate().queryForList("JZ_MEDICALAFTER_BILL.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public JzMedicalafterBill selectByPrimaryKey(String billId) {
        JzMedicalafterBill key = new JzMedicalafterBill();
        key.setBillId(billId);
        JzMedicalafterBill record = (JzMedicalafterBill) getSqlMapClientTemplate().queryForObject("JZ_MEDICALAFTER_BILL.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public int updateByExampleSelective(JzMedicalafterBill record, JzMedicalafterBillExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTER_BILL.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public int updateByExample(JzMedicalafterBill record, JzMedicalafterBillExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTER_BILL.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public int updateByPrimaryKeySelective(JzMedicalafterBill record) {
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTER_BILL.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    public int updateByPrimaryKey(JzMedicalafterBill record) {
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTER_BILL.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.JZ_MEDICALAFTER_BILL
     *
     * @ibatorgenerated Wed Dec 31 10:21:28 CST 2014
     */
    private static class UpdateByExampleParms extends JzMedicalafterBillExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzMedicalafterBillExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}