package com.mingda.dao.impl;

import com.mingda.dao.JzMedicalafterfileDAO;
import com.mingda.model.JzMedicalafterfile;
import com.mingda.model.JzMedicalafterfileExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzMedicalafterfileDAOImpl extends SqlMapClientDaoSupport implements JzMedicalafterfileDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public JzMedicalafterfileDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public int countByExample(JzMedicalafterfileExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_MEDICALAFTERFILE.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public int deleteByExample(JzMedicalafterfileExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_MEDICALAFTERFILE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public int deleteByPrimaryKey(BigDecimal fileId) {
        JzMedicalafterfile key = new JzMedicalafterfile();
        key.setFileId(fileId);
        int rows = getSqlMapClientTemplate().delete("JZ_MEDICALAFTERFILE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public BigDecimal insert(JzMedicalafterfile record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_MEDICALAFTERFILE.ibatorgenerated_insert", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public BigDecimal insertSelective(JzMedicalafterfile record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_MEDICALAFTERFILE.ibatorgenerated_insertSelective", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<JzMedicalafterfile> selectByExample(JzMedicalafterfileExample example) {
        List<JzMedicalafterfile> list = getSqlMapClientTemplate().queryForList("JZ_MEDICALAFTERFILE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public JzMedicalafterfile selectByPrimaryKey(BigDecimal fileId) {
        JzMedicalafterfile key = new JzMedicalafterfile();
        key.setFileId(fileId);
        JzMedicalafterfile record = (JzMedicalafterfile) getSqlMapClientTemplate().queryForObject("JZ_MEDICALAFTERFILE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public int updateByExampleSelective(JzMedicalafterfile record, JzMedicalafterfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTERFILE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public int updateByExample(JzMedicalafterfile record, JzMedicalafterfileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTERFILE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public int updateByPrimaryKeySelective(JzMedicalafterfile record) {
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTERFILE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public int updateByPrimaryKey(JzMedicalafterfile record) {
        int rows = getSqlMapClientTemplate().update("JZ_MEDICALAFTERFILE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.JZ_MEDICALAFTERFILE
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    private static class UpdateByExampleParms extends JzMedicalafterfileExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzMedicalafterfileExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}