package com.mingda.dao.impl;

import com.mingda.dao.JzPayDAO;
import com.mingda.model.JzPay;
import com.mingda.model.JzPayExample;
import com.mingda.model.JzPayKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzPayDAOImpl extends SqlMapClientDaoSupport implements JzPayDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public JzPayDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public int countByExample(JzPayExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"JZ_PAY.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public int deleteByExample(JzPayExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_PAY.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public int deleteByPrimaryKey(JzPayKey key) {
		int rows = getSqlMapClientTemplate().delete(
				"JZ_PAY.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public void insert(JzPay record) {
		getSqlMapClientTemplate().insert("JZ_PAY.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public void insertSelective(JzPay record) {
		getSqlMapClientTemplate().insert(
				"JZ_PAY.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<JzPay> selectByExample(JzPayExample example) {
		List<JzPay> list = getSqlMapClientTemplate().queryForList(
				"JZ_PAY.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public JzPay selectByPrimaryKey(JzPayKey key) {
		JzPay record = (JzPay) getSqlMapClientTemplate().queryForObject(
				"JZ_PAY.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public int updateByExampleSelective(JzPay record, JzPayExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_PAY.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public int updateByExample(JzPay record, JzPayExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"JZ_PAY.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public int updateByPrimaryKeySelective(JzPay record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_PAY.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	public int updateByPrimaryKey(JzPay record) {
		int rows = getSqlMapClientTemplate().update(
				"JZ_PAY.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.JZ_PAY
	 * @ibatorgenerated  Wed Jun 05 19:58:11 CST 2013
	 */
	private static class UpdateByExampleParms extends JzPayExample {
		private Object record;

		public UpdateByExampleParms(Object record, JzPayExample example) {
			super(example);
			this.record = record;
		}
		
		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}