package com.mingda.dao.impl;

import com.mingda.dao.JzYearDAO;
import com.mingda.model.JzYear;
import com.mingda.model.JzYearExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class JzYearDAOImpl extends SqlMapClientDaoSupport implements JzYearDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public JzYearDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public int countByExample(JzYearExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("JZ_YEAR.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public int deleteByExample(JzYearExample example) {
        int rows = getSqlMapClientTemplate().delete("JZ_YEAR.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public int deleteByPrimaryKey(Integer yId) {
        JzYear key = new JzYear();
        key.setyId(yId);
        int rows = getSqlMapClientTemplate().delete("JZ_YEAR.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public Integer insert(JzYear record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_YEAR.ibatorgenerated_insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public Integer insertSelective(JzYear record) {
        Object newKey = getSqlMapClientTemplate().insert("JZ_YEAR.ibatorgenerated_insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    @SuppressWarnings("unchecked")
    public List<JzYear> selectByExample(JzYearExample example) {
        List<JzYear> list = getSqlMapClientTemplate().queryForList("JZ_YEAR.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public JzYear selectByPrimaryKey(Integer yId) {
        JzYear key = new JzYear();
        key.setyId(yId);
        JzYear record = (JzYear) getSqlMapClientTemplate().queryForObject("JZ_YEAR.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public int updateByExampleSelective(JzYear record, JzYearExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_YEAR.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public int updateByExample(JzYear record, JzYearExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("JZ_YEAR.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public int updateByPrimaryKeySelective(JzYear record) {
        int rows = getSqlMapClientTemplate().update("JZ_YEAR.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    public int updateByPrimaryKey(JzYear record) {
        int rows = getSqlMapClientTemplate().update("JZ_YEAR.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.JZ_YEAR
     *
     * @ibatorgenerated Sat Jan 10 15:40:04 CST 2015
     */
    private static class UpdateByExampleParms extends JzYearExample {
        private Object record;

        public UpdateByExampleParms(Object record, JzYearExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}