package com.mingda.dao.impl;

import com.mingda.dao.MaBillDAO;
import com.mingda.model.MaBill;
import com.mingda.model.MaBillExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MaBillDAOImpl extends SqlMapClientDaoSupport implements MaBillDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public MaBillDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int countByExample(MaBillExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("MA_BILL.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int deleteByExample(MaBillExample example) {
        int rows = getSqlMapClientTemplate().delete("MA_BILL.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int deleteByPrimaryKey(Long billId) {
        MaBill key = new MaBill();
        key.setBillId(billId);
        int rows = getSqlMapClientTemplate().delete("MA_BILL.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public Long insert(MaBill record) {
        Object newKey = getSqlMapClientTemplate().insert("MA_BILL.ibatorgenerated_insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public Long insertSelective(MaBill record) {
        Object newKey = getSqlMapClientTemplate().insert("MA_BILL.ibatorgenerated_insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<MaBill> selectByExample(MaBillExample example) {
        List<MaBill> list = getSqlMapClientTemplate().queryForList("MA_BILL.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public MaBill selectByPrimaryKey(Long billId) {
        MaBill key = new MaBill();
        key.setBillId(billId);
        MaBill record = (MaBill) getSqlMapClientTemplate().queryForObject("MA_BILL.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByExampleSelective(MaBill record, MaBillExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MA_BILL.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByExample(MaBill record, MaBillExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MA_BILL.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByPrimaryKeySelective(MaBill record) {
        int rows = getSqlMapClientTemplate().update("MA_BILL.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByPrimaryKey(MaBill record) {
        int rows = getSqlMapClientTemplate().update("MA_BILL.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.MA_BILL
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    private static class UpdateByExampleParms extends MaBillExample {
        private Object record;

        public UpdateByExampleParms(Object record, MaBillExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}