package com.mingda.dao.impl;

import com.mingda.dao.MaMonthDAO;
import com.mingda.model.MaMonth;
import com.mingda.model.MaMonthExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MaMonthDAOImpl extends SqlMapClientDaoSupport implements MaMonthDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public MaMonthDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int countByExample(MaMonthExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("MA_MONTH.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int deleteByExample(MaMonthExample example) {
        int rows = getSqlMapClientTemplate().delete("MA_MONTH.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int deleteByPrimaryKey(BigDecimal mid) {
        MaMonth key = new MaMonth();
        key.setMid(mid);
        int rows = getSqlMapClientTemplate().delete("MA_MONTH.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public BigDecimal insert(MaMonth record) {
        Object newKey = getSqlMapClientTemplate().insert("MA_MONTH.ibatorgenerated_insert", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public BigDecimal insertSelective(MaMonth record) {
        Object newKey = getSqlMapClientTemplate().insert("MA_MONTH.ibatorgenerated_insertSelective", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<MaMonth> selectByExample(MaMonthExample example) {
        List<MaMonth> list = getSqlMapClientTemplate().queryForList("MA_MONTH.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public MaMonth selectByPrimaryKey(BigDecimal mid) {
        MaMonth key = new MaMonth();
        key.setMid(mid);
        MaMonth record = (MaMonth) getSqlMapClientTemplate().queryForObject("MA_MONTH.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByExampleSelective(MaMonth record, MaMonthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MA_MONTH.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByExample(MaMonth record, MaMonthExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MA_MONTH.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByPrimaryKeySelective(MaMonth record) {
        int rows = getSqlMapClientTemplate().update("MA_MONTH.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    public int updateByPrimaryKey(MaMonth record) {
        int rows = getSqlMapClientTemplate().update("MA_MONTH.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.MA_MONTH
     *
     * @ibatorgenerated Tue Feb 28 14:09:17 CST 2012
     */
    private static class UpdateByExampleParms extends MaMonthExample {
        private Object record;

        public UpdateByExampleParms(Object record, MaMonthExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}