package com.mingda.dao.impl;

import com.mingda.dao.ManagerEmpDAO;
import com.mingda.model.ManagerEmp;
import com.mingda.model.ManagerEmpExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ManagerEmpDAOImpl extends SqlMapClientDaoSupport implements ManagerEmpDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:44 CST 2011
	 */
	public ManagerEmpDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public int countByExample(ManagerEmpExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"MANAGER_EMP.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public int deleteByExample(ManagerEmpExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"MANAGER_EMP.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public int deleteByPrimaryKey(String empid) {
		ManagerEmp key = new ManagerEmp();
		key.setEmpid(empid);
		int rows = getSqlMapClientTemplate().delete(
				"MANAGER_EMP.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public void insert(ManagerEmp record) {
		getSqlMapClientTemplate().insert("MANAGER_EMP.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public void insertSelective(ManagerEmp record) {
		getSqlMapClientTemplate().insert(
				"MANAGER_EMP.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<ManagerEmp> selectByExample(ManagerEmpExample example) {
		List<ManagerEmp> list = getSqlMapClientTemplate().queryForList(
				"MANAGER_EMP.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public ManagerEmp selectByPrimaryKey(String empid) {
		ManagerEmp key = new ManagerEmp();
		key.setEmpid(empid);
		ManagerEmp record = (ManagerEmp) getSqlMapClientTemplate()
				.queryForObject(
						"MANAGER_EMP.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public int updateByExampleSelective(ManagerEmp record,
			ManagerEmpExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"MANAGER_EMP.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public int updateByExample(ManagerEmp record, ManagerEmpExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"MANAGER_EMP.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public int updateByPrimaryKeySelective(ManagerEmp record) {
		int rows = getSqlMapClientTemplate().update(
				"MANAGER_EMP.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	public int updateByPrimaryKey(ManagerEmp record) {
		int rows = getSqlMapClientTemplate().update(
				"MANAGER_EMP.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.MANAGER_EMP
	 * @ibatorgenerated  Mon Jan 10 15:29:45 CST 2011
	 */
	private static class UpdateByExampleParms extends ManagerEmpExample {
		private Object record;

		public UpdateByExampleParms(Object record, ManagerEmpExample example) {
			super(example);
			this.record = record;
		}

		@SuppressWarnings("unused")
		public Object getRecord() {
			return record;
		}
	}
}