package com.mingda.dao.impl;

import com.mingda.dao.MemberBaseinfoviewDAO;
import com.mingda.model.MemberBaseinfoview;
import com.mingda.model.MemberBaseinfoviewExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MemberBaseinfoviewDAOImpl extends SqlMapClientDaoSupport implements MemberBaseinfoviewDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    public MemberBaseinfoviewDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    public int countByExample(MemberBaseinfoviewExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("MEMBER_BASEINFOVIEW02.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    public int deleteByExample(MemberBaseinfoviewExample example) {
        int rows = getSqlMapClientTemplate().delete("MEMBER_BASEINFOVIEW02.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    public void insert(MemberBaseinfoview record) {
        getSqlMapClientTemplate().insert("MEMBER_BASEINFOVIEW02.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    public void insertSelective(MemberBaseinfoview record) {
        getSqlMapClientTemplate().insert("MEMBER_BASEINFOVIEW02.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<MemberBaseinfoview> selectByExample(MemberBaseinfoviewExample example) {
        List<MemberBaseinfoview> list = getSqlMapClientTemplate().queryForList("MEMBER_BASEINFOVIEW02.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    public int updateByExampleSelective(MemberBaseinfoview record, MemberBaseinfoviewExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MEMBER_BASEINFOVIEW02.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    public int updateByExample(MemberBaseinfoview record, MemberBaseinfoviewExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("MEMBER_BASEINFOVIEW02.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.MEMBER_BASEINFOVIEW02
     *
     * @ibatorgenerated Sat Nov 13 12:17:58 CST 2010
     */
    private static class UpdateByExampleParms extends MemberBaseinfoviewExample {
        private Object record;

        public UpdateByExampleParms(Object record, MemberBaseinfoviewExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}