package com.mingda.dao.impl;

import com.mingda.dao.NcempDAO;
import com.mingda.model.Ncemp;
import com.mingda.model.NcempExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class NcempDAOImpl extends SqlMapClientDaoSupport implements NcempDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    public NcempDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    public int countByExample(NcempExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("NCEMP.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    public int deleteByExample(NcempExample example) {
        int rows = getSqlMapClientTemplate().delete("NCEMP.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    public void insert(Ncemp record) {
        getSqlMapClientTemplate().insert("NCEMP.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    public void insertSelective(Ncemp record) {
        getSqlMapClientTemplate().insert("NCEMP.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Ncemp> selectByExample(NcempExample example) {
        List<Ncemp> list = getSqlMapClientTemplate().queryForList("NCEMP.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    public int updateByExampleSelective(Ncemp record, NcempExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("NCEMP.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    public int updateByExample(Ncemp record, NcempExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("NCEMP.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.NCEMP
     *
     * @ibatorgenerated Tue Oct 12 12:42:23 CST 2010
     */
    private static class UpdateByExampleParms extends NcempExample {
        private Object record;

        public UpdateByExampleParms(Object record, NcempExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}