package com.mingda.dao.impl;

import com.mingda.dao.NcorganizationDAO;
import com.mingda.model.Ncorganization;
import com.mingda.model.NcorganizationExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class NcorganizationDAOImpl extends SqlMapClientDaoSupport implements NcorganizationDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    public NcorganizationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    public int countByExample(NcorganizationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("NCORGANIZATION.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    public int deleteByExample(NcorganizationExample example) {
        int rows = getSqlMapClientTemplate().delete("NCORGANIZATION.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    public void insert(Ncorganization record) {
        getSqlMapClientTemplate().insert("NCORGANIZATION.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    public void insertSelective(Ncorganization record) {
        getSqlMapClientTemplate().insert("NCORGANIZATION.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Ncorganization> selectByExample(NcorganizationExample example) {
        List<Ncorganization> list = getSqlMapClientTemplate().queryForList("NCORGANIZATION.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    public int updateByExampleSelective(Ncorganization record, NcorganizationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("NCORGANIZATION.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    public int updateByExample(Ncorganization record, NcorganizationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("NCORGANIZATION.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.NCORGANIZATION
     *
     * @ibatorgenerated Tue Oct 12 12:43:24 CST 2010
     */
    private static class UpdateByExampleParms extends NcorganizationExample {
        private Object record;

        public UpdateByExampleParms(Object record, NcorganizationExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
    }
}