package com.mingda.dao.impl;

import com.mingda.dao.OrgEnabledDAO;
import com.mingda.model.OrgEnabled;
import com.mingda.model.OrgEnabledExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OrgEnabledDAOImpl extends SqlMapClientDaoSupport implements OrgEnabledDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public OrgEnabledDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public int countByExample(OrgEnabledExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"ORG_ENABLED.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public int deleteByExample(OrgEnabledExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"ORG_ENABLED.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public int deleteByPrimaryKey(String organizationId) {
		OrgEnabled key = new OrgEnabled();
		key.setOrganizationId(organizationId);
		int rows = getSqlMapClientTemplate().delete(
				"ORG_ENABLED.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public void insert(OrgEnabled record) {
		getSqlMapClientTemplate().insert("ORG_ENABLED.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public void insertSelective(OrgEnabled record) {
		getSqlMapClientTemplate().insert(
				"ORG_ENABLED.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	@SuppressWarnings("unchecked")
	public List<OrgEnabled> selectByExample(OrgEnabledExample example) {
		List<OrgEnabled> list = getSqlMapClientTemplate().queryForList(
				"ORG_ENABLED.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public OrgEnabled selectByPrimaryKey(String organizationId) {
		OrgEnabled key = new OrgEnabled();
		key.setOrganizationId(organizationId);
		OrgEnabled record = (OrgEnabled) getSqlMapClientTemplate()
				.queryForObject(
						"ORG_ENABLED.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public int updateByExampleSelective(OrgEnabled record,
			OrgEnabledExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"ORG_ENABLED.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public int updateByExample(OrgEnabled record, OrgEnabledExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"ORG_ENABLED.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public int updateByPrimaryKeySelective(OrgEnabled record) {
		int rows = getSqlMapClientTemplate().update(
				"ORG_ENABLED.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	public int updateByPrimaryKey(OrgEnabled record) {
		int rows = getSqlMapClientTemplate().update(
				"ORG_ENABLED.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.ORG_ENABLED
	 * @ibatorgenerated  Thu Oct 08 14:19:54 CST 2015
	 */
	private static class UpdateByExampleParms extends OrgEnabledExample {
		private Object record;

		public UpdateByExampleParms(Object record, OrgEnabledExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}