package com.mingda.dao.impl;

import com.mingda.dao.OutIcdDAO;
import com.mingda.model.OutIcd;
import com.mingda.model.OutIcdExample;
import com.mingda.model.OutIcdKey;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class OutIcdDAOImpl extends SqlMapClientDaoSupport implements OutIcdDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public OutIcdDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public int countByExample(OutIcdExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("OUT_ICD.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public int deleteByExample(OutIcdExample example) {
        int rows = getSqlMapClientTemplate().delete("OUT_ICD.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public int deleteByPrimaryKey(OutIcdKey key) {
        int rows = getSqlMapClientTemplate().delete("OUT_ICD.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public void insert(OutIcd record) {
        getSqlMapClientTemplate().insert("OUT_ICD.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public void insertSelective(OutIcd record) {
        getSqlMapClientTemplate().insert("OUT_ICD.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<OutIcd> selectByExample(OutIcdExample example) {
        List<OutIcd> list = getSqlMapClientTemplate().queryForList("OUT_ICD.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public OutIcd selectByPrimaryKey(OutIcdKey key) {
        OutIcd record = (OutIcd) getSqlMapClientTemplate().queryForObject("OUT_ICD.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public int updateByExampleSelective(OutIcd record, OutIcdExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("OUT_ICD.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public int updateByExample(OutIcd record, OutIcdExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("OUT_ICD.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public int updateByPrimaryKeySelective(OutIcd record) {
        int rows = getSqlMapClientTemplate().update("OUT_ICD.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    public int updateByPrimaryKey(OutIcd record) {
        int rows = getSqlMapClientTemplate().update("OUT_ICD.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.OUT_ICD
     *
     * @ibatorgenerated Tue Nov 23 14:18:40 CST 2010
     */
    private static class UpdateByExampleParms extends OutIcdExample {
        private Object record;

        public UpdateByExampleParms(Object record, OutIcdExample example) {
            super(example);
            this.record = record;
        }

        @SuppressWarnings("unused")
		public Object getRecord() {
            return record;
        }
        
    }
}