package com.mingda.dao.impl;

import com.mingda.dao.Payview01DAO;
import com.mingda.model.Payview01;
import com.mingda.model.Payview01Example;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Payview01DAOImpl extends SqlMapClientDaoSupport implements Payview01DAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	public Payview01DAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	public int countByExample(Payview01Example example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"PAYVIEW01.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	public int deleteByExample(Payview01Example example) {
		int rows = getSqlMapClientTemplate().delete(
				"PAYVIEW01.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	public void insert(Payview01 record) {
		getSqlMapClientTemplate().insert("PAYVIEW01.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	public void insertSelective(Payview01 record) {
		getSqlMapClientTemplate().insert(
				"PAYVIEW01.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<Payview01> selectByExample(Payview01Example example) {
		List<Payview01> list = getSqlMapClientTemplate().queryForList(
				"PAYVIEW01.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	public int updateByExampleSelective(Payview01 record,
			Payview01Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"PAYVIEW01.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	public int updateByExample(Payview01 record, Payview01Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"PAYVIEW01.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.PAYVIEW01
	 * @ibatorgenerated  Tue Jul 02 09:53:20 CST 2013
	 */
	private static class UpdateByExampleParms extends Payview01Example {
		private Object record;

		public UpdateByExampleParms(Object record, Payview01Example example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}