package com.mingda.dao.impl;

import com.mingda.dao.SecondBatchDAO;
import com.mingda.model.SecondBatch;
import com.mingda.model.SecondBatchExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecondBatchDAOImpl extends SqlMapClientDaoSupport implements SecondBatchDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public SecondBatchDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int countByExample(SecondBatchExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"SECOND_BATCH.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int deleteByExample(SecondBatchExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"SECOND_BATCH.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int deleteByPrimaryKey(BigDecimal batchId) {
		SecondBatch key = new SecondBatch();
		key.setBatchId(batchId);
		int rows = getSqlMapClientTemplate().delete(
				"SECOND_BATCH.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public BigDecimal insert(SecondBatch record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"SECOND_BATCH.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public BigDecimal insertSelective(SecondBatch record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"SECOND_BATCH.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<SecondBatch> selectByExample(SecondBatchExample example) {
		List<SecondBatch> list = getSqlMapClientTemplate().queryForList(
				"SECOND_BATCH.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public SecondBatch selectByPrimaryKey(BigDecimal batchId) {
		SecondBatch key = new SecondBatch();
		key.setBatchId(batchId);
		SecondBatch record = (SecondBatch) getSqlMapClientTemplate()
				.queryForObject(
						"SECOND_BATCH.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByExampleSelective(SecondBatch record,
			SecondBatchExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SECOND_BATCH.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByExample(SecondBatch record, SecondBatchExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SECOND_BATCH.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByPrimaryKeySelective(SecondBatch record) {
		int rows = getSqlMapClientTemplate().update(
				"SECOND_BATCH.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByPrimaryKey(SecondBatch record) {
		int rows = getSqlMapClientTemplate().update(
				"SECOND_BATCH.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.SECOND_BATCH
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private static class UpdateByExampleParms extends SecondBatchExample {
		private Object record;

		public UpdateByExampleParms(Object record, SecondBatchExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}