package com.mingda.dao.impl;

import com.mingda.dao.SecondApproveDAO;
import com.mingda.model.SecondApprove;
import com.mingda.model.SecondApproveExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SecondApproveDAOImpl extends SqlMapClientDaoSupport implements SecondApproveDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public SecondApproveDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int countByExample(SecondApproveExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"SECOND_APPROVE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int deleteByExample(SecondApproveExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"SECOND_APPROVE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int deleteByPrimaryKey(BigDecimal approveId) {
		SecondApprove key = new SecondApprove();
		key.setApproveId(approveId);
		int rows = getSqlMapClientTemplate().delete(
				"SECOND_APPROVE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public BigDecimal insert(SecondApprove record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"SECOND_APPROVE.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public BigDecimal insertSelective(SecondApprove record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"SECOND_APPROVE.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<SecondApprove> selectByExample(SecondApproveExample example) {
		List<SecondApprove> list = getSqlMapClientTemplate().queryForList(
				"SECOND_APPROVE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public SecondApprove selectByPrimaryKey(BigDecimal approveId) {
		SecondApprove key = new SecondApprove();
		key.setApproveId(approveId);
		SecondApprove record = (SecondApprove) getSqlMapClientTemplate()
				.queryForObject(
						"SECOND_APPROVE.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByExampleSelective(SecondApprove record,
			SecondApproveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SECOND_APPROVE.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByExample(SecondApprove record,
			SecondApproveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"SECOND_APPROVE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByPrimaryKeySelective(SecondApprove record) {
		int rows = getSqlMapClientTemplate().update(
				"SECOND_APPROVE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public int updateByPrimaryKey(SecondApprove record) {
		int rows = getSqlMapClientTemplate().update(
				"SECOND_APPROVE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.SECOND_APPROVE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private static class UpdateByExampleParms extends SecondApproveExample {
		private Object record;

		public UpdateByExampleParms(Object record, SecondApproveExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}