package com.mingda.dao.impl;

import com.mingda.dao.TempBillDAO;
import com.mingda.model.TempBill;
import com.mingda.model.TempBillExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TempBillDAOImpl extends SqlMapClientDaoSupport implements TempBillDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public TempBillDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int countByExample(TempBillExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TEMP_BILL.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int deleteByExample(TempBillExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TEMP_BILL.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int deleteByPrimaryKey(Long billId) {
		TempBill key = new TempBill();
		key.setBillId(billId);
		int rows = getSqlMapClientTemplate().delete(
				"TEMP_BILL.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public Long insert(TempBill record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"TEMP_BILL.ibatorgenerated_insert", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public Long insertSelective(TempBill record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"TEMP_BILL.ibatorgenerated_insertSelective", record);
		return (Long) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<TempBill> selectByExample(TempBillExample example) {
		List<TempBill> list = getSqlMapClientTemplate().queryForList(
				"TEMP_BILL.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public TempBill selectByPrimaryKey(Long billId) {
		TempBill key = new TempBill();
		key.setBillId(billId);
		TempBill record = (TempBill) getSqlMapClientTemplate().queryForObject(
				"TEMP_BILL.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByExampleSelective(TempBill record, TempBillExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TEMP_BILL.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByExample(TempBill record, TempBillExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TEMP_BILL.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByPrimaryKeySelective(TempBill record) {
		int rows = getSqlMapClientTemplate()
				.update("TEMP_BILL.ibatorgenerated_updateByPrimaryKeySelective",
						record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByPrimaryKey(TempBill record) {
		int rows = getSqlMapClientTemplate().update(
				"TEMP_BILL.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.TEMP_BILL
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	private static class UpdateByExampleParms extends TempBillExample {
		private Object record;

		public UpdateByExampleParms(Object record, TempBillExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}