package com.mingda.dao.impl;

import com.mingda.dao.TempCalcRuleDAO;
import com.mingda.model.TempCalcRule;
import com.mingda.model.TempCalcRuleExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TempCalcRuleDAOImpl extends SqlMapClientDaoSupport implements TempCalcRuleDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public TempCalcRuleDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public int countByExample(TempCalcRuleExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TEMP_CALC_RULE.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public int deleteByExample(TempCalcRuleExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TEMP_CALC_RULE.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public int deleteByPrimaryKey(Integer ruletempId) {
		TempCalcRule key = new TempCalcRule();
		key.setRuletempId(ruletempId);
		int rows = getSqlMapClientTemplate().delete(
				"TEMP_CALC_RULE.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public Integer insert(TempCalcRule record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"TEMP_CALC_RULE.ibatorgenerated_insert", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public Integer insertSelective(TempCalcRule record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"TEMP_CALC_RULE.ibatorgenerated_insertSelective", record);
		return (Integer) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<TempCalcRule> selectByExample(TempCalcRuleExample example) {
		List<TempCalcRule> list = getSqlMapClientTemplate().queryForList(
				"TEMP_CALC_RULE.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public TempCalcRule selectByPrimaryKey(Integer ruletempId) {
		TempCalcRule key = new TempCalcRule();
		key.setRuletempId(ruletempId);
		TempCalcRule record = (TempCalcRule) getSqlMapClientTemplate()
				.queryForObject(
						"TEMP_CALC_RULE.ibatorgenerated_selectByPrimaryKey",
						key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public int updateByExampleSelective(TempCalcRule record,
			TempCalcRuleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TEMP_CALC_RULE.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public int updateByExample(TempCalcRule record, TempCalcRuleExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TEMP_CALC_RULE.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public int updateByPrimaryKeySelective(TempCalcRule record) {
		int rows = getSqlMapClientTemplate().update(
				"TEMP_CALC_RULE.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	public int updateByPrimaryKey(TempCalcRule record) {
		int rows = getSqlMapClientTemplate().update(
				"TEMP_CALC_RULE.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.TEMP_CALC_RULE
	 * @ibatorgenerated  Fri Feb 22 14:36:52 CST 2013
	 */
	private static class UpdateByExampleParms extends TempCalcRuleExample {
		private Object record;

		public UpdateByExampleParms(Object record, TempCalcRuleExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}