package com.mingda.dao.impl;

import com.mingda.dao.TempMonthDAO;
import com.mingda.model.TempMonth;
import com.mingda.model.TempMonthExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TempMonthDAOImpl extends SqlMapClientDaoSupport implements TempMonthDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public TempMonthDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int countByExample(TempMonthExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"TEMP_MONTH.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int deleteByExample(TempMonthExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"TEMP_MONTH.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int deleteByPrimaryKey(BigDecimal mid) {
		TempMonth key = new TempMonth();
		key.setMid(mid);
		int rows = getSqlMapClientTemplate().delete(
				"TEMP_MONTH.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public BigDecimal insert(TempMonth record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"TEMP_MONTH.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public BigDecimal insertSelective(TempMonth record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"TEMP_MONTH.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	@SuppressWarnings("unchecked")
	public List<TempMonth> selectByExample(TempMonthExample example) {
		List<TempMonth> list = getSqlMapClientTemplate().queryForList(
				"TEMP_MONTH.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public TempMonth selectByPrimaryKey(BigDecimal mid) {
		TempMonth key = new TempMonth();
		key.setMid(mid);
		TempMonth record = (TempMonth) getSqlMapClientTemplate()
				.queryForObject(
						"TEMP_MONTH.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByExampleSelective(TempMonth record,
			TempMonthExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TEMP_MONTH.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByExample(TempMonth record, TempMonthExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"TEMP_MONTH.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByPrimaryKeySelective(TempMonth record) {
		int rows = getSqlMapClientTemplate().update(
				"TEMP_MONTH.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	public int updateByPrimaryKey(TempMonth record) {
		int rows = getSqlMapClientTemplate().update(
				"TEMP_MONTH.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.TEMP_MONTH
	 * @ibatorgenerated  Thu Aug 11 13:36:30 CST 2011
	 */
	private static class UpdateByExampleParms extends TempMonthExample {
		private Object record;

		public UpdateByExampleParms(Object record, TempMonthExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}