package com.mingda.dao.impl;

import com.mingda.dao.TempApprovefileDAO;
import com.mingda.model.TempApprovefile;
import com.mingda.model.TempApprovefileExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TempApprovefileDAOImpl extends SqlMapClientDaoSupport implements TempApprovefileDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public TempApprovefileDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public int countByExample(TempApprovefileExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("TEMP_APPROVEFILE.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public int deleteByExample(TempApprovefileExample example) {
        int rows = getSqlMapClientTemplate().delete("TEMP_APPROVEFILE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public int deleteByPrimaryKey(BigDecimal fileId) {
        TempApprovefile key = new TempApprovefile();
        key.setFileId(fileId);
        int rows = getSqlMapClientTemplate().delete("TEMP_APPROVEFILE.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public BigDecimal insert(TempApprovefile record) {
        Object newKey = getSqlMapClientTemplate().insert("TEMP_APPROVEFILE.ibatorgenerated_insert", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public BigDecimal insertSelective(TempApprovefile record) {
        Object newKey = getSqlMapClientTemplate().insert("TEMP_APPROVEFILE.ibatorgenerated_insertSelective", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<TempApprovefile> selectByExample(TempApprovefileExample example) {
        List<TempApprovefile> list = getSqlMapClientTemplate().queryForList("TEMP_APPROVEFILE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public TempApprovefile selectByPrimaryKey(BigDecimal fileId) {
        TempApprovefile key = new TempApprovefile();
        key.setFileId(fileId);
        TempApprovefile record = (TempApprovefile) getSqlMapClientTemplate().queryForObject("TEMP_APPROVEFILE.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public int updateByExampleSelective(TempApprovefile record, TempApprovefileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TEMP_APPROVEFILE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public int updateByExample(TempApprovefile record, TempApprovefileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("TEMP_APPROVEFILE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public int updateByPrimaryKeySelective(TempApprovefile record) {
        int rows = getSqlMapClientTemplate().update("TEMP_APPROVEFILE.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    public int updateByPrimaryKey(TempApprovefile record) {
        int rows = getSqlMapClientTemplate().update("TEMP_APPROVEFILE.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.TEMP_APPROVEFILE
     *
     * @ibatorgenerated Fri Nov 23 13:23:16 CST 2012
     */
    private static class UpdateByExampleParms extends TempApprovefileExample {
        private Object record;

        public UpdateByExampleParms(Object record, TempApprovefileExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}