package com.mingda.dao.impl;

import com.mingda.dao.WubaohufileDAO;
import com.mingda.model.Wubaohufile;
import com.mingda.model.WubaohufileExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WubaohufileDAOImpl extends SqlMapClientDaoSupport implements WubaohufileDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:22 CST 2012
     */
    public WubaohufileDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:22 CST 2012
     */
    public int countByExample(WubaohufileExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("WUBAOHUFILE.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:23 CST 2012
     */
    public int deleteByExample(WubaohufileExample example) {
        int rows = getSqlMapClientTemplate().delete("WUBAOHUFILE.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:23 CST 2012
     */
    public BigDecimal insert(Wubaohufile record) {
        Object newKey = getSqlMapClientTemplate().insert("WUBAOHUFILE.ibatorgenerated_insert", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:23 CST 2012
     */
    public BigDecimal insertSelective(Wubaohufile record) {
        Object newKey = getSqlMapClientTemplate().insert("WUBAOHUFILE.ibatorgenerated_insertSelective", record);
        return (BigDecimal) newKey;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:23 CST 2012
     */
    @SuppressWarnings("unchecked")
    public List<Wubaohufile> selectByExample(WubaohufileExample example) {
        List<Wubaohufile> list = getSqlMapClientTemplate().queryForList("WUBAOHUFILE.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:23 CST 2012
     */
    public int updateByExampleSelective(Wubaohufile record, WubaohufileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WUBAOHUFILE.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:23 CST 2012
     */
    public int updateByExample(Wubaohufile record, WubaohufileExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("WUBAOHUFILE.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.WUBAOHUFILE
     *
     * @ibatorgenerated Fri Dec 14 12:30:23 CST 2012
     */
    private static class UpdateByExampleParms extends WubaohufileExample {
        private Object record;

        public UpdateByExampleParms(Object record, WubaohufileExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}