package com.mingda.dao.impl;

import com.mingda.dao.WubaohuDAO;
import com.mingda.model.Wubaohu;
import com.mingda.model.WubaohuExample;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class WubaohuDAOImpl extends SqlMapClientDaoSupport implements WubaohuDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public WubaohuDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public int countByExample(WubaohuExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"WUBAOHU.ibatorgenerated_countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public int deleteByExample(WubaohuExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"WUBAOHU.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public int deleteByPrimaryKey(BigDecimal memberId) {
		Wubaohu key = new Wubaohu();
		key.setMemberId(memberId);
		int rows = getSqlMapClientTemplate().delete(
				"WUBAOHU.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public BigDecimal insert(Wubaohu record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"WUBAOHU.ibatorgenerated_insert", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public BigDecimal insertSelective(Wubaohu record) {
		Object newKey = getSqlMapClientTemplate().insert(
				"WUBAOHU.ibatorgenerated_insertSelective", record);
		return (BigDecimal) newKey;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	@SuppressWarnings("unchecked")
	public List<Wubaohu> selectByExample(WubaohuExample example) {
		List<Wubaohu> list = getSqlMapClientTemplate().queryForList(
				"WUBAOHU.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public Wubaohu selectByPrimaryKey(BigDecimal memberId) {
		Wubaohu key = new Wubaohu();
		key.setMemberId(memberId);
		Wubaohu record = (Wubaohu) getSqlMapClientTemplate().queryForObject(
				"WUBAOHU.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public int updateByExampleSelective(Wubaohu record, WubaohuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"WUBAOHU.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public int updateByExample(Wubaohu record, WubaohuExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"WUBAOHU.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public int updateByPrimaryKeySelective(Wubaohu record) {
		int rows = getSqlMapClientTemplate().update(
				"WUBAOHU.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	public int updateByPrimaryKey(Wubaohu record) {
		int rows = getSqlMapClientTemplate().update(
				"WUBAOHU.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.WUBAOHU
	 * @ibatorgenerated  Thu May 30 16:03:45 CST 2013
	 */
	private static class UpdateByExampleParms extends WubaohuExample {
		private Object record;

		public UpdateByExampleParms(Object record, WubaohuExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}