package com.mingda.model;

public class ChronicItem {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.CHRONIC_ITEM.ICD_ID
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    private Integer icdId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.CHRONIC_ITEM.CHRONICCHECK_ID
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    private Integer chroniccheckId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.CHRONIC_ITEM.ICD_ID
     *
     * @return the value of MEDICAL.CHRONIC_ITEM.ICD_ID
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public Integer getIcdId() {
        return icdId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.CHRONIC_ITEM.ICD_ID
     *
     * @param icdId the value for MEDICAL.CHRONIC_ITEM.ICD_ID
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public void setIcdId(Integer icdId) {
        this.icdId = icdId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.CHRONIC_ITEM.CHRONICCHECK_ID
     *
     * @return the value of MEDICAL.CHRONIC_ITEM.CHRONICCHECK_ID
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public Integer getChroniccheckId() {
        return chroniccheckId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.CHRONIC_ITEM.CHRONICCHECK_ID
     *
     * @param chroniccheckId the value for MEDICAL.CHRONIC_ITEM.CHRONICCHECK_ID
     *
     * @ibatorgenerated Tue Nov 16 13:27:00 CST 2010
     */
    public void setChroniccheckId(Integer chroniccheckId) {
        this.chroniccheckId = chroniccheckId;
    }
}