package com.mingda.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ChronicCheckExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public ChronicCheckExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	protected ChronicCheckExample(ChronicCheckExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.CHRONIC_CHECK
	 * @ibatorgenerated  Wed Nov 24 13:28:51 CST 2010
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andChroniccheckIdIsNull() {
			addCriterion("CHRONICCHECK_ID is null");
			return this;
		}

		public Criteria andChroniccheckIdIsNotNull() {
			addCriterion("CHRONICCHECK_ID is not null");
			return this;
		}

		public Criteria andChroniccheckIdEqualTo(Integer value) {
			addCriterion("CHRONICCHECK_ID =", value, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdNotEqualTo(Integer value) {
			addCriterion("CHRONICCHECK_ID <>", value, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdGreaterThan(Integer value) {
			addCriterion("CHRONICCHECK_ID >", value, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHRONICCHECK_ID >=", value, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdLessThan(Integer value) {
			addCriterion("CHRONICCHECK_ID <", value, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdLessThanOrEqualTo(Integer value) {
			addCriterion("CHRONICCHECK_ID <=", value, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdIn(List<Integer> values) {
			addCriterion("CHRONICCHECK_ID in", values, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdNotIn(List<Integer> values) {
			addCriterion("CHRONICCHECK_ID not in", values, "chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdBetween(Integer value1, Integer value2) {
			addCriterion("CHRONICCHECK_ID between", value1, value2,
					"chroniccheckId");
			return this;
		}

		public Criteria andChroniccheckIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("CHRONICCHECK_ID not between", value1, value2,
					"chroniccheckId");
			return this;
		}

		public Criteria andMemberTypeIsNull() {
			addCriterion("MEMBER_TYPE is null");
			return this;
		}

		public Criteria andMemberTypeIsNotNull() {
			addCriterion("MEMBER_TYPE is not null");
			return this;
		}

		public Criteria andMemberTypeEqualTo(String value) {
			addCriterion("MEMBER_TYPE =", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeNotEqualTo(String value) {
			addCriterion("MEMBER_TYPE <>", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeGreaterThan(String value) {
			addCriterion("MEMBER_TYPE >", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeGreaterThanOrEqualTo(String value) {
			addCriterion("MEMBER_TYPE >=", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeLessThan(String value) {
			addCriterion("MEMBER_TYPE <", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeLessThanOrEqualTo(String value) {
			addCriterion("MEMBER_TYPE <=", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeLike(String value) {
			addCriterion("MEMBER_TYPE like", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeNotLike(String value) {
			addCriterion("MEMBER_TYPE not like", value, "memberType");
			return this;
		}

		public Criteria andMemberTypeIn(List<String> values) {
			addCriterion("MEMBER_TYPE in", values, "memberType");
			return this;
		}

		public Criteria andMemberTypeNotIn(List<String> values) {
			addCriterion("MEMBER_TYPE not in", values, "memberType");
			return this;
		}

		public Criteria andMemberTypeBetween(String value1, String value2) {
			addCriterion("MEMBER_TYPE between", value1, value2, "memberType");
			return this;
		}

		public Criteria andMemberTypeNotBetween(String value1, String value2) {
			addCriterion("MEMBER_TYPE not between", value1, value2,
					"memberType");
			return this;
		}

		public Criteria andMemberIdIsNull() {
			addCriterion("MEMBER_ID is null");
			return this;
		}

		public Criteria andMemberIdIsNotNull() {
			addCriterion("MEMBER_ID is not null");
			return this;
		}

		public Criteria andMemberIdEqualTo(String value) {
			addCriterion("MEMBER_ID =", value, "memberId");
			return this;
		}

		public Criteria andMemberIdNotEqualTo(String value) {
			addCriterion("MEMBER_ID <>", value, "memberId");
			return this;
		}

		public Criteria andMemberIdGreaterThan(String value) {
			addCriterion("MEMBER_ID >", value, "memberId");
			return this;
		}

		public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
			addCriterion("MEMBER_ID >=", value, "memberId");
			return this;
		}

		public Criteria andMemberIdLessThan(String value) {
			addCriterion("MEMBER_ID <", value, "memberId");
			return this;
		}

		public Criteria andMemberIdLessThanOrEqualTo(String value) {
			addCriterion("MEMBER_ID <=", value, "memberId");
			return this;
		}

		public Criteria andMemberIdLike(String value) {
			addCriterion("MEMBER_ID like", value, "memberId");
			return this;
		}

		public Criteria andMemberIdNotLike(String value) {
			addCriterion("MEMBER_ID not like", value, "memberId");
			return this;
		}

		public Criteria andMemberIdIn(List<String> values) {
			addCriterion("MEMBER_ID in", values, "memberId");
			return this;
		}

		public Criteria andMemberIdNotIn(List<String> values) {
			addCriterion("MEMBER_ID not in", values, "memberId");
			return this;
		}

		public Criteria andMemberIdBetween(String value1, String value2) {
			addCriterion("MEMBER_ID between", value1, value2, "memberId");
			return this;
		}

		public Criteria andMemberIdNotBetween(String value1, String value2) {
			addCriterion("MEMBER_ID not between", value1, value2, "memberId");
			return this;
		}

		public Criteria andChecked1IsNull() {
			addCriterion("CHECKED1 is null");
			return this;
		}

		public Criteria andChecked1IsNotNull() {
			addCriterion("CHECKED1 is not null");
			return this;
		}

		public Criteria andChecked1EqualTo(Short value) {
			addCriterion("CHECKED1 =", value, "checked1");
			return this;
		}

		public Criteria andChecked1NotEqualTo(Short value) {
			addCriterion("CHECKED1 <>", value, "checked1");
			return this;
		}

		public Criteria andChecked1GreaterThan(Short value) {
			addCriterion("CHECKED1 >", value, "checked1");
			return this;
		}

		public Criteria andChecked1GreaterThanOrEqualTo(Short value) {
			addCriterion("CHECKED1 >=", value, "checked1");
			return this;
		}

		public Criteria andChecked1LessThan(Short value) {
			addCriterion("CHECKED1 <", value, "checked1");
			return this;
		}

		public Criteria andChecked1LessThanOrEqualTo(Short value) {
			addCriterion("CHECKED1 <=", value, "checked1");
			return this;
		}

		public Criteria andChecked1In(List<Short> values) {
			addCriterion("CHECKED1 in", values, "checked1");
			return this;
		}

		public Criteria andChecked1NotIn(List<Short> values) {
			addCriterion("CHECKED1 not in", values, "checked1");
			return this;
		}

		public Criteria andChecked1Between(Short value1, Short value2) {
			addCriterion("CHECKED1 between", value1, value2, "checked1");
			return this;
		}

		public Criteria andChecked1NotBetween(Short value1, Short value2) {
			addCriterion("CHECKED1 not between", value1, value2, "checked1");
			return this;
		}

		public Criteria andDetail1IsNull() {
			addCriterion("DETAIL1 is null");
			return this;
		}

		public Criteria andDetail1IsNotNull() {
			addCriterion("DETAIL1 is not null");
			return this;
		}

		public Criteria andDetail1EqualTo(String value) {
			addCriterion("DETAIL1 =", value, "detail1");
			return this;
		}

		public Criteria andDetail1NotEqualTo(String value) {
			addCriterion("DETAIL1 <>", value, "detail1");
			return this;
		}

		public Criteria andDetail1GreaterThan(String value) {
			addCriterion("DETAIL1 >", value, "detail1");
			return this;
		}

		public Criteria andDetail1GreaterThanOrEqualTo(String value) {
			addCriterion("DETAIL1 >=", value, "detail1");
			return this;
		}

		public Criteria andDetail1LessThan(String value) {
			addCriterion("DETAIL1 <", value, "detail1");
			return this;
		}

		public Criteria andDetail1LessThanOrEqualTo(String value) {
			addCriterion("DETAIL1 <=", value, "detail1");
			return this;
		}

		public Criteria andDetail1Like(String value) {
			addCriterion("DETAIL1 like", value, "detail1");
			return this;
		}

		public Criteria andDetail1NotLike(String value) {
			addCriterion("DETAIL1 not like", value, "detail1");
			return this;
		}

		public Criteria andDetail1In(List<String> values) {
			addCriterion("DETAIL1 in", values, "detail1");
			return this;
		}

		public Criteria andDetail1NotIn(List<String> values) {
			addCriterion("DETAIL1 not in", values, "detail1");
			return this;
		}

		public Criteria andDetail1Between(String value1, String value2) {
			addCriterion("DETAIL1 between", value1, value2, "detail1");
			return this;
		}

		public Criteria andDetail1NotBetween(String value1, String value2) {
			addCriterion("DETAIL1 not between", value1, value2, "detail1");
			return this;
		}

		public Criteria andChecktime1IsNull() {
			addCriterion("CHECKTIME1 is null");
			return this;
		}

		public Criteria andChecktime1IsNotNull() {
			addCriterion("CHECKTIME1 is not null");
			return this;
		}

		public Criteria andChecktime1EqualTo(Date value) {
			addCriterion("CHECKTIME1 =", value, "checktime1");
			return this;
		}

		public Criteria andChecktime1NotEqualTo(Date value) {
			addCriterion("CHECKTIME1 <>", value, "checktime1");
			return this;
		}

		public Criteria andChecktime1GreaterThan(Date value) {
			addCriterion("CHECKTIME1 >", value, "checktime1");
			return this;
		}

		public Criteria andChecktime1GreaterThanOrEqualTo(Date value) {
			addCriterion("CHECKTIME1 >=", value, "checktime1");
			return this;
		}

		public Criteria andChecktime1LessThan(Date value) {
			addCriterion("CHECKTIME1 <", value, "checktime1");
			return this;
		}

		public Criteria andChecktime1LessThanOrEqualTo(Date value) {
			addCriterion("CHECKTIME1 <=", value, "checktime1");
			return this;
		}

		public Criteria andChecktime1In(List<Date> values) {
			addCriterion("CHECKTIME1 in", values, "checktime1");
			return this;
		}

		public Criteria andChecktime1NotIn(List<Date> values) {
			addCriterion("CHECKTIME1 not in", values, "checktime1");
			return this;
		}

		public Criteria andChecktime1Between(Date value1, Date value2) {
			addCriterion("CHECKTIME1 between", value1, value2, "checktime1");
			return this;
		}

		public Criteria andChecktime1NotBetween(Date value1, Date value2) {
			addCriterion("CHECKTIME1 not between", value1, value2, "checktime1");
			return this;
		}

		public Criteria andOperator1nameIsNull() {
			addCriterion("OPERATOR1NAME is null");
			return this;
		}

		public Criteria andOperator1nameIsNotNull() {
			addCriterion("OPERATOR1NAME is not null");
			return this;
		}

		public Criteria andOperator1nameEqualTo(String value) {
			addCriterion("OPERATOR1NAME =", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameNotEqualTo(String value) {
			addCriterion("OPERATOR1NAME <>", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameGreaterThan(String value) {
			addCriterion("OPERATOR1NAME >", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR1NAME >=", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameLessThan(String value) {
			addCriterion("OPERATOR1NAME <", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR1NAME <=", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameLike(String value) {
			addCriterion("OPERATOR1NAME like", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameNotLike(String value) {
			addCriterion("OPERATOR1NAME not like", value, "operator1name");
			return this;
		}

		public Criteria andOperator1nameIn(List<String> values) {
			addCriterion("OPERATOR1NAME in", values, "operator1name");
			return this;
		}

		public Criteria andOperator1nameNotIn(List<String> values) {
			addCriterion("OPERATOR1NAME not in", values, "operator1name");
			return this;
		}

		public Criteria andOperator1nameBetween(String value1, String value2) {
			addCriterion("OPERATOR1NAME between", value1, value2,
					"operator1name");
			return this;
		}

		public Criteria andOperator1nameNotBetween(String value1, String value2) {
			addCriterion("OPERATOR1NAME not between", value1, value2,
					"operator1name");
			return this;
		}

		public Criteria andOperator1IsNull() {
			addCriterion("OPERATOR1 is null");
			return this;
		}

		public Criteria andOperator1IsNotNull() {
			addCriterion("OPERATOR1 is not null");
			return this;
		}

		public Criteria andOperator1EqualTo(String value) {
			addCriterion("OPERATOR1 =", value, "operator1");
			return this;
		}

		public Criteria andOperator1NotEqualTo(String value) {
			addCriterion("OPERATOR1 <>", value, "operator1");
			return this;
		}

		public Criteria andOperator1GreaterThan(String value) {
			addCriterion("OPERATOR1 >", value, "operator1");
			return this;
		}

		public Criteria andOperator1GreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR1 >=", value, "operator1");
			return this;
		}

		public Criteria andOperator1LessThan(String value) {
			addCriterion("OPERATOR1 <", value, "operator1");
			return this;
		}

		public Criteria andOperator1LessThanOrEqualTo(String value) {
			addCriterion("OPERATOR1 <=", value, "operator1");
			return this;
		}

		public Criteria andOperator1Like(String value) {
			addCriterion("OPERATOR1 like", value, "operator1");
			return this;
		}

		public Criteria andOperator1NotLike(String value) {
			addCriterion("OPERATOR1 not like", value, "operator1");
			return this;
		}

		public Criteria andOperator1In(List<String> values) {
			addCriterion("OPERATOR1 in", values, "operator1");
			return this;
		}

		public Criteria andOperator1NotIn(List<String> values) {
			addCriterion("OPERATOR1 not in", values, "operator1");
			return this;
		}

		public Criteria andOperator1Between(String value1, String value2) {
			addCriterion("OPERATOR1 between", value1, value2, "operator1");
			return this;
		}

		public Criteria andOperator1NotBetween(String value1, String value2) {
			addCriterion("OPERATOR1 not between", value1, value2, "operator1");
			return this;
		}

		public Criteria andOpttime1IsNull() {
			addCriterion("OPTTIME1 is null");
			return this;
		}

		public Criteria andOpttime1IsNotNull() {
			addCriterion("OPTTIME1 is not null");
			return this;
		}

		public Criteria andOpttime1EqualTo(Date value) {
			addCriterion("OPTTIME1 =", value, "opttime1");
			return this;
		}

		public Criteria andOpttime1NotEqualTo(Date value) {
			addCriterion("OPTTIME1 <>", value, "opttime1");
			return this;
		}

		public Criteria andOpttime1GreaterThan(Date value) {
			addCriterion("OPTTIME1 >", value, "opttime1");
			return this;
		}

		public Criteria andOpttime1GreaterThanOrEqualTo(Date value) {
			addCriterion("OPTTIME1 >=", value, "opttime1");
			return this;
		}

		public Criteria andOpttime1LessThan(Date value) {
			addCriterion("OPTTIME1 <", value, "opttime1");
			return this;
		}

		public Criteria andOpttime1LessThanOrEqualTo(Date value) {
			addCriterion("OPTTIME1 <=", value, "opttime1");
			return this;
		}

		public Criteria andOpttime1In(List<Date> values) {
			addCriterion("OPTTIME1 in", values, "opttime1");
			return this;
		}

		public Criteria andOpttime1NotIn(List<Date> values) {
			addCriterion("OPTTIME1 not in", values, "opttime1");
			return this;
		}

		public Criteria andOpttime1Between(Date value1, Date value2) {
			addCriterion("OPTTIME1 between", value1, value2, "opttime1");
			return this;
		}

		public Criteria andOpttime1NotBetween(Date value1, Date value2) {
			addCriterion("OPTTIME1 not between", value1, value2, "opttime1");
			return this;
		}

		public Criteria andChecked2IsNull() {
			addCriterion("CHECKED2 is null");
			return this;
		}

		public Criteria andChecked2IsNotNull() {
			addCriterion("CHECKED2 is not null");
			return this;
		}

		public Criteria andChecked2EqualTo(Short value) {
			addCriterion("CHECKED2 =", value, "checked2");
			return this;
		}

		public Criteria andChecked2NotEqualTo(Short value) {
			addCriterion("CHECKED2 <>", value, "checked2");
			return this;
		}

		public Criteria andChecked2GreaterThan(Short value) {
			addCriterion("CHECKED2 >", value, "checked2");
			return this;
		}

		public Criteria andChecked2GreaterThanOrEqualTo(Short value) {
			addCriterion("CHECKED2 >=", value, "checked2");
			return this;
		}

		public Criteria andChecked2LessThan(Short value) {
			addCriterion("CHECKED2 <", value, "checked2");
			return this;
		}

		public Criteria andChecked2LessThanOrEqualTo(Short value) {
			addCriterion("CHECKED2 <=", value, "checked2");
			return this;
		}

		public Criteria andChecked2In(List<Short> values) {
			addCriterion("CHECKED2 in", values, "checked2");
			return this;
		}

		public Criteria andChecked2NotIn(List<Short> values) {
			addCriterion("CHECKED2 not in", values, "checked2");
			return this;
		}

		public Criteria andChecked2Between(Short value1, Short value2) {
			addCriterion("CHECKED2 between", value1, value2, "checked2");
			return this;
		}

		public Criteria andChecked2NotBetween(Short value1, Short value2) {
			addCriterion("CHECKED2 not between", value1, value2, "checked2");
			return this;
		}

		public Criteria andDetail2IsNull() {
			addCriterion("DETAIL2 is null");
			return this;
		}

		public Criteria andDetail2IsNotNull() {
			addCriterion("DETAIL2 is not null");
			return this;
		}

		public Criteria andDetail2EqualTo(String value) {
			addCriterion("DETAIL2 =", value, "detail2");
			return this;
		}

		public Criteria andDetail2NotEqualTo(String value) {
			addCriterion("DETAIL2 <>", value, "detail2");
			return this;
		}

		public Criteria andDetail2GreaterThan(String value) {
			addCriterion("DETAIL2 >", value, "detail2");
			return this;
		}

		public Criteria andDetail2GreaterThanOrEqualTo(String value) {
			addCriterion("DETAIL2 >=", value, "detail2");
			return this;
		}

		public Criteria andDetail2LessThan(String value) {
			addCriterion("DETAIL2 <", value, "detail2");
			return this;
		}

		public Criteria andDetail2LessThanOrEqualTo(String value) {
			addCriterion("DETAIL2 <=", value, "detail2");
			return this;
		}

		public Criteria andDetail2Like(String value) {
			addCriterion("DETAIL2 like", value, "detail2");
			return this;
		}

		public Criteria andDetail2NotLike(String value) {
			addCriterion("DETAIL2 not like", value, "detail2");
			return this;
		}

		public Criteria andDetail2In(List<String> values) {
			addCriterion("DETAIL2 in", values, "detail2");
			return this;
		}

		public Criteria andDetail2NotIn(List<String> values) {
			addCriterion("DETAIL2 not in", values, "detail2");
			return this;
		}

		public Criteria andDetail2Between(String value1, String value2) {
			addCriterion("DETAIL2 between", value1, value2, "detail2");
			return this;
		}

		public Criteria andDetail2NotBetween(String value1, String value2) {
			addCriterion("DETAIL2 not between", value1, value2, "detail2");
			return this;
		}

		public Criteria andChecktime2IsNull() {
			addCriterion("CHECKTIME2 is null");
			return this;
		}

		public Criteria andChecktime2IsNotNull() {
			addCriterion("CHECKTIME2 is not null");
			return this;
		}

		public Criteria andChecktime2EqualTo(Date value) {
			addCriterion("CHECKTIME2 =", value, "checktime2");
			return this;
		}

		public Criteria andChecktime2NotEqualTo(Date value) {
			addCriterion("CHECKTIME2 <>", value, "checktime2");
			return this;
		}

		public Criteria andChecktime2GreaterThan(Date value) {
			addCriterion("CHECKTIME2 >", value, "checktime2");
			return this;
		}

		public Criteria andChecktime2GreaterThanOrEqualTo(Date value) {
			addCriterion("CHECKTIME2 >=", value, "checktime2");
			return this;
		}

		public Criteria andChecktime2LessThan(Date value) {
			addCriterion("CHECKTIME2 <", value, "checktime2");
			return this;
		}

		public Criteria andChecktime2LessThanOrEqualTo(Date value) {
			addCriterion("CHECKTIME2 <=", value, "checktime2");
			return this;
		}

		public Criteria andChecktime2In(List<Date> values) {
			addCriterion("CHECKTIME2 in", values, "checktime2");
			return this;
		}

		public Criteria andChecktime2NotIn(List<Date> values) {
			addCriterion("CHECKTIME2 not in", values, "checktime2");
			return this;
		}

		public Criteria andChecktime2Between(Date value1, Date value2) {
			addCriterion("CHECKTIME2 between", value1, value2, "checktime2");
			return this;
		}

		public Criteria andChecktime2NotBetween(Date value1, Date value2) {
			addCriterion("CHECKTIME2 not between", value1, value2, "checktime2");
			return this;
		}

		public Criteria andOperator2IsNull() {
			addCriterion("OPERATOR2 is null");
			return this;
		}

		public Criteria andOperator2IsNotNull() {
			addCriterion("OPERATOR2 is not null");
			return this;
		}

		public Criteria andOperator2EqualTo(String value) {
			addCriterion("OPERATOR2 =", value, "operator2");
			return this;
		}

		public Criteria andOperator2NotEqualTo(String value) {
			addCriterion("OPERATOR2 <>", value, "operator2");
			return this;
		}

		public Criteria andOperator2GreaterThan(String value) {
			addCriterion("OPERATOR2 >", value, "operator2");
			return this;
		}

		public Criteria andOperator2GreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR2 >=", value, "operator2");
			return this;
		}

		public Criteria andOperator2LessThan(String value) {
			addCriterion("OPERATOR2 <", value, "operator2");
			return this;
		}

		public Criteria andOperator2LessThanOrEqualTo(String value) {
			addCriterion("OPERATOR2 <=", value, "operator2");
			return this;
		}

		public Criteria andOperator2Like(String value) {
			addCriterion("OPERATOR2 like", value, "operator2");
			return this;
		}

		public Criteria andOperator2NotLike(String value) {
			addCriterion("OPERATOR2 not like", value, "operator2");
			return this;
		}

		public Criteria andOperator2In(List<String> values) {
			addCriterion("OPERATOR2 in", values, "operator2");
			return this;
		}

		public Criteria andOperator2NotIn(List<String> values) {
			addCriterion("OPERATOR2 not in", values, "operator2");
			return this;
		}

		public Criteria andOperator2Between(String value1, String value2) {
			addCriterion("OPERATOR2 between", value1, value2, "operator2");
			return this;
		}

		public Criteria andOperator2NotBetween(String value1, String value2) {
			addCriterion("OPERATOR2 not between", value1, value2, "operator2");
			return this;
		}

		public Criteria andOperator2nameIsNull() {
			addCriterion("OPERATOR2NAME is null");
			return this;
		}

		public Criteria andOperator2nameIsNotNull() {
			addCriterion("OPERATOR2NAME is not null");
			return this;
		}

		public Criteria andOperator2nameEqualTo(String value) {
			addCriterion("OPERATOR2NAME =", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameNotEqualTo(String value) {
			addCriterion("OPERATOR2NAME <>", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameGreaterThan(String value) {
			addCriterion("OPERATOR2NAME >", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameGreaterThanOrEqualTo(String value) {
			addCriterion("OPERATOR2NAME >=", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameLessThan(String value) {
			addCriterion("OPERATOR2NAME <", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameLessThanOrEqualTo(String value) {
			addCriterion("OPERATOR2NAME <=", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameLike(String value) {
			addCriterion("OPERATOR2NAME like", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameNotLike(String value) {
			addCriterion("OPERATOR2NAME not like", value, "operator2name");
			return this;
		}

		public Criteria andOperator2nameIn(List<String> values) {
			addCriterion("OPERATOR2NAME in", values, "operator2name");
			return this;
		}

		public Criteria andOperator2nameNotIn(List<String> values) {
			addCriterion("OPERATOR2NAME not in", values, "operator2name");
			return this;
		}

		public Criteria andOperator2nameBetween(String value1, String value2) {
			addCriterion("OPERATOR2NAME between", value1, value2,
					"operator2name");
			return this;
		}

		public Criteria andOperator2nameNotBetween(String value1, String value2) {
			addCriterion("OPERATOR2NAME not between", value1, value2,
					"operator2name");
			return this;
		}

		public Criteria andOpttime2IsNull() {
			addCriterion("OPTTIME2 is null");
			return this;
		}

		public Criteria andOpttime2IsNotNull() {
			addCriterion("OPTTIME2 is not null");
			return this;
		}

		public Criteria andOpttime2EqualTo(Date value) {
			addCriterion("OPTTIME2 =", value, "opttime2");
			return this;
		}

		public Criteria andOpttime2NotEqualTo(Date value) {
			addCriterion("OPTTIME2 <>", value, "opttime2");
			return this;
		}

		public Criteria andOpttime2GreaterThan(Date value) {
			addCriterion("OPTTIME2 >", value, "opttime2");
			return this;
		}

		public Criteria andOpttime2GreaterThanOrEqualTo(Date value) {
			addCriterion("OPTTIME2 >=", value, "opttime2");
			return this;
		}

		public Criteria andOpttime2LessThan(Date value) {
			addCriterion("OPTTIME2 <", value, "opttime2");
			return this;
		}

		public Criteria andOpttime2LessThanOrEqualTo(Date value) {
			addCriterion("OPTTIME2 <=", value, "opttime2");
			return this;
		}

		public Criteria andOpttime2In(List<Date> values) {
			addCriterion("OPTTIME2 in", values, "opttime2");
			return this;
		}

		public Criteria andOpttime2NotIn(List<Date> values) {
			addCriterion("OPTTIME2 not in", values, "opttime2");
			return this;
		}

		public Criteria andOpttime2Between(Date value1, Date value2) {
			addCriterion("OPTTIME2 between", value1, value2, "opttime2");
			return this;
		}

		public Criteria andOpttime2NotBetween(Date value1, Date value2) {
			addCriterion("OPTTIME2 not between", value1, value2, "opttime2");
			return this;
		}

		public Criteria andStsIsNull() {
			addCriterion("STS is null");
			return this;
		}

		public Criteria andStsIsNotNull() {
			addCriterion("STS is not null");
			return this;
		}

		public Criteria andStsEqualTo(String value) {
			addCriterion("STS =", value, "sts");
			return this;
		}

		public Criteria andStsNotEqualTo(String value) {
			addCriterion("STS <>", value, "sts");
			return this;
		}

		public Criteria andStsGreaterThan(String value) {
			addCriterion("STS >", value, "sts");
			return this;
		}

		public Criteria andStsGreaterThanOrEqualTo(String value) {
			addCriterion("STS >=", value, "sts");
			return this;
		}

		public Criteria andStsLessThan(String value) {
			addCriterion("STS <", value, "sts");
			return this;
		}

		public Criteria andStsLessThanOrEqualTo(String value) {
			addCriterion("STS <=", value, "sts");
			return this;
		}

		public Criteria andStsLike(String value) {
			addCriterion("STS like", value, "sts");
			return this;
		}

		public Criteria andStsNotLike(String value) {
			addCriterion("STS not like", value, "sts");
			return this;
		}

		public Criteria andStsIn(List<String> values) {
			addCriterion("STS in", values, "sts");
			return this;
		}

		public Criteria andStsNotIn(List<String> values) {
			addCriterion("STS not in", values, "sts");
			return this;
		}

		public Criteria andStsBetween(String value1, String value2) {
			addCriterion("STS between", value1, value2, "sts");
			return this;
		}

		public Criteria andStsNotBetween(String value1, String value2) {
			addCriterion("STS not between", value1, value2, "sts");
			return this;
		}

		public Criteria andIcdIdIsNull() {
			addCriterion("ICD_ID is null");
			return this;
		}

		public Criteria andIcdIdIsNotNull() {
			addCriterion("ICD_ID is not null");
			return this;
		}

		public Criteria andIcdIdEqualTo(String value) {
			addCriterion("ICD_ID =", value, "icdId");
			return this;
		}

		public Criteria andIcdIdNotEqualTo(String value) {
			addCriterion("ICD_ID <>", value, "icdId");
			return this;
		}

		public Criteria andIcdIdGreaterThan(String value) {
			addCriterion("ICD_ID >", value, "icdId");
			return this;
		}

		public Criteria andIcdIdGreaterThanOrEqualTo(String value) {
			addCriterion("ICD_ID >=", value, "icdId");
			return this;
		}

		public Criteria andIcdIdLessThan(String value) {
			addCriterion("ICD_ID <", value, "icdId");
			return this;
		}

		public Criteria andIcdIdLessThanOrEqualTo(String value) {
			addCriterion("ICD_ID <=", value, "icdId");
			return this;
		}

		public Criteria andIcdIdLike(String value) {
			addCriterion("ICD_ID like", value, "icdId");
			return this;
		}

		public Criteria andIcdIdNotLike(String value) {
			addCriterion("ICD_ID not like", value, "icdId");
			return this;
		}

		public Criteria andIcdIdIn(List<String> values) {
			addCriterion("ICD_ID in", values, "icdId");
			return this;
		}

		public Criteria andIcdIdNotIn(List<String> values) {
			addCriterion("ICD_ID not in", values, "icdId");
			return this;
		}

		public Criteria andIcdIdBetween(String value1, String value2) {
			addCriterion("ICD_ID between", value1, value2, "icdId");
			return this;
		}

		public Criteria andIcdIdNotBetween(String value1, String value2) {
			addCriterion("ICD_ID not between", value1, value2, "icdId");
			return this;
		}

		public Criteria andMainIdIsNull() {
			addCriterion("MAIN_ID is null");
			return this;
		}

		public Criteria andMainIdIsNotNull() {
			addCriterion("MAIN_ID is not null");
			return this;
		}

		public Criteria andMainIdEqualTo(String value) {
			addCriterion("MAIN_ID =", value, "mainId");
			return this;
		}

		public Criteria andMainIdNotEqualTo(String value) {
			addCriterion("MAIN_ID <>", value, "mainId");
			return this;
		}

		public Criteria andMainIdGreaterThan(String value) {
			addCriterion("MAIN_ID >", value, "mainId");
			return this;
		}

		public Criteria andMainIdGreaterThanOrEqualTo(String value) {
			addCriterion("MAIN_ID >=", value, "mainId");
			return this;
		}

		public Criteria andMainIdLessThan(String value) {
			addCriterion("MAIN_ID <", value, "mainId");
			return this;
		}

		public Criteria andMainIdLessThanOrEqualTo(String value) {
			addCriterion("MAIN_ID <=", value, "mainId");
			return this;
		}

		public Criteria andMainIdLike(String value) {
			addCriterion("MAIN_ID like", value, "mainId");
			return this;
		}

		public Criteria andMainIdNotLike(String value) {
			addCriterion("MAIN_ID not like", value, "mainId");
			return this;
		}

		public Criteria andMainIdIn(List<String> values) {
			addCriterion("MAIN_ID in", values, "mainId");
			return this;
		}

		public Criteria andMainIdNotIn(List<String> values) {
			addCriterion("MAIN_ID not in", values, "mainId");
			return this;
		}

		public Criteria andMainIdBetween(String value1, String value2) {
			addCriterion("MAIN_ID between", value1, value2, "mainId");
			return this;
		}

		public Criteria andMainIdNotBetween(String value1, String value2) {
			addCriterion("MAIN_ID not between", value1, value2, "mainId");
			return this;
		}
	}
}