package com.mingda.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzBizcheck {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private BigDecimal bizcheck;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.BIZ_ID
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private Integer bizId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.CHECKED1
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private BigDecimal checked1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.DETAIL1
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private String detail1;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.CHECKTIME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private Date checktime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.OPERATOR
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private String operator;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.OPTTIME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private Date opttime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.CHECKED2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private BigDecimal checked2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.DETAIL2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private String detail2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.CHECKTIME2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private Date checktime2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.OPERATOR2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private String operator2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.OPTTIME2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private Date opttime2;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.OPERATORNAME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private String operatorname;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.OPERATOR2NAME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private String operator2name;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.JZ_BIZCHECK.DS
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	private String ds;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.BIZCHECK
	 * @return  the value of MEDICAL.JZ_BIZCHECK.BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public BigDecimal getBizcheck() {
		return bizcheck;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.BIZCHECK
	 * @param bizcheck  the value for MEDICAL.JZ_BIZCHECK.BIZCHECK
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setBizcheck(BigDecimal bizcheck) {
		this.bizcheck = bizcheck;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.BIZ_ID
	 * @return  the value of MEDICAL.JZ_BIZCHECK.BIZ_ID
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public Integer getBizId() {
		return bizId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.BIZ_ID
	 * @param bizId  the value for MEDICAL.JZ_BIZCHECK.BIZ_ID
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setBizId(Integer bizId) {
		this.bizId = bizId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.CHECKED1
	 * @return  the value of MEDICAL.JZ_BIZCHECK.CHECKED1
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public BigDecimal getChecked1() {
		return checked1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.CHECKED1
	 * @param checked1  the value for MEDICAL.JZ_BIZCHECK.CHECKED1
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setChecked1(BigDecimal checked1) {
		this.checked1 = checked1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.DETAIL1
	 * @return  the value of MEDICAL.JZ_BIZCHECK.DETAIL1
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public String getDetail1() {
		return detail1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.DETAIL1
	 * @param detail1  the value for MEDICAL.JZ_BIZCHECK.DETAIL1
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setDetail1(String detail1) {
		this.detail1 = detail1;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.CHECKTIME
	 * @return  the value of MEDICAL.JZ_BIZCHECK.CHECKTIME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public Date getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.CHECKTIME
	 * @param checktime  the value for MEDICAL.JZ_BIZCHECK.CHECKTIME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setChecktime(Date checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.OPERATOR
	 * @return  the value of MEDICAL.JZ_BIZCHECK.OPERATOR
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.OPERATOR
	 * @param operator  the value for MEDICAL.JZ_BIZCHECK.OPERATOR
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.OPTTIME
	 * @return  the value of MEDICAL.JZ_BIZCHECK.OPTTIME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public Date getOpttime() {
		return opttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.OPTTIME
	 * @param opttime  the value for MEDICAL.JZ_BIZCHECK.OPTTIME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setOpttime(Date opttime) {
		this.opttime = opttime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.CHECKED2
	 * @return  the value of MEDICAL.JZ_BIZCHECK.CHECKED2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public BigDecimal getChecked2() {
		return checked2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.CHECKED2
	 * @param checked2  the value for MEDICAL.JZ_BIZCHECK.CHECKED2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setChecked2(BigDecimal checked2) {
		this.checked2 = checked2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.DETAIL2
	 * @return  the value of MEDICAL.JZ_BIZCHECK.DETAIL2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public String getDetail2() {
		return detail2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.DETAIL2
	 * @param detail2  the value for MEDICAL.JZ_BIZCHECK.DETAIL2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setDetail2(String detail2) {
		this.detail2 = detail2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.CHECKTIME2
	 * @return  the value of MEDICAL.JZ_BIZCHECK.CHECKTIME2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public Date getChecktime2() {
		return checktime2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.CHECKTIME2
	 * @param checktime2  the value for MEDICAL.JZ_BIZCHECK.CHECKTIME2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setChecktime2(Date checktime2) {
		this.checktime2 = checktime2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.OPERATOR2
	 * @return  the value of MEDICAL.JZ_BIZCHECK.OPERATOR2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public String getOperator2() {
		return operator2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.OPERATOR2
	 * @param operator2  the value for MEDICAL.JZ_BIZCHECK.OPERATOR2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setOperator2(String operator2) {
		this.operator2 = operator2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.OPTTIME2
	 * @return  the value of MEDICAL.JZ_BIZCHECK.OPTTIME2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public Date getOpttime2() {
		return opttime2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.OPTTIME2
	 * @param opttime2  the value for MEDICAL.JZ_BIZCHECK.OPTTIME2
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setOpttime2(Date opttime2) {
		this.opttime2 = opttime2;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.OPERATORNAME
	 * @return  the value of MEDICAL.JZ_BIZCHECK.OPERATORNAME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public String getOperatorname() {
		return operatorname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.OPERATORNAME
	 * @param operatorname  the value for MEDICAL.JZ_BIZCHECK.OPERATORNAME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setOperatorname(String operatorname) {
		this.operatorname = operatorname;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.OPERATOR2NAME
	 * @return  the value of MEDICAL.JZ_BIZCHECK.OPERATOR2NAME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public String getOperator2name() {
		return operator2name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.OPERATOR2NAME
	 * @param operator2name  the value for MEDICAL.JZ_BIZCHECK.OPERATOR2NAME
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setOperator2name(String operator2name) {
		this.operator2name = operator2name;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.JZ_BIZCHECK.DS
	 * @return  the value of MEDICAL.JZ_BIZCHECK.DS
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public String getDs() {
		return ds;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.JZ_BIZCHECK.DS
	 * @param ds  the value for MEDICAL.JZ_BIZCHECK.DS
	 * @ibatorgenerated  Tue Jun 25 18:42:38 CST 2013
	 */
	public void setDs(String ds) {
		this.ds = ds;
	}
}