package com.mingda.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class JzMedicalafterRuleExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public JzMedicalafterRuleExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	protected JzMedicalafterRuleExample(JzMedicalafterRuleExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table MEDICAL.JZ_MEDICALAFTER_RULE
	 * @ibatorgenerated  Thu Apr 11 15:47:37 CST 2013
	 */
	public static class Criteria {
		protected List<String> criteriaWithoutValue;
		protected List<Map<String, Object>> criteriaWithSingleValue;
		protected List<Map<String, Object>> criteriaWithListValue;
		protected List<Map<String, Object>> criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList<String>();
			criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
			criteriaWithListValue = new ArrayList<Map<String, Object>>();
			criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0
					|| criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0
					|| criteriaWithBetweenValue.size() > 0;
		}

		public List<String> getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List<Map<String, Object>> getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List<Map<String, Object>> getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List<Map<String, Object>> getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition,
				List<? extends Object> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			List<Object> list = new ArrayList<Object>();
			list.add(value1);
			list.add(value2);
			Map<String, Object> map = new HashMap<String, Object>();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		public Criteria andRuleIdIsNull() {
			addCriterion("RULE_ID is null");
			return this;
		}

		public Criteria andRuleIdIsNotNull() {
			addCriterion("RULE_ID is not null");
			return this;
		}

		public Criteria andRuleIdEqualTo(BigDecimal value) {
			addCriterion("RULE_ID =", value, "ruleId");
			return this;
		}

		public Criteria andRuleIdNotEqualTo(BigDecimal value) {
			addCriterion("RULE_ID <>", value, "ruleId");
			return this;
		}

		public Criteria andRuleIdGreaterThan(BigDecimal value) {
			addCriterion("RULE_ID >", value, "ruleId");
			return this;
		}

		public Criteria andRuleIdGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("RULE_ID >=", value, "ruleId");
			return this;
		}

		public Criteria andRuleIdLessThan(BigDecimal value) {
			addCriterion("RULE_ID <", value, "ruleId");
			return this;
		}

		public Criteria andRuleIdLessThanOrEqualTo(BigDecimal value) {
			addCriterion("RULE_ID <=", value, "ruleId");
			return this;
		}

		public Criteria andRuleIdIn(List<BigDecimal> values) {
			addCriterion("RULE_ID in", values, "ruleId");
			return this;
		}

		public Criteria andRuleIdNotIn(List<BigDecimal> values) {
			addCriterion("RULE_ID not in", values, "ruleId");
			return this;
		}

		public Criteria andRuleIdBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("RULE_ID between", value1, value2, "ruleId");
			return this;
		}

		public Criteria andRuleIdNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("RULE_ID not between", value1, value2, "ruleId");
			return this;
		}

		public Criteria andOrganizationIdIsNull() {
			addCriterion("ORGANIZATION_ID is null");
			return this;
		}

		public Criteria andOrganizationIdIsNotNull() {
			addCriterion("ORGANIZATION_ID is not null");
			return this;
		}

		public Criteria andOrganizationIdEqualTo(String value) {
			addCriterion("ORGANIZATION_ID =", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdNotEqualTo(String value) {
			addCriterion("ORGANIZATION_ID <>", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdGreaterThan(String value) {
			addCriterion("ORGANIZATION_ID >", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdGreaterThanOrEqualTo(String value) {
			addCriterion("ORGANIZATION_ID >=", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdLessThan(String value) {
			addCriterion("ORGANIZATION_ID <", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdLessThanOrEqualTo(String value) {
			addCriterion("ORGANIZATION_ID <=", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdLike(String value) {
			addCriterion("ORGANIZATION_ID like", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdNotLike(String value) {
			addCriterion("ORGANIZATION_ID not like", value, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdIn(List<String> values) {
			addCriterion("ORGANIZATION_ID in", values, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdNotIn(List<String> values) {
			addCriterion("ORGANIZATION_ID not in", values, "organizationId");
			return this;
		}

		public Criteria andOrganizationIdBetween(String value1, String value2) {
			addCriterion("ORGANIZATION_ID between", value1, value2,
					"organizationId");
			return this;
		}

		public Criteria andOrganizationIdNotBetween(String value1, String value2) {
			addCriterion("ORGANIZATION_ID not between", value1, value2,
					"organizationId");
			return this;
		}

		public Criteria andMztsTopLineIsNull() {
			addCriterion("MZTS_TOP_LINE is null");
			return this;
		}

		public Criteria andMztsTopLineIsNotNull() {
			addCriterion("MZTS_TOP_LINE is not null");
			return this;
		}

		public Criteria andMztsTopLineEqualTo(BigDecimal value) {
			addCriterion("MZTS_TOP_LINE =", value, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineNotEqualTo(BigDecimal value) {
			addCriterion("MZTS_TOP_LINE <>", value, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineGreaterThan(BigDecimal value) {
			addCriterion("MZTS_TOP_LINE >", value, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("MZTS_TOP_LINE >=", value, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineLessThan(BigDecimal value) {
			addCriterion("MZTS_TOP_LINE <", value, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineLessThanOrEqualTo(BigDecimal value) {
			addCriterion("MZTS_TOP_LINE <=", value, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineIn(List<BigDecimal> values) {
			addCriterion("MZTS_TOP_LINE in", values, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineNotIn(List<BigDecimal> values) {
			addCriterion("MZTS_TOP_LINE not in", values, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MZTS_TOP_LINE between", value1, value2, "mztsTopLine");
			return this;
		}

		public Criteria andMztsTopLineNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MZTS_TOP_LINE not between", value1, value2,
					"mztsTopLine");
			return this;
		}

		public Criteria andMztsSlIsNull() {
			addCriterion("MZTS_SL is null");
			return this;
		}

		public Criteria andMztsSlIsNotNull() {
			addCriterion("MZTS_SL is not null");
			return this;
		}

		public Criteria andMztsSlEqualTo(BigDecimal value) {
			addCriterion("MZTS_SL =", value, "mztsSl");
			return this;
		}

		public Criteria andMztsSlNotEqualTo(BigDecimal value) {
			addCriterion("MZTS_SL <>", value, "mztsSl");
			return this;
		}

		public Criteria andMztsSlGreaterThan(BigDecimal value) {
			addCriterion("MZTS_SL >", value, "mztsSl");
			return this;
		}

		public Criteria andMztsSlGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("MZTS_SL >=", value, "mztsSl");
			return this;
		}

		public Criteria andMztsSlLessThan(BigDecimal value) {
			addCriterion("MZTS_SL <", value, "mztsSl");
			return this;
		}

		public Criteria andMztsSlLessThanOrEqualTo(BigDecimal value) {
			addCriterion("MZTS_SL <=", value, "mztsSl");
			return this;
		}

		public Criteria andMztsSlIn(List<BigDecimal> values) {
			addCriterion("MZTS_SL in", values, "mztsSl");
			return this;
		}

		public Criteria andMztsSlNotIn(List<BigDecimal> values) {
			addCriterion("MZTS_SL not in", values, "mztsSl");
			return this;
		}

		public Criteria andMztsSlBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("MZTS_SL between", value1, value2, "mztsSl");
			return this;
		}

		public Criteria andMztsSlNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("MZTS_SL not between", value1, value2, "mztsSl");
			return this;
		}

		public Criteria andMztsScaleIsNull() {
			addCriterion("MZTS_SCALE is null");
			return this;
		}

		public Criteria andMztsScaleIsNotNull() {
			addCriterion("MZTS_SCALE is not null");
			return this;
		}

		public Criteria andMztsScaleEqualTo(BigDecimal value) {
			addCriterion("MZTS_SCALE =", value, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleNotEqualTo(BigDecimal value) {
			addCriterion("MZTS_SCALE <>", value, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleGreaterThan(BigDecimal value) {
			addCriterion("MZTS_SCALE >", value, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("MZTS_SCALE >=", value, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleLessThan(BigDecimal value) {
			addCriterion("MZTS_SCALE <", value, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleLessThanOrEqualTo(BigDecimal value) {
			addCriterion("MZTS_SCALE <=", value, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleIn(List<BigDecimal> values) {
			addCriterion("MZTS_SCALE in", values, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleNotIn(List<BigDecimal> values) {
			addCriterion("MZTS_SCALE not in", values, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("MZTS_SCALE between", value1, value2, "mztsScale");
			return this;
		}

		public Criteria andMztsScaleNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("MZTS_SCALE not between", value1, value2, "mztsScale");
			return this;
		}

		public Criteria andZySlIsNull() {
			addCriterion("ZY_SL is null");
			return this;
		}

		public Criteria andZySlIsNotNull() {
			addCriterion("ZY_SL is not null");
			return this;
		}

		public Criteria andZySlEqualTo(BigDecimal value) {
			addCriterion("ZY_SL =", value, "zySl");
			return this;
		}

		public Criteria andZySlNotEqualTo(BigDecimal value) {
			addCriterion("ZY_SL <>", value, "zySl");
			return this;
		}

		public Criteria andZySlGreaterThan(BigDecimal value) {
			addCriterion("ZY_SL >", value, "zySl");
			return this;
		}

		public Criteria andZySlGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SL >=", value, "zySl");
			return this;
		}

		public Criteria andZySlLessThan(BigDecimal value) {
			addCriterion("ZY_SL <", value, "zySl");
			return this;
		}

		public Criteria andZySlLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SL <=", value, "zySl");
			return this;
		}

		public Criteria andZySlIn(List<BigDecimal> values) {
			addCriterion("ZY_SL in", values, "zySl");
			return this;
		}

		public Criteria andZySlNotIn(List<BigDecimal> values) {
			addCriterion("ZY_SL not in", values, "zySl");
			return this;
		}

		public Criteria andZySlBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_SL between", value1, value2, "zySl");
			return this;
		}

		public Criteria andZySlNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_SL not between", value1, value2, "zySl");
			return this;
		}

		public Criteria andZyScale1IsNull() {
			addCriterion("ZY_SCALE1 is null");
			return this;
		}

		public Criteria andZyScale1IsNotNull() {
			addCriterion("ZY_SCALE1 is not null");
			return this;
		}

		public Criteria andZyScale1EqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE1 =", value, "zyScale1");
			return this;
		}

		public Criteria andZyScale1NotEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE1 <>", value, "zyScale1");
			return this;
		}

		public Criteria andZyScale1GreaterThan(BigDecimal value) {
			addCriterion("ZY_SCALE1 >", value, "zyScale1");
			return this;
		}

		public Criteria andZyScale1GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE1 >=", value, "zyScale1");
			return this;
		}

		public Criteria andZyScale1LessThan(BigDecimal value) {
			addCriterion("ZY_SCALE1 <", value, "zyScale1");
			return this;
		}

		public Criteria andZyScale1LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE1 <=", value, "zyScale1");
			return this;
		}

		public Criteria andZyScale1In(List<BigDecimal> values) {
			addCriterion("ZY_SCALE1 in", values, "zyScale1");
			return this;
		}

		public Criteria andZyScale1NotIn(List<BigDecimal> values) {
			addCriterion("ZY_SCALE1 not in", values, "zyScale1");
			return this;
		}

		public Criteria andZyScale1Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_SCALE1 between", value1, value2, "zyScale1");
			return this;
		}

		public Criteria andZyScale1NotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ZY_SCALE1 not between", value1, value2, "zyScale1");
			return this;
		}

		public Criteria andZyM1IsNull() {
			addCriterion("ZY_M1 is null");
			return this;
		}

		public Criteria andZyM1IsNotNull() {
			addCriterion("ZY_M1 is not null");
			return this;
		}

		public Criteria andZyM1EqualTo(BigDecimal value) {
			addCriterion("ZY_M1 =", value, "zyM1");
			return this;
		}

		public Criteria andZyM1NotEqualTo(BigDecimal value) {
			addCriterion("ZY_M1 <>", value, "zyM1");
			return this;
		}

		public Criteria andZyM1GreaterThan(BigDecimal value) {
			addCriterion("ZY_M1 >", value, "zyM1");
			return this;
		}

		public Criteria andZyM1GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M1 >=", value, "zyM1");
			return this;
		}

		public Criteria andZyM1LessThan(BigDecimal value) {
			addCriterion("ZY_M1 <", value, "zyM1");
			return this;
		}

		public Criteria andZyM1LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M1 <=", value, "zyM1");
			return this;
		}

		public Criteria andZyM1In(List<BigDecimal> values) {
			addCriterion("ZY_M1 in", values, "zyM1");
			return this;
		}

		public Criteria andZyM1NotIn(List<BigDecimal> values) {
			addCriterion("ZY_M1 not in", values, "zyM1");
			return this;
		}

		public Criteria andZyM1Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M1 between", value1, value2, "zyM1");
			return this;
		}

		public Criteria andZyM1NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M1 not between", value1, value2, "zyM1");
			return this;
		}

		public Criteria andZyScale2IsNull() {
			addCriterion("ZY_SCALE2 is null");
			return this;
		}

		public Criteria andZyScale2IsNotNull() {
			addCriterion("ZY_SCALE2 is not null");
			return this;
		}

		public Criteria andZyScale2EqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE2 =", value, "zyScale2");
			return this;
		}

		public Criteria andZyScale2NotEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE2 <>", value, "zyScale2");
			return this;
		}

		public Criteria andZyScale2GreaterThan(BigDecimal value) {
			addCriterion("ZY_SCALE2 >", value, "zyScale2");
			return this;
		}

		public Criteria andZyScale2GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE2 >=", value, "zyScale2");
			return this;
		}

		public Criteria andZyScale2LessThan(BigDecimal value) {
			addCriterion("ZY_SCALE2 <", value, "zyScale2");
			return this;
		}

		public Criteria andZyScale2LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE2 <=", value, "zyScale2");
			return this;
		}

		public Criteria andZyScale2In(List<BigDecimal> values) {
			addCriterion("ZY_SCALE2 in", values, "zyScale2");
			return this;
		}

		public Criteria andZyScale2NotIn(List<BigDecimal> values) {
			addCriterion("ZY_SCALE2 not in", values, "zyScale2");
			return this;
		}

		public Criteria andZyScale2Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_SCALE2 between", value1, value2, "zyScale2");
			return this;
		}

		public Criteria andZyScale2NotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ZY_SCALE2 not between", value1, value2, "zyScale2");
			return this;
		}

		public Criteria andZyM2IsNull() {
			addCriterion("ZY_M2 is null");
			return this;
		}

		public Criteria andZyM2IsNotNull() {
			addCriterion("ZY_M2 is not null");
			return this;
		}

		public Criteria andZyM2EqualTo(BigDecimal value) {
			addCriterion("ZY_M2 =", value, "zyM2");
			return this;
		}

		public Criteria andZyM2NotEqualTo(BigDecimal value) {
			addCriterion("ZY_M2 <>", value, "zyM2");
			return this;
		}

		public Criteria andZyM2GreaterThan(BigDecimal value) {
			addCriterion("ZY_M2 >", value, "zyM2");
			return this;
		}

		public Criteria andZyM2GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M2 >=", value, "zyM2");
			return this;
		}

		public Criteria andZyM2LessThan(BigDecimal value) {
			addCriterion("ZY_M2 <", value, "zyM2");
			return this;
		}

		public Criteria andZyM2LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M2 <=", value, "zyM2");
			return this;
		}

		public Criteria andZyM2In(List<BigDecimal> values) {
			addCriterion("ZY_M2 in", values, "zyM2");
			return this;
		}

		public Criteria andZyM2NotIn(List<BigDecimal> values) {
			addCriterion("ZY_M2 not in", values, "zyM2");
			return this;
		}

		public Criteria andZyM2Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M2 between", value1, value2, "zyM2");
			return this;
		}

		public Criteria andZyM2NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M2 not between", value1, value2, "zyM2");
			return this;
		}

		public Criteria andZyScale3IsNull() {
			addCriterion("ZY_SCALE3 is null");
			return this;
		}

		public Criteria andZyScale3IsNotNull() {
			addCriterion("ZY_SCALE3 is not null");
			return this;
		}

		public Criteria andZyScale3EqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE3 =", value, "zyScale3");
			return this;
		}

		public Criteria andZyScale3NotEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE3 <>", value, "zyScale3");
			return this;
		}

		public Criteria andZyScale3GreaterThan(BigDecimal value) {
			addCriterion("ZY_SCALE3 >", value, "zyScale3");
			return this;
		}

		public Criteria andZyScale3GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE3 >=", value, "zyScale3");
			return this;
		}

		public Criteria andZyScale3LessThan(BigDecimal value) {
			addCriterion("ZY_SCALE3 <", value, "zyScale3");
			return this;
		}

		public Criteria andZyScale3LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE3 <=", value, "zyScale3");
			return this;
		}

		public Criteria andZyScale3In(List<BigDecimal> values) {
			addCriterion("ZY_SCALE3 in", values, "zyScale3");
			return this;
		}

		public Criteria andZyScale3NotIn(List<BigDecimal> values) {
			addCriterion("ZY_SCALE3 not in", values, "zyScale3");
			return this;
		}

		public Criteria andZyScale3Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_SCALE3 between", value1, value2, "zyScale3");
			return this;
		}

		public Criteria andZyScale3NotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ZY_SCALE3 not between", value1, value2, "zyScale3");
			return this;
		}

		public Criteria andZyM3IsNull() {
			addCriterion("ZY_M3 is null");
			return this;
		}

		public Criteria andZyM3IsNotNull() {
			addCriterion("ZY_M3 is not null");
			return this;
		}

		public Criteria andZyM3EqualTo(BigDecimal value) {
			addCriterion("ZY_M3 =", value, "zyM3");
			return this;
		}

		public Criteria andZyM3NotEqualTo(BigDecimal value) {
			addCriterion("ZY_M3 <>", value, "zyM3");
			return this;
		}

		public Criteria andZyM3GreaterThan(BigDecimal value) {
			addCriterion("ZY_M3 >", value, "zyM3");
			return this;
		}

		public Criteria andZyM3GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M3 >=", value, "zyM3");
			return this;
		}

		public Criteria andZyM3LessThan(BigDecimal value) {
			addCriterion("ZY_M3 <", value, "zyM3");
			return this;
		}

		public Criteria andZyM3LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M3 <=", value, "zyM3");
			return this;
		}

		public Criteria andZyM3In(List<BigDecimal> values) {
			addCriterion("ZY_M3 in", values, "zyM3");
			return this;
		}

		public Criteria andZyM3NotIn(List<BigDecimal> values) {
			addCriterion("ZY_M3 not in", values, "zyM3");
			return this;
		}

		public Criteria andZyM3Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M3 between", value1, value2, "zyM3");
			return this;
		}

		public Criteria andZyM3NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M3 not between", value1, value2, "zyM3");
			return this;
		}

		public Criteria andZyScale4IsNull() {
			addCriterion("ZY_SCALE4 is null");
			return this;
		}

		public Criteria andZyScale4IsNotNull() {
			addCriterion("ZY_SCALE4 is not null");
			return this;
		}

		public Criteria andZyScale4EqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE4 =", value, "zyScale4");
			return this;
		}

		public Criteria andZyScale4NotEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE4 <>", value, "zyScale4");
			return this;
		}

		public Criteria andZyScale4GreaterThan(BigDecimal value) {
			addCriterion("ZY_SCALE4 >", value, "zyScale4");
			return this;
		}

		public Criteria andZyScale4GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE4 >=", value, "zyScale4");
			return this;
		}

		public Criteria andZyScale4LessThan(BigDecimal value) {
			addCriterion("ZY_SCALE4 <", value, "zyScale4");
			return this;
		}

		public Criteria andZyScale4LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE4 <=", value, "zyScale4");
			return this;
		}

		public Criteria andZyScale4In(List<BigDecimal> values) {
			addCriterion("ZY_SCALE4 in", values, "zyScale4");
			return this;
		}

		public Criteria andZyScale4NotIn(List<BigDecimal> values) {
			addCriterion("ZY_SCALE4 not in", values, "zyScale4");
			return this;
		}

		public Criteria andZyScale4Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_SCALE4 between", value1, value2, "zyScale4");
			return this;
		}

		public Criteria andZyScale4NotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ZY_SCALE4 not between", value1, value2, "zyScale4");
			return this;
		}

		public Criteria andZyM4IsNull() {
			addCriterion("ZY_M4 is null");
			return this;
		}

		public Criteria andZyM4IsNotNull() {
			addCriterion("ZY_M4 is not null");
			return this;
		}

		public Criteria andZyM4EqualTo(BigDecimal value) {
			addCriterion("ZY_M4 =", value, "zyM4");
			return this;
		}

		public Criteria andZyM4NotEqualTo(BigDecimal value) {
			addCriterion("ZY_M4 <>", value, "zyM4");
			return this;
		}

		public Criteria andZyM4GreaterThan(BigDecimal value) {
			addCriterion("ZY_M4 >", value, "zyM4");
			return this;
		}

		public Criteria andZyM4GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M4 >=", value, "zyM4");
			return this;
		}

		public Criteria andZyM4LessThan(BigDecimal value) {
			addCriterion("ZY_M4 <", value, "zyM4");
			return this;
		}

		public Criteria andZyM4LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_M4 <=", value, "zyM4");
			return this;
		}

		public Criteria andZyM4In(List<BigDecimal> values) {
			addCriterion("ZY_M4 in", values, "zyM4");
			return this;
		}

		public Criteria andZyM4NotIn(List<BigDecimal> values) {
			addCriterion("ZY_M4 not in", values, "zyM4");
			return this;
		}

		public Criteria andZyM4Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M4 between", value1, value2, "zyM4");
			return this;
		}

		public Criteria andZyM4NotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_M4 not between", value1, value2, "zyM4");
			return this;
		}

		public Criteria andZyScale5IsNull() {
			addCriterion("ZY_SCALE5 is null");
			return this;
		}

		public Criteria andZyScale5IsNotNull() {
			addCriterion("ZY_SCALE5 is not null");
			return this;
		}

		public Criteria andZyScale5EqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE5 =", value, "zyScale5");
			return this;
		}

		public Criteria andZyScale5NotEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE5 <>", value, "zyScale5");
			return this;
		}

		public Criteria andZyScale5GreaterThan(BigDecimal value) {
			addCriterion("ZY_SCALE5 >", value, "zyScale5");
			return this;
		}

		public Criteria andZyScale5GreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE5 >=", value, "zyScale5");
			return this;
		}

		public Criteria andZyScale5LessThan(BigDecimal value) {
			addCriterion("ZY_SCALE5 <", value, "zyScale5");
			return this;
		}

		public Criteria andZyScale5LessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_SCALE5 <=", value, "zyScale5");
			return this;
		}

		public Criteria andZyScale5In(List<BigDecimal> values) {
			addCriterion("ZY_SCALE5 in", values, "zyScale5");
			return this;
		}

		public Criteria andZyScale5NotIn(List<BigDecimal> values) {
			addCriterion("ZY_SCALE5 not in", values, "zyScale5");
			return this;
		}

		public Criteria andZyScale5Between(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_SCALE5 between", value1, value2, "zyScale5");
			return this;
		}

		public Criteria andZyScale5NotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ZY_SCALE5 not between", value1, value2, "zyScale5");
			return this;
		}

		public Criteria andCNcScaleIsNull() {
			addCriterion("C_NC_SCALE is null");
			return this;
		}

		public Criteria andCNcScaleIsNotNull() {
			addCriterion("C_NC_SCALE is not null");
			return this;
		}

		public Criteria andCNcScaleEqualTo(BigDecimal value) {
			addCriterion("C_NC_SCALE =", value, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleNotEqualTo(BigDecimal value) {
			addCriterion("C_NC_SCALE <>", value, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleGreaterThan(BigDecimal value) {
			addCriterion("C_NC_SCALE >", value, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("C_NC_SCALE >=", value, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleLessThan(BigDecimal value) {
			addCriterion("C_NC_SCALE <", value, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleLessThanOrEqualTo(BigDecimal value) {
			addCriterion("C_NC_SCALE <=", value, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleIn(List<BigDecimal> values) {
			addCriterion("C_NC_SCALE in", values, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleNotIn(List<BigDecimal> values) {
			addCriterion("C_NC_SCALE not in", values, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_NC_SCALE between", value1, value2, "cNcScale");
			return this;
		}

		public Criteria andCNcScaleNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("C_NC_SCALE not between", value1, value2, "cNcScale");
			return this;
		}

		public Criteria andCCsScaleIsNull() {
			addCriterion("C_CS_SCALE is null");
			return this;
		}

		public Criteria andCCsScaleIsNotNull() {
			addCriterion("C_CS_SCALE is not null");
			return this;
		}

		public Criteria andCCsScaleEqualTo(BigDecimal value) {
			addCriterion("C_CS_SCALE =", value, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleNotEqualTo(BigDecimal value) {
			addCriterion("C_CS_SCALE <>", value, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleGreaterThan(BigDecimal value) {
			addCriterion("C_CS_SCALE >", value, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("C_CS_SCALE >=", value, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleLessThan(BigDecimal value) {
			addCriterion("C_CS_SCALE <", value, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleLessThanOrEqualTo(BigDecimal value) {
			addCriterion("C_CS_SCALE <=", value, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleIn(List<BigDecimal> values) {
			addCriterion("C_CS_SCALE in", values, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleNotIn(List<BigDecimal> values) {
			addCriterion("C_CS_SCALE not in", values, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("C_CS_SCALE between", value1, value2, "cCsScale");
			return this;
		}

		public Criteria andCCsScaleNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("C_CS_SCALE not between", value1, value2, "cCsScale");
			return this;
		}

		public Criteria andWcNcScaleIsNull() {
			addCriterion("WC_NC_SCALE is null");
			return this;
		}

		public Criteria andWcNcScaleIsNotNull() {
			addCriterion("WC_NC_SCALE is not null");
			return this;
		}

		public Criteria andWcNcScaleEqualTo(BigDecimal value) {
			addCriterion("WC_NC_SCALE =", value, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleNotEqualTo(BigDecimal value) {
			addCriterion("WC_NC_SCALE <>", value, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleGreaterThan(BigDecimal value) {
			addCriterion("WC_NC_SCALE >", value, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("WC_NC_SCALE >=", value, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleLessThan(BigDecimal value) {
			addCriterion("WC_NC_SCALE <", value, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleLessThanOrEqualTo(BigDecimal value) {
			addCriterion("WC_NC_SCALE <=", value, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleIn(List<BigDecimal> values) {
			addCriterion("WC_NC_SCALE in", values, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleNotIn(List<BigDecimal> values) {
			addCriterion("WC_NC_SCALE not in", values, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("WC_NC_SCALE between", value1, value2, "wcNcScale");
			return this;
		}

		public Criteria andWcNcScaleNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("WC_NC_SCALE not between", value1, value2, "wcNcScale");
			return this;
		}

		public Criteria andWcCsScaleIsNull() {
			addCriterion("WC_CS_SCALE is null");
			return this;
		}

		public Criteria andWcCsScaleIsNotNull() {
			addCriterion("WC_CS_SCALE is not null");
			return this;
		}

		public Criteria andWcCsScaleEqualTo(BigDecimal value) {
			addCriterion("WC_CS_SCALE =", value, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleNotEqualTo(BigDecimal value) {
			addCriterion("WC_CS_SCALE <>", value, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleGreaterThan(BigDecimal value) {
			addCriterion("WC_CS_SCALE >", value, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("WC_CS_SCALE >=", value, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleLessThan(BigDecimal value) {
			addCriterion("WC_CS_SCALE <", value, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleLessThanOrEqualTo(BigDecimal value) {
			addCriterion("WC_CS_SCALE <=", value, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleIn(List<BigDecimal> values) {
			addCriterion("WC_CS_SCALE in", values, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleNotIn(List<BigDecimal> values) {
			addCriterion("WC_CS_SCALE not in", values, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("WC_CS_SCALE between", value1, value2, "wcCsScale");
			return this;
		}

		public Criteria andWcCsScaleNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("WC_CS_SCALE not between", value1, value2, "wcCsScale");
			return this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return this;
		}

		public Criteria andFlagIsNull() {
			addCriterion("FLAG is null");
			return this;
		}

		public Criteria andFlagIsNotNull() {
			addCriterion("FLAG is not null");
			return this;
		}

		public Criteria andFlagEqualTo(String value) {
			addCriterion("FLAG =", value, "flag");
			return this;
		}

		public Criteria andFlagNotEqualTo(String value) {
			addCriterion("FLAG <>", value, "flag");
			return this;
		}

		public Criteria andFlagGreaterThan(String value) {
			addCriterion("FLAG >", value, "flag");
			return this;
		}

		public Criteria andFlagGreaterThanOrEqualTo(String value) {
			addCriterion("FLAG >=", value, "flag");
			return this;
		}

		public Criteria andFlagLessThan(String value) {
			addCriterion("FLAG <", value, "flag");
			return this;
		}

		public Criteria andFlagLessThanOrEqualTo(String value) {
			addCriterion("FLAG <=", value, "flag");
			return this;
		}

		public Criteria andFlagLike(String value) {
			addCriterion("FLAG like", value, "flag");
			return this;
		}

		public Criteria andFlagNotLike(String value) {
			addCriterion("FLAG not like", value, "flag");
			return this;
		}

		public Criteria andFlagIn(List<String> values) {
			addCriterion("FLAG in", values, "flag");
			return this;
		}

		public Criteria andFlagNotIn(List<String> values) {
			addCriterion("FLAG not in", values, "flag");
			return this;
		}

		public Criteria andFlagBetween(String value1, String value2) {
			addCriterion("FLAG between", value1, value2, "flag");
			return this;
		}

		public Criteria andFlagNotBetween(String value1, String value2) {
			addCriterion("FLAG not between", value1, value2, "flag");
			return this;
		}

		public Criteria andZyTopLineIsNull() {
			addCriterion("ZY_TOP_LINE is null");
			return this;
		}

		public Criteria andZyTopLineIsNotNull() {
			addCriterion("ZY_TOP_LINE is not null");
			return this;
		}

		public Criteria andZyTopLineEqualTo(BigDecimal value) {
			addCriterion("ZY_TOP_LINE =", value, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineNotEqualTo(BigDecimal value) {
			addCriterion("ZY_TOP_LINE <>", value, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineGreaterThan(BigDecimal value) {
			addCriterion("ZY_TOP_LINE >", value, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_TOP_LINE >=", value, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineLessThan(BigDecimal value) {
			addCriterion("ZY_TOP_LINE <", value, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineLessThanOrEqualTo(BigDecimal value) {
			addCriterion("ZY_TOP_LINE <=", value, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineIn(List<BigDecimal> values) {
			addCriterion("ZY_TOP_LINE in", values, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineNotIn(List<BigDecimal> values) {
			addCriterion("ZY_TOP_LINE not in", values, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("ZY_TOP_LINE between", value1, value2, "zyTopLine");
			return this;
		}

		public Criteria andZyTopLineNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("ZY_TOP_LINE not between", value1, value2, "zyTopLine");
			return this;
		}

		public Criteria andWbhScaleIsNull() {
			addCriterion("WBH_SCALE is null");
			return this;
		}

		public Criteria andWbhScaleIsNotNull() {
			addCriterion("WBH_SCALE is not null");
			return this;
		}

		public Criteria andWbhScaleEqualTo(BigDecimal value) {
			addCriterion("WBH_SCALE =", value, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleNotEqualTo(BigDecimal value) {
			addCriterion("WBH_SCALE <>", value, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleGreaterThan(BigDecimal value) {
			addCriterion("WBH_SCALE >", value, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("WBH_SCALE >=", value, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleLessThan(BigDecimal value) {
			addCriterion("WBH_SCALE <", value, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleLessThanOrEqualTo(BigDecimal value) {
			addCriterion("WBH_SCALE <=", value, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleIn(List<BigDecimal> values) {
			addCriterion("WBH_SCALE in", values, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleNotIn(List<BigDecimal> values) {
			addCriterion("WBH_SCALE not in", values, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("WBH_SCALE between", value1, value2, "wbhScale");
			return this;
		}

		public Criteria andWbhScaleNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("WBH_SCALE not between", value1, value2, "wbhScale");
			return this;
		}

		public Criteria andSanwuScaleIsNull() {
			addCriterion("SANWU_SCALE is null");
			return this;
		}

		public Criteria andSanwuScaleIsNotNull() {
			addCriterion("SANWU_SCALE is not null");
			return this;
		}

		public Criteria andSanwuScaleEqualTo(BigDecimal value) {
			addCriterion("SANWU_SCALE =", value, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleNotEqualTo(BigDecimal value) {
			addCriterion("SANWU_SCALE <>", value, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleGreaterThan(BigDecimal value) {
			addCriterion("SANWU_SCALE >", value, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("SANWU_SCALE >=", value, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleLessThan(BigDecimal value) {
			addCriterion("SANWU_SCALE <", value, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleLessThanOrEqualTo(BigDecimal value) {
			addCriterion("SANWU_SCALE <=", value, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleIn(List<BigDecimal> values) {
			addCriterion("SANWU_SCALE in", values, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleNotIn(List<BigDecimal> values) {
			addCriterion("SANWU_SCALE not in", values, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SANWU_SCALE between", value1, value2, "sanwuScale");
			return this;
		}

		public Criteria andSanwuScaleNotBetween(BigDecimal value1,
				BigDecimal value2) {
			addCriterion("SANWU_SCALE not between", value1, value2,
					"sanwuScale");
			return this;
		}
	}
}