package com.mingda.model;

import java.math.BigDecimal;
import java.util.Date;

public class JzMedicalafter {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.BIZ_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Integer bizId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String hospitalName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String assistType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.ORGANIZATION_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String organizationId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.MEMBER_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String memberId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.MEMBER_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String memberType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.FAMILY_NO
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String familyNo;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.FAMILY_ADDRESS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String familyAddress;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.SEX
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String sex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.ID_CARD
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String idCard;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.BEGIN_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String diagnoseName;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.END_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Date assistTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PAY_TOTAL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal payTotal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PAY_MEDICARE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal payMedicare;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PAY_OUTMEDICARE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal payOutmedicare;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PAY_ASSIST
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal payAssist;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.BIZ_STATUS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String bizStatus;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.OPER_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Date operTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.IMPLSTS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String implsts;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.MEDICARE_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String medicareType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String hospitalType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PERSONSTATE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String personstate;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE_M
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String assistTypeM;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_IN
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal paySumassistIn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_OUT
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal paySumassistOut;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.SUM_MEDICARESCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal sumMedicarescope;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.PAY_CIASSIST
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal payCiassist;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.SUM_ASSITSCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal sumAssitscope;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.SUM_PRE_ASSITSCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal sumPreAssitscope;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPEX
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String assistTypex;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Integer hospitalId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_TYPE_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Integer diagnoseTypeId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.ICD_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Integer icdId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.SPECBIZ
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String specbiz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.CALCMSG
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String calcmsg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.OTHER_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String otherType;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.INSURANCE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private BigDecimal insurance;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LEVEL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String hospitalLevel;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.SSN
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String ssn;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.APPLY_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private Date applyTime;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LOCAL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String hospitalLocal;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.BUSINESS_YEAR
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String businessYear;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTER.MEDICARE_FLAG
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    private String medicareFlag;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.BIZ_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.BIZ_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Integer getBizId() {
        return bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.BIZ_ID
     *
     * @param bizId the value for MEDICAL.JZ_MEDICALAFTER.BIZ_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setBizId(Integer bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_NAME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.HOSPITAL_NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getHospitalName() {
        return hospitalName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_NAME
     *
     * @param hospitalName the value for MEDICAL.JZ_MEDICALAFTER.HOSPITAL_NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setHospitalName(String hospitalName) {
        this.hospitalName = hospitalName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getAssistType() {
        return assistType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE
     *
     * @param assistType the value for MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setAssistType(String assistType) {
        this.assistType = assistType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.ORGANIZATION_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.ORGANIZATION_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.ORGANIZATION_ID
     *
     * @param organizationId the value for MEDICAL.JZ_MEDICALAFTER.ORGANIZATION_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.MEMBER_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.MEMBER_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.MEMBER_ID
     *
     * @param memberId the value for MEDICAL.JZ_MEDICALAFTER.MEMBER_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.MEMBER_TYPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.MEMBER_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getMemberType() {
        return memberType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.MEMBER_TYPE
     *
     * @param memberType the value for MEDICAL.JZ_MEDICALAFTER.MEMBER_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.FAMILY_NO
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.FAMILY_NO
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getFamilyNo() {
        return familyNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.FAMILY_NO
     *
     * @param familyNo the value for MEDICAL.JZ_MEDICALAFTER.FAMILY_NO
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setFamilyNo(String familyNo) {
        this.familyNo = familyNo;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.FAMILY_ADDRESS
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.FAMILY_ADDRESS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getFamilyAddress() {
        return familyAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.FAMILY_ADDRESS
     *
     * @param familyAddress the value for MEDICAL.JZ_MEDICALAFTER.FAMILY_ADDRESS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setFamilyAddress(String familyAddress) {
        this.familyAddress = familyAddress;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.NAME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.NAME
     *
     * @param name the value for MEDICAL.JZ_MEDICALAFTER.NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.SEX
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.SEX
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.SEX
     *
     * @param sex the value for MEDICAL.JZ_MEDICALAFTER.SEX
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.ID_CARD
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.ID_CARD
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.ID_CARD
     *
     * @param idCard the value for MEDICAL.JZ_MEDICALAFTER.ID_CARD
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.BEGIN_TIME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.BEGIN_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.BEGIN_TIME
     *
     * @param beginTime the value for MEDICAL.JZ_MEDICALAFTER.BEGIN_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_NAME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getDiagnoseName() {
        return diagnoseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_NAME
     *
     * @param diagnoseName the value for MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_NAME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setDiagnoseName(String diagnoseName) {
        this.diagnoseName = diagnoseName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.END_TIME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.END_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.END_TIME
     *
     * @param endTime the value for MEDICAL.JZ_MEDICALAFTER.END_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TIME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.ASSIST_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Date getAssistTime() {
        return assistTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TIME
     *
     * @param assistTime the value for MEDICAL.JZ_MEDICALAFTER.ASSIST_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setAssistTime(Date assistTime) {
        this.assistTime = assistTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_TOTAL
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PAY_TOTAL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getPayTotal() {
        return payTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_TOTAL
     *
     * @param payTotal the value for MEDICAL.JZ_MEDICALAFTER.PAY_TOTAL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPayTotal(BigDecimal payTotal) {
        this.payTotal = payTotal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_MEDICARE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PAY_MEDICARE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getPayMedicare() {
        return payMedicare;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_MEDICARE
     *
     * @param payMedicare the value for MEDICAL.JZ_MEDICALAFTER.PAY_MEDICARE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPayMedicare(BigDecimal payMedicare) {
        this.payMedicare = payMedicare;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_OUTMEDICARE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PAY_OUTMEDICARE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getPayOutmedicare() {
        return payOutmedicare;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_OUTMEDICARE
     *
     * @param payOutmedicare the value for MEDICAL.JZ_MEDICALAFTER.PAY_OUTMEDICARE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPayOutmedicare(BigDecimal payOutmedicare) {
        this.payOutmedicare = payOutmedicare;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_ASSIST
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PAY_ASSIST
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getPayAssist() {
        return payAssist;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_ASSIST
     *
     * @param payAssist the value for MEDICAL.JZ_MEDICALAFTER.PAY_ASSIST
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPayAssist(BigDecimal payAssist) {
        this.payAssist = payAssist;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.BIZ_STATUS
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.BIZ_STATUS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getBizStatus() {
        return bizStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.BIZ_STATUS
     *
     * @param bizStatus the value for MEDICAL.JZ_MEDICALAFTER.BIZ_STATUS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setBizStatus(String bizStatus) {
        this.bizStatus = bizStatus;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.OPER_TIME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.OPER_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.OPER_TIME
     *
     * @param operTime the value for MEDICAL.JZ_MEDICALAFTER.OPER_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.IMPLSTS
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.IMPLSTS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getImplsts() {
        return implsts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.IMPLSTS
     *
     * @param implsts the value for MEDICAL.JZ_MEDICALAFTER.IMPLSTS
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setImplsts(String implsts) {
        this.implsts = implsts;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.MEDICARE_TYPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.MEDICARE_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getMedicareType() {
        return medicareType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.MEDICARE_TYPE
     *
     * @param medicareType the value for MEDICAL.JZ_MEDICALAFTER.MEDICARE_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setMedicareType(String medicareType) {
        this.medicareType = medicareType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_TYPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.HOSPITAL_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getHospitalType() {
        return hospitalType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_TYPE
     *
     * @param hospitalType the value for MEDICAL.JZ_MEDICALAFTER.HOSPITAL_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setHospitalType(String hospitalType) {
        this.hospitalType = hospitalType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PERSONSTATE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PERSONSTATE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getPersonstate() {
        return personstate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PERSONSTATE
     *
     * @param personstate the value for MEDICAL.JZ_MEDICALAFTER.PERSONSTATE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPersonstate(String personstate) {
        this.personstate = personstate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE_M
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE_M
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getAssistTypeM() {
        return assistTypeM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE_M
     *
     * @param assistTypeM the value for MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPE_M
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setAssistTypeM(String assistTypeM) {
        this.assistTypeM = assistTypeM;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_IN
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_IN
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getPaySumassistIn() {
        return paySumassistIn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_IN
     *
     * @param paySumassistIn the value for MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_IN
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPaySumassistIn(BigDecimal paySumassistIn) {
        this.paySumassistIn = paySumassistIn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_OUT
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_OUT
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getPaySumassistOut() {
        return paySumassistOut;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_OUT
     *
     * @param paySumassistOut the value for MEDICAL.JZ_MEDICALAFTER.PAY_SUMASSIST_OUT
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPaySumassistOut(BigDecimal paySumassistOut) {
        this.paySumassistOut = paySumassistOut;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.SUM_MEDICARESCOPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.SUM_MEDICARESCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getSumMedicarescope() {
        return sumMedicarescope;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.SUM_MEDICARESCOPE
     *
     * @param sumMedicarescope the value for MEDICAL.JZ_MEDICALAFTER.SUM_MEDICARESCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setSumMedicarescope(BigDecimal sumMedicarescope) {
        this.sumMedicarescope = sumMedicarescope;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_CIASSIST
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.PAY_CIASSIST
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getPayCiassist() {
        return payCiassist;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.PAY_CIASSIST
     *
     * @param payCiassist the value for MEDICAL.JZ_MEDICALAFTER.PAY_CIASSIST
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setPayCiassist(BigDecimal payCiassist) {
        this.payCiassist = payCiassist;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.SUM_ASSITSCOPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.SUM_ASSITSCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getSumAssitscope() {
        return sumAssitscope;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.SUM_ASSITSCOPE
     *
     * @param sumAssitscope the value for MEDICAL.JZ_MEDICALAFTER.SUM_ASSITSCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setSumAssitscope(BigDecimal sumAssitscope) {
        this.sumAssitscope = sumAssitscope;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.SUM_PRE_ASSITSCOPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.SUM_PRE_ASSITSCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getSumPreAssitscope() {
        return sumPreAssitscope;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.SUM_PRE_ASSITSCOPE
     *
     * @param sumPreAssitscope the value for MEDICAL.JZ_MEDICALAFTER.SUM_PRE_ASSITSCOPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setSumPreAssitscope(BigDecimal sumPreAssitscope) {
        this.sumPreAssitscope = sumPreAssitscope;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPEX
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPEX
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getAssistTypex() {
        return assistTypex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPEX
     *
     * @param assistTypex the value for MEDICAL.JZ_MEDICALAFTER.ASSIST_TYPEX
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setAssistTypex(String assistTypex) {
        this.assistTypex = assistTypex;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.HOSPITAL_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Integer getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_ID
     *
     * @param hospitalId the value for MEDICAL.JZ_MEDICALAFTER.HOSPITAL_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setHospitalId(Integer hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_TYPE_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_TYPE_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Integer getDiagnoseTypeId() {
        return diagnoseTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_TYPE_ID
     *
     * @param diagnoseTypeId the value for MEDICAL.JZ_MEDICALAFTER.DIAGNOSE_TYPE_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setDiagnoseTypeId(Integer diagnoseTypeId) {
        this.diagnoseTypeId = diagnoseTypeId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.ICD_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.ICD_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Integer getIcdId() {
        return icdId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.ICD_ID
     *
     * @param icdId the value for MEDICAL.JZ_MEDICALAFTER.ICD_ID
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setIcdId(Integer icdId) {
        this.icdId = icdId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.SPECBIZ
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.SPECBIZ
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getSpecbiz() {
        return specbiz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.SPECBIZ
     *
     * @param specbiz the value for MEDICAL.JZ_MEDICALAFTER.SPECBIZ
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setSpecbiz(String specbiz) {
        this.specbiz = specbiz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.CALCMSG
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.CALCMSG
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getCalcmsg() {
        return calcmsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.CALCMSG
     *
     * @param calcmsg the value for MEDICAL.JZ_MEDICALAFTER.CALCMSG
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setCalcmsg(String calcmsg) {
        this.calcmsg = calcmsg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.OTHER_TYPE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.OTHER_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getOtherType() {
        return otherType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.OTHER_TYPE
     *
     * @param otherType the value for MEDICAL.JZ_MEDICALAFTER.OTHER_TYPE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setOtherType(String otherType) {
        this.otherType = otherType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.INSURANCE
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.INSURANCE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public BigDecimal getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.INSURANCE
     *
     * @param insurance the value for MEDICAL.JZ_MEDICALAFTER.INSURANCE
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setInsurance(BigDecimal insurance) {
        this.insurance = insurance;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LEVEL
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LEVEL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getHospitalLevel() {
        return hospitalLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LEVEL
     *
     * @param hospitalLevel the value for MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LEVEL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setHospitalLevel(String hospitalLevel) {
        this.hospitalLevel = hospitalLevel;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.SSN
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.SSN
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.SSN
     *
     * @param ssn the value for MEDICAL.JZ_MEDICALAFTER.SSN
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.APPLY_TIME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.APPLY_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.APPLY_TIME
     *
     * @param applyTime the value for MEDICAL.JZ_MEDICALAFTER.APPLY_TIME
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LOCAL
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LOCAL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getHospitalLocal() {
        return hospitalLocal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LOCAL
     *
     * @param hospitalLocal the value for MEDICAL.JZ_MEDICALAFTER.HOSPITAL_LOCAL
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setHospitalLocal(String hospitalLocal) {
        this.hospitalLocal = hospitalLocal;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.BUSINESS_YEAR
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.BUSINESS_YEAR
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getBusinessYear() {
        return businessYear;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.BUSINESS_YEAR
     *
     * @param businessYear the value for MEDICAL.JZ_MEDICALAFTER.BUSINESS_YEAR
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setBusinessYear(String businessYear) {
        this.businessYear = businessYear;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTER.MEDICARE_FLAG
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTER.MEDICARE_FLAG
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public String getMedicareFlag() {
        return medicareFlag;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTER.MEDICARE_FLAG
     *
     * @param medicareFlag the value for MEDICAL.JZ_MEDICALAFTER.MEDICARE_FLAG
     *
     * @ibatorgenerated Wed Oct 21 20:12:00 CST 2015
     */
    public void setMedicareFlag(String medicareFlag) {
        this.medicareFlag = medicareFlag;
    }
}