package com.mingda.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class JzMedicalafterExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public JzMedicalafterExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    protected JzMedicalafterExample(JzMedicalafterExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.JZ_MEDICALAFTER
     *
     * @ibatorgenerated Sun Nov 30 18:21:51 CST 2014
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andBizIdIsNull() {
            addCriterion("BIZ_ID is null");
            return this;
        }

        public Criteria andBizIdIsNotNull() {
            addCriterion("BIZ_ID is not null");
            return this;
        }

        public Criteria andBizIdEqualTo(Integer value) {
            addCriterion("BIZ_ID =", value, "bizId");
            return this;
        }

        public Criteria andBizIdNotEqualTo(Integer value) {
            addCriterion("BIZ_ID <>", value, "bizId");
            return this;
        }

        public Criteria andBizIdGreaterThan(Integer value) {
            addCriterion("BIZ_ID >", value, "bizId");
            return this;
        }

        public Criteria andBizIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("BIZ_ID >=", value, "bizId");
            return this;
        }

        public Criteria andBizIdLessThan(Integer value) {
            addCriterion("BIZ_ID <", value, "bizId");
            return this;
        }

        public Criteria andBizIdLessThanOrEqualTo(Integer value) {
            addCriterion("BIZ_ID <=", value, "bizId");
            return this;
        }

        public Criteria andBizIdIn(List<Integer> values) {
            addCriterion("BIZ_ID in", values, "bizId");
            return this;
        }

        public Criteria andBizIdNotIn(List<Integer> values) {
            addCriterion("BIZ_ID not in", values, "bizId");
            return this;
        }

        public Criteria andBizIdBetween(Integer value1, Integer value2) {
            addCriterion("BIZ_ID between", value1, value2, "bizId");
            return this;
        }

        public Criteria andBizIdNotBetween(Integer value1, Integer value2) {
            addCriterion("BIZ_ID not between", value1, value2, "bizId");
            return this;
        }

        public Criteria andHospitalNameIsNull() {
            addCriterion("HOSPITAL_NAME is null");
            return this;
        }

        public Criteria andHospitalNameIsNotNull() {
            addCriterion("HOSPITAL_NAME is not null");
            return this;
        }

        public Criteria andHospitalNameEqualTo(String value) {
            addCriterion("HOSPITAL_NAME =", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameNotEqualTo(String value) {
            addCriterion("HOSPITAL_NAME <>", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameGreaterThan(String value) {
            addCriterion("HOSPITAL_NAME >", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameGreaterThanOrEqualTo(String value) {
            addCriterion("HOSPITAL_NAME >=", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameLessThan(String value) {
            addCriterion("HOSPITAL_NAME <", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameLessThanOrEqualTo(String value) {
            addCriterion("HOSPITAL_NAME <=", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameLike(String value) {
            addCriterion("HOSPITAL_NAME like", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameNotLike(String value) {
            addCriterion("HOSPITAL_NAME not like", value, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameIn(List<String> values) {
            addCriterion("HOSPITAL_NAME in", values, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameNotIn(List<String> values) {
            addCriterion("HOSPITAL_NAME not in", values, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameBetween(String value1, String value2) {
            addCriterion("HOSPITAL_NAME between", value1, value2, "hospitalName");
            return this;
        }

        public Criteria andHospitalNameNotBetween(String value1, String value2) {
            addCriterion("HOSPITAL_NAME not between", value1, value2, "hospitalName");
            return this;
        }

        public Criteria andAssistTypeIsNull() {
            addCriterion("ASSIST_TYPE is null");
            return this;
        }

        public Criteria andAssistTypeIsNotNull() {
            addCriterion("ASSIST_TYPE is not null");
            return this;
        }

        public Criteria andAssistTypeEqualTo(String value) {
            addCriterion("ASSIST_TYPE =", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotEqualTo(String value) {
            addCriterion("ASSIST_TYPE <>", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeGreaterThan(String value) {
            addCriterion("ASSIST_TYPE >", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPE >=", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeLessThan(String value) {
            addCriterion("ASSIST_TYPE <", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeLessThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPE <=", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeLike(String value) {
            addCriterion("ASSIST_TYPE like", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotLike(String value) {
            addCriterion("ASSIST_TYPE not like", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeIn(List<String> values) {
            addCriterion("ASSIST_TYPE in", values, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotIn(List<String> values) {
            addCriterion("ASSIST_TYPE not in", values, "assistType");
            return this;
        }

        public Criteria andAssistTypeBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPE between", value1, value2, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPE not between", value1, value2, "assistType");
            return this;
        }

        public Criteria andOrganizationIdIsNull() {
            addCriterion("ORGANIZATION_ID is null");
            return this;
        }

        public Criteria andOrganizationIdIsNotNull() {
            addCriterion("ORGANIZATION_ID is not null");
            return this;
        }

        public Criteria andOrganizationIdEqualTo(String value) {
            addCriterion("ORGANIZATION_ID =", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdNotEqualTo(String value) {
            addCriterion("ORGANIZATION_ID <>", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdGreaterThan(String value) {
            addCriterion("ORGANIZATION_ID >", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORGANIZATION_ID >=", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdLessThan(String value) {
            addCriterion("ORGANIZATION_ID <", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdLessThanOrEqualTo(String value) {
            addCriterion("ORGANIZATION_ID <=", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdLike(String value) {
            addCriterion("ORGANIZATION_ID like", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdNotLike(String value) {
            addCriterion("ORGANIZATION_ID not like", value, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdIn(List<String> values) {
            addCriterion("ORGANIZATION_ID in", values, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdNotIn(List<String> values) {
            addCriterion("ORGANIZATION_ID not in", values, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdBetween(String value1, String value2) {
            addCriterion("ORGANIZATION_ID between", value1, value2, "organizationId");
            return this;
        }

        public Criteria andOrganizationIdNotBetween(String value1, String value2) {
            addCriterion("ORGANIZATION_ID not between", value1, value2, "organizationId");
            return this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("MEMBER_ID is null");
            return this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("MEMBER_ID is not null");
            return this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("MEMBER_ID =", value, "memberId");
            return this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("MEMBER_ID <>", value, "memberId");
            return this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("MEMBER_ID >", value, "memberId");
            return this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID >=", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("MEMBER_ID <", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID <=", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("MEMBER_ID like", value, "memberId");
            return this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("MEMBER_ID not like", value, "memberId");
            return this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("MEMBER_ID in", values, "memberId");
            return this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("MEMBER_ID not in", values, "memberId");
            return this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("MEMBER_ID between", value1, value2, "memberId");
            return this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("MEMBER_ID not between", value1, value2, "memberId");
            return this;
        }

        public Criteria andMemberTypeIsNull() {
            addCriterion("MEMBER_TYPE is null");
            return this;
        }

        public Criteria andMemberTypeIsNotNull() {
            addCriterion("MEMBER_TYPE is not null");
            return this;
        }

        public Criteria andMemberTypeEqualTo(String value) {
            addCriterion("MEMBER_TYPE =", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotEqualTo(String value) {
            addCriterion("MEMBER_TYPE <>", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeGreaterThan(String value) {
            addCriterion("MEMBER_TYPE >", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_TYPE >=", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLessThan(String value) {
            addCriterion("MEMBER_TYPE <", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_TYPE <=", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLike(String value) {
            addCriterion("MEMBER_TYPE like", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotLike(String value) {
            addCriterion("MEMBER_TYPE not like", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeIn(List<String> values) {
            addCriterion("MEMBER_TYPE in", values, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotIn(List<String> values) {
            addCriterion("MEMBER_TYPE not in", values, "memberType");
            return this;
        }

        public Criteria andMemberTypeBetween(String value1, String value2) {
            addCriterion("MEMBER_TYPE between", value1, value2, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotBetween(String value1, String value2) {
            addCriterion("MEMBER_TYPE not between", value1, value2, "memberType");
            return this;
        }

        public Criteria andFamilyNoIsNull() {
            addCriterion("FAMILY_NO is null");
            return this;
        }

        public Criteria andFamilyNoIsNotNull() {
            addCriterion("FAMILY_NO is not null");
            return this;
        }

        public Criteria andFamilyNoEqualTo(String value) {
            addCriterion("FAMILY_NO =", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoNotEqualTo(String value) {
            addCriterion("FAMILY_NO <>", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoGreaterThan(String value) {
            addCriterion("FAMILY_NO >", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoGreaterThanOrEqualTo(String value) {
            addCriterion("FAMILY_NO >=", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoLessThan(String value) {
            addCriterion("FAMILY_NO <", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoLessThanOrEqualTo(String value) {
            addCriterion("FAMILY_NO <=", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoLike(String value) {
            addCriterion("FAMILY_NO like", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoNotLike(String value) {
            addCriterion("FAMILY_NO not like", value, "familyNo");
            return this;
        }

        public Criteria andFamilyNoIn(List<String> values) {
            addCriterion("FAMILY_NO in", values, "familyNo");
            return this;
        }

        public Criteria andFamilyNoNotIn(List<String> values) {
            addCriterion("FAMILY_NO not in", values, "familyNo");
            return this;
        }

        public Criteria andFamilyNoBetween(String value1, String value2) {
            addCriterion("FAMILY_NO between", value1, value2, "familyNo");
            return this;
        }

        public Criteria andFamilyNoNotBetween(String value1, String value2) {
            addCriterion("FAMILY_NO not between", value1, value2, "familyNo");
            return this;
        }

        public Criteria andFamilyAddressIsNull() {
            addCriterion("FAMILY_ADDRESS is null");
            return this;
        }

        public Criteria andFamilyAddressIsNotNull() {
            addCriterion("FAMILY_ADDRESS is not null");
            return this;
        }

        public Criteria andFamilyAddressEqualTo(String value) {
            addCriterion("FAMILY_ADDRESS =", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressNotEqualTo(String value) {
            addCriterion("FAMILY_ADDRESS <>", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressGreaterThan(String value) {
            addCriterion("FAMILY_ADDRESS >", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressGreaterThanOrEqualTo(String value) {
            addCriterion("FAMILY_ADDRESS >=", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressLessThan(String value) {
            addCriterion("FAMILY_ADDRESS <", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressLessThanOrEqualTo(String value) {
            addCriterion("FAMILY_ADDRESS <=", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressLike(String value) {
            addCriterion("FAMILY_ADDRESS like", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressNotLike(String value) {
            addCriterion("FAMILY_ADDRESS not like", value, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressIn(List<String> values) {
            addCriterion("FAMILY_ADDRESS in", values, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressNotIn(List<String> values) {
            addCriterion("FAMILY_ADDRESS not in", values, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressBetween(String value1, String value2) {
            addCriterion("FAMILY_ADDRESS between", value1, value2, "familyAddress");
            return this;
        }

        public Criteria andFamilyAddressNotBetween(String value1, String value2) {
            addCriterion("FAMILY_ADDRESS not between", value1, value2, "familyAddress");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andSexIsNull() {
            addCriterion("SEX is null");
            return this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("SEX is not null");
            return this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("SEX =", value, "sex");
            return this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("SEX <>", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("SEX >", value, "sex");
            return this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("SEX >=", value, "sex");
            return this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("SEX <", value, "sex");
            return this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("SEX <=", value, "sex");
            return this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("SEX like", value, "sex");
            return this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("SEX not like", value, "sex");
            return this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("SEX in", values, "sex");
            return this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("SEX not in", values, "sex");
            return this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("SEX between", value1, value2, "sex");
            return this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("SEX not between", value1, value2, "sex");
            return this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("ID_CARD is null");
            return this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("ID_CARD is not null");
            return this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("ID_CARD =", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("ID_CARD <>", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("ID_CARD >", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD >=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("ID_CARD <", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD <=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("ID_CARD like", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("ID_CARD not like", value, "idCard");
            return this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("ID_CARD in", values, "idCard");
            return this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("ID_CARD not in", values, "idCard");
            return this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("ID_CARD between", value1, value2, "idCard");
            return this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("ID_CARD not between", value1, value2, "idCard");
            return this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("BEGIN_TIME is null");
            return this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("BEGIN_TIME is not null");
            return this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("BEGIN_TIME =", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("BEGIN_TIME <>", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("BEGIN_TIME >", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("BEGIN_TIME >=", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("BEGIN_TIME <", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("BEGIN_TIME <=", value, "beginTime");
            return this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("BEGIN_TIME in", values, "beginTime");
            return this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("BEGIN_TIME not in", values, "beginTime");
            return this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("BEGIN_TIME between", value1, value2, "beginTime");
            return this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("BEGIN_TIME not between", value1, value2, "beginTime");
            return this;
        }

        public Criteria andDiagnoseNameIsNull() {
            addCriterion("DIAGNOSE_NAME is null");
            return this;
        }

        public Criteria andDiagnoseNameIsNotNull() {
            addCriterion("DIAGNOSE_NAME is not null");
            return this;
        }

        public Criteria andDiagnoseNameEqualTo(String value) {
            addCriterion("DIAGNOSE_NAME =", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameNotEqualTo(String value) {
            addCriterion("DIAGNOSE_NAME <>", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameGreaterThan(String value) {
            addCriterion("DIAGNOSE_NAME >", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameGreaterThanOrEqualTo(String value) {
            addCriterion("DIAGNOSE_NAME >=", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameLessThan(String value) {
            addCriterion("DIAGNOSE_NAME <", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameLessThanOrEqualTo(String value) {
            addCriterion("DIAGNOSE_NAME <=", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameLike(String value) {
            addCriterion("DIAGNOSE_NAME like", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameNotLike(String value) {
            addCriterion("DIAGNOSE_NAME not like", value, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameIn(List<String> values) {
            addCriterion("DIAGNOSE_NAME in", values, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameNotIn(List<String> values) {
            addCriterion("DIAGNOSE_NAME not in", values, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameBetween(String value1, String value2) {
            addCriterion("DIAGNOSE_NAME between", value1, value2, "diagnoseName");
            return this;
        }

        public Criteria andDiagnoseNameNotBetween(String value1, String value2) {
            addCriterion("DIAGNOSE_NAME not between", value1, value2, "diagnoseName");
            return this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("END_TIME is null");
            return this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("END_TIME is not null");
            return this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("END_TIME =", value, "endTime");
            return this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("END_TIME <>", value, "endTime");
            return this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("END_TIME >", value, "endTime");
            return this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("END_TIME >=", value, "endTime");
            return this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("END_TIME <", value, "endTime");
            return this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("END_TIME <=", value, "endTime");
            return this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("END_TIME in", values, "endTime");
            return this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("END_TIME not in", values, "endTime");
            return this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("END_TIME between", value1, value2, "endTime");
            return this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("END_TIME not between", value1, value2, "endTime");
            return this;
        }

        public Criteria andAssistTimeIsNull() {
            addCriterion("ASSIST_TIME is null");
            return this;
        }

        public Criteria andAssistTimeIsNotNull() {
            addCriterion("ASSIST_TIME is not null");
            return this;
        }

        public Criteria andAssistTimeEqualTo(Date value) {
            addCriterion("ASSIST_TIME =", value, "assistTime");
            return this;
        }

        public Criteria andAssistTimeNotEqualTo(Date value) {
            addCriterion("ASSIST_TIME <>", value, "assistTime");
            return this;
        }

        public Criteria andAssistTimeGreaterThan(Date value) {
            addCriterion("ASSIST_TIME >", value, "assistTime");
            return this;
        }

        public Criteria andAssistTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ASSIST_TIME >=", value, "assistTime");
            return this;
        }

        public Criteria andAssistTimeLessThan(Date value) {
            addCriterion("ASSIST_TIME <", value, "assistTime");
            return this;
        }

        public Criteria andAssistTimeLessThanOrEqualTo(Date value) {
            addCriterion("ASSIST_TIME <=", value, "assistTime");
            return this;
        }

        public Criteria andAssistTimeIn(List<Date> values) {
            addCriterion("ASSIST_TIME in", values, "assistTime");
            return this;
        }

        public Criteria andAssistTimeNotIn(List<Date> values) {
            addCriterion("ASSIST_TIME not in", values, "assistTime");
            return this;
        }

        public Criteria andAssistTimeBetween(Date value1, Date value2) {
            addCriterion("ASSIST_TIME between", value1, value2, "assistTime");
            return this;
        }

        public Criteria andAssistTimeNotBetween(Date value1, Date value2) {
            addCriterion("ASSIST_TIME not between", value1, value2, "assistTime");
            return this;
        }

        public Criteria andPayTotalIsNull() {
            addCriterion("PAY_TOTAL is null");
            return this;
        }

        public Criteria andPayTotalIsNotNull() {
            addCriterion("PAY_TOTAL is not null");
            return this;
        }

        public Criteria andPayTotalEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL =", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalNotEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL <>", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalGreaterThan(BigDecimal value) {
            addCriterion("PAY_TOTAL >", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL >=", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalLessThan(BigDecimal value) {
            addCriterion("PAY_TOTAL <", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL <=", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalIn(List<BigDecimal> values) {
            addCriterion("PAY_TOTAL in", values, "payTotal");
            return this;
        }

        public Criteria andPayTotalNotIn(List<BigDecimal> values) {
            addCriterion("PAY_TOTAL not in", values, "payTotal");
            return this;
        }

        public Criteria andPayTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_TOTAL between", value1, value2, "payTotal");
            return this;
        }

        public Criteria andPayTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_TOTAL not between", value1, value2, "payTotal");
            return this;
        }

        public Criteria andPayMedicareIsNull() {
            addCriterion("PAY_MEDICARE is null");
            return this;
        }

        public Criteria andPayMedicareIsNotNull() {
            addCriterion("PAY_MEDICARE is not null");
            return this;
        }

        public Criteria andPayMedicareEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE =", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareNotEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE <>", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareGreaterThan(BigDecimal value) {
            addCriterion("PAY_MEDICARE >", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE >=", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareLessThan(BigDecimal value) {
            addCriterion("PAY_MEDICARE <", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE <=", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareIn(List<BigDecimal> values) {
            addCriterion("PAY_MEDICARE in", values, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareNotIn(List<BigDecimal> values) {
            addCriterion("PAY_MEDICARE not in", values, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MEDICARE between", value1, value2, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MEDICARE not between", value1, value2, "payMedicare");
            return this;
        }

        public Criteria andPayOutmedicareIsNull() {
            addCriterion("PAY_OUTMEDICARE is null");
            return this;
        }

        public Criteria andPayOutmedicareIsNotNull() {
            addCriterion("PAY_OUTMEDICARE is not null");
            return this;
        }

        public Criteria andPayOutmedicareEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE =", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareNotEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE <>", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareGreaterThan(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE >", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE >=", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareLessThan(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE <", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE <=", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareIn(List<BigDecimal> values) {
            addCriterion("PAY_OUTMEDICARE in", values, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareNotIn(List<BigDecimal> values) {
            addCriterion("PAY_OUTMEDICARE not in", values, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_OUTMEDICARE between", value1, value2, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_OUTMEDICARE not between", value1, value2, "payOutmedicare");
            return this;
        }

        public Criteria andPayAssistIsNull() {
            addCriterion("PAY_ASSIST is null");
            return this;
        }

        public Criteria andPayAssistIsNotNull() {
            addCriterion("PAY_ASSIST is not null");
            return this;
        }

        public Criteria andPayAssistEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST =", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistNotEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST <>", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistGreaterThan(BigDecimal value) {
            addCriterion("PAY_ASSIST >", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST >=", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistLessThan(BigDecimal value) {
            addCriterion("PAY_ASSIST <", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST <=", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistIn(List<BigDecimal> values) {
            addCriterion("PAY_ASSIST in", values, "payAssist");
            return this;
        }

        public Criteria andPayAssistNotIn(List<BigDecimal> values) {
            addCriterion("PAY_ASSIST not in", values, "payAssist");
            return this;
        }

        public Criteria andPayAssistBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_ASSIST between", value1, value2, "payAssist");
            return this;
        }

        public Criteria andPayAssistNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_ASSIST not between", value1, value2, "payAssist");
            return this;
        }

        public Criteria andBizStatusIsNull() {
            addCriterion("BIZ_STATUS is null");
            return this;
        }

        public Criteria andBizStatusIsNotNull() {
            addCriterion("BIZ_STATUS is not null");
            return this;
        }

        public Criteria andBizStatusEqualTo(String value) {
            addCriterion("BIZ_STATUS =", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusNotEqualTo(String value) {
            addCriterion("BIZ_STATUS <>", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusGreaterThan(String value) {
            addCriterion("BIZ_STATUS >", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusGreaterThanOrEqualTo(String value) {
            addCriterion("BIZ_STATUS >=", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusLessThan(String value) {
            addCriterion("BIZ_STATUS <", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusLessThanOrEqualTo(String value) {
            addCriterion("BIZ_STATUS <=", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusLike(String value) {
            addCriterion("BIZ_STATUS like", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusNotLike(String value) {
            addCriterion("BIZ_STATUS not like", value, "bizStatus");
            return this;
        }

        public Criteria andBizStatusIn(List<String> values) {
            addCriterion("BIZ_STATUS in", values, "bizStatus");
            return this;
        }

        public Criteria andBizStatusNotIn(List<String> values) {
            addCriterion("BIZ_STATUS not in", values, "bizStatus");
            return this;
        }

        public Criteria andBizStatusBetween(String value1, String value2) {
            addCriterion("BIZ_STATUS between", value1, value2, "bizStatus");
            return this;
        }

        public Criteria andBizStatusNotBetween(String value1, String value2) {
            addCriterion("BIZ_STATUS not between", value1, value2, "bizStatus");
            return this;
        }

        public Criteria andOperTimeIsNull() {
            addCriterion("OPER_TIME is null");
            return this;
        }

        public Criteria andOperTimeIsNotNull() {
            addCriterion("OPER_TIME is not null");
            return this;
        }

        public Criteria andOperTimeEqualTo(Date value) {
            addCriterion("OPER_TIME =", value, "operTime");
            return this;
        }

        public Criteria andOperTimeNotEqualTo(Date value) {
            addCriterion("OPER_TIME <>", value, "operTime");
            return this;
        }

        public Criteria andOperTimeGreaterThan(Date value) {
            addCriterion("OPER_TIME >", value, "operTime");
            return this;
        }

        public Criteria andOperTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("OPER_TIME >=", value, "operTime");
            return this;
        }

        public Criteria andOperTimeLessThan(Date value) {
            addCriterion("OPER_TIME <", value, "operTime");
            return this;
        }

        public Criteria andOperTimeLessThanOrEqualTo(Date value) {
            addCriterion("OPER_TIME <=", value, "operTime");
            return this;
        }

        public Criteria andOperTimeIn(List<Date> values) {
            addCriterion("OPER_TIME in", values, "operTime");
            return this;
        }

        public Criteria andOperTimeNotIn(List<Date> values) {
            addCriterion("OPER_TIME not in", values, "operTime");
            return this;
        }

        public Criteria andOperTimeBetween(Date value1, Date value2) {
            addCriterion("OPER_TIME between", value1, value2, "operTime");
            return this;
        }

        public Criteria andOperTimeNotBetween(Date value1, Date value2) {
            addCriterion("OPER_TIME not between", value1, value2, "operTime");
            return this;
        }

        public Criteria andImplstsIsNull() {
            addCriterion("IMPLSTS is null");
            return this;
        }

        public Criteria andImplstsIsNotNull() {
            addCriterion("IMPLSTS is not null");
            return this;
        }

        public Criteria andImplstsEqualTo(String value) {
            addCriterion("IMPLSTS =", value, "implsts");
            return this;
        }

        public Criteria andImplstsNotEqualTo(String value) {
            addCriterion("IMPLSTS <>", value, "implsts");
            return this;
        }

        public Criteria andImplstsGreaterThan(String value) {
            addCriterion("IMPLSTS >", value, "implsts");
            return this;
        }

        public Criteria andImplstsGreaterThanOrEqualTo(String value) {
            addCriterion("IMPLSTS >=", value, "implsts");
            return this;
        }

        public Criteria andImplstsLessThan(String value) {
            addCriterion("IMPLSTS <", value, "implsts");
            return this;
        }

        public Criteria andImplstsLessThanOrEqualTo(String value) {
            addCriterion("IMPLSTS <=", value, "implsts");
            return this;
        }

        public Criteria andImplstsLike(String value) {
            addCriterion("IMPLSTS like", value, "implsts");
            return this;
        }

        public Criteria andImplstsNotLike(String value) {
            addCriterion("IMPLSTS not like", value, "implsts");
            return this;
        }

        public Criteria andImplstsIn(List<String> values) {
            addCriterion("IMPLSTS in", values, "implsts");
            return this;
        }

        public Criteria andImplstsNotIn(List<String> values) {
            addCriterion("IMPLSTS not in", values, "implsts");
            return this;
        }

        public Criteria andImplstsBetween(String value1, String value2) {
            addCriterion("IMPLSTS between", value1, value2, "implsts");
            return this;
        }

        public Criteria andImplstsNotBetween(String value1, String value2) {
            addCriterion("IMPLSTS not between", value1, value2, "implsts");
            return this;
        }

        public Criteria andMedicareTypeIsNull() {
            addCriterion("MEDICARE_TYPE is null");
            return this;
        }

        public Criteria andMedicareTypeIsNotNull() {
            addCriterion("MEDICARE_TYPE is not null");
            return this;
        }

        public Criteria andMedicareTypeEqualTo(String value) {
            addCriterion("MEDICARE_TYPE =", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeNotEqualTo(String value) {
            addCriterion("MEDICARE_TYPE <>", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeGreaterThan(String value) {
            addCriterion("MEDICARE_TYPE >", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MEDICARE_TYPE >=", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeLessThan(String value) {
            addCriterion("MEDICARE_TYPE <", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeLessThanOrEqualTo(String value) {
            addCriterion("MEDICARE_TYPE <=", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeLike(String value) {
            addCriterion("MEDICARE_TYPE like", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeNotLike(String value) {
            addCriterion("MEDICARE_TYPE not like", value, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeIn(List<String> values) {
            addCriterion("MEDICARE_TYPE in", values, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeNotIn(List<String> values) {
            addCriterion("MEDICARE_TYPE not in", values, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeBetween(String value1, String value2) {
            addCriterion("MEDICARE_TYPE between", value1, value2, "medicareType");
            return this;
        }

        public Criteria andMedicareTypeNotBetween(String value1, String value2) {
            addCriterion("MEDICARE_TYPE not between", value1, value2, "medicareType");
            return this;
        }

        public Criteria andHospitalTypeIsNull() {
            addCriterion("HOSPITAL_TYPE is null");
            return this;
        }

        public Criteria andHospitalTypeIsNotNull() {
            addCriterion("HOSPITAL_TYPE is not null");
            return this;
        }

        public Criteria andHospitalTypeEqualTo(String value) {
            addCriterion("HOSPITAL_TYPE =", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeNotEqualTo(String value) {
            addCriterion("HOSPITAL_TYPE <>", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeGreaterThan(String value) {
            addCriterion("HOSPITAL_TYPE >", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeGreaterThanOrEqualTo(String value) {
            addCriterion("HOSPITAL_TYPE >=", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeLessThan(String value) {
            addCriterion("HOSPITAL_TYPE <", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeLessThanOrEqualTo(String value) {
            addCriterion("HOSPITAL_TYPE <=", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeLike(String value) {
            addCriterion("HOSPITAL_TYPE like", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeNotLike(String value) {
            addCriterion("HOSPITAL_TYPE not like", value, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeIn(List<String> values) {
            addCriterion("HOSPITAL_TYPE in", values, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeNotIn(List<String> values) {
            addCriterion("HOSPITAL_TYPE not in", values, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeBetween(String value1, String value2) {
            addCriterion("HOSPITAL_TYPE between", value1, value2, "hospitalType");
            return this;
        }

        public Criteria andHospitalTypeNotBetween(String value1, String value2) {
            addCriterion("HOSPITAL_TYPE not between", value1, value2, "hospitalType");
            return this;
        }

        public Criteria andPersonstateIsNull() {
            addCriterion("PERSONSTATE is null");
            return this;
        }

        public Criteria andPersonstateIsNotNull() {
            addCriterion("PERSONSTATE is not null");
            return this;
        }

        public Criteria andPersonstateEqualTo(String value) {
            addCriterion("PERSONSTATE =", value, "personstate");
            return this;
        }

        public Criteria andPersonstateNotEqualTo(String value) {
            addCriterion("PERSONSTATE <>", value, "personstate");
            return this;
        }

        public Criteria andPersonstateGreaterThan(String value) {
            addCriterion("PERSONSTATE >", value, "personstate");
            return this;
        }

        public Criteria andPersonstateGreaterThanOrEqualTo(String value) {
            addCriterion("PERSONSTATE >=", value, "personstate");
            return this;
        }

        public Criteria andPersonstateLessThan(String value) {
            addCriterion("PERSONSTATE <", value, "personstate");
            return this;
        }

        public Criteria andPersonstateLessThanOrEqualTo(String value) {
            addCriterion("PERSONSTATE <=", value, "personstate");
            return this;
        }

        public Criteria andPersonstateLike(String value) {
            addCriterion("PERSONSTATE like", value, "personstate");
            return this;
        }

        public Criteria andPersonstateNotLike(String value) {
            addCriterion("PERSONSTATE not like", value, "personstate");
            return this;
        }

        public Criteria andPersonstateIn(List<String> values) {
            addCriterion("PERSONSTATE in", values, "personstate");
            return this;
        }

        public Criteria andPersonstateNotIn(List<String> values) {
            addCriterion("PERSONSTATE not in", values, "personstate");
            return this;
        }

        public Criteria andPersonstateBetween(String value1, String value2) {
            addCriterion("PERSONSTATE between", value1, value2, "personstate");
            return this;
        }

        public Criteria andPersonstateNotBetween(String value1, String value2) {
            addCriterion("PERSONSTATE not between", value1, value2, "personstate");
            return this;
        }

        public Criteria andAssistTypeMIsNull() {
            addCriterion("ASSIST_TYPE_M is null");
            return this;
        }

        public Criteria andAssistTypeMIsNotNull() {
            addCriterion("ASSIST_TYPE_M is not null");
            return this;
        }

        public Criteria andAssistTypeMEqualTo(String value) {
            addCriterion("ASSIST_TYPE_M =", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMNotEqualTo(String value) {
            addCriterion("ASSIST_TYPE_M <>", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMGreaterThan(String value) {
            addCriterion("ASSIST_TYPE_M >", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPE_M >=", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMLessThan(String value) {
            addCriterion("ASSIST_TYPE_M <", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMLessThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPE_M <=", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMLike(String value) {
            addCriterion("ASSIST_TYPE_M like", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMNotLike(String value) {
            addCriterion("ASSIST_TYPE_M not like", value, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMIn(List<String> values) {
            addCriterion("ASSIST_TYPE_M in", values, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMNotIn(List<String> values) {
            addCriterion("ASSIST_TYPE_M not in", values, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPE_M between", value1, value2, "assistTypeM");
            return this;
        }

        public Criteria andAssistTypeMNotBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPE_M not between", value1, value2, "assistTypeM");
            return this;
        }

        public Criteria andPaySumassistInIsNull() {
            addCriterion("PAY_SUMASSIST_IN is null");
            return this;
        }

        public Criteria andPaySumassistInIsNotNull() {
            addCriterion("PAY_SUMASSIST_IN is not null");
            return this;
        }

        public Criteria andPaySumassistInEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN =", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInNotEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN <>", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInGreaterThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN >", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN >=", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInLessThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN <", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN <=", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_IN in", values, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInNotIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_IN not in", values, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_IN between", value1, value2, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_IN not between", value1, value2, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistOutIsNull() {
            addCriterion("PAY_SUMASSIST_OUT is null");
            return this;
        }

        public Criteria andPaySumassistOutIsNotNull() {
            addCriterion("PAY_SUMASSIST_OUT is not null");
            return this;
        }

        public Criteria andPaySumassistOutEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT =", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutNotEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT <>", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutGreaterThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT >", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT >=", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutLessThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT <", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT <=", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_OUT in", values, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutNotIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_OUT not in", values, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_OUT between", value1, value2, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_OUT not between", value1, value2, "paySumassistOut");
            return this;
        }

        public Criteria andSumMedicarescopeIsNull() {
            addCriterion("SUM_MEDICARESCOPE is null");
            return this;
        }

        public Criteria andSumMedicarescopeIsNotNull() {
            addCriterion("SUM_MEDICARESCOPE is not null");
            return this;
        }

        public Criteria andSumMedicarescopeEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE =", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeNotEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE <>", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeGreaterThan(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE >", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE >=", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeLessThan(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE <", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE <=", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeIn(List<BigDecimal> values) {
            addCriterion("SUM_MEDICARESCOPE in", values, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeNotIn(List<BigDecimal> values) {
            addCriterion("SUM_MEDICARESCOPE not in", values, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_MEDICARESCOPE between", value1, value2, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_MEDICARESCOPE not between", value1, value2, "sumMedicarescope");
            return this;
        }

        public Criteria andPayCiassistIsNull() {
            addCriterion("PAY_CIASSIST is null");
            return this;
        }

        public Criteria andPayCiassistIsNotNull() {
            addCriterion("PAY_CIASSIST is not null");
            return this;
        }

        public Criteria andPayCiassistEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST =", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistNotEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST <>", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistGreaterThan(BigDecimal value) {
            addCriterion("PAY_CIASSIST >", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST >=", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistLessThan(BigDecimal value) {
            addCriterion("PAY_CIASSIST <", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST <=", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistIn(List<BigDecimal> values) {
            addCriterion("PAY_CIASSIST in", values, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistNotIn(List<BigDecimal> values) {
            addCriterion("PAY_CIASSIST not in", values, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_CIASSIST between", value1, value2, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_CIASSIST not between", value1, value2, "payCiassist");
            return this;
        }

        public Criteria andSumAssitscopeIsNull() {
            addCriterion("SUM_ASSITSCOPE is null");
            return this;
        }

        public Criteria andSumAssitscopeIsNotNull() {
            addCriterion("SUM_ASSITSCOPE is not null");
            return this;
        }

        public Criteria andSumAssitscopeEqualTo(BigDecimal value) {
            addCriterion("SUM_ASSITSCOPE =", value, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeNotEqualTo(BigDecimal value) {
            addCriterion("SUM_ASSITSCOPE <>", value, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeGreaterThan(BigDecimal value) {
            addCriterion("SUM_ASSITSCOPE >", value, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_ASSITSCOPE >=", value, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeLessThan(BigDecimal value) {
            addCriterion("SUM_ASSITSCOPE <", value, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_ASSITSCOPE <=", value, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeIn(List<BigDecimal> values) {
            addCriterion("SUM_ASSITSCOPE in", values, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeNotIn(List<BigDecimal> values) {
            addCriterion("SUM_ASSITSCOPE not in", values, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_ASSITSCOPE between", value1, value2, "sumAssitscope");
            return this;
        }

        public Criteria andSumAssitscopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_ASSITSCOPE not between", value1, value2, "sumAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeIsNull() {
            addCriterion("SUM_PRE_ASSITSCOPE is null");
            return this;
        }

        public Criteria andSumPreAssitscopeIsNotNull() {
            addCriterion("SUM_PRE_ASSITSCOPE is not null");
            return this;
        }

        public Criteria andSumPreAssitscopeEqualTo(BigDecimal value) {
            addCriterion("SUM_PRE_ASSITSCOPE =", value, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeNotEqualTo(BigDecimal value) {
            addCriterion("SUM_PRE_ASSITSCOPE <>", value, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeGreaterThan(BigDecimal value) {
            addCriterion("SUM_PRE_ASSITSCOPE >", value, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_PRE_ASSITSCOPE >=", value, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeLessThan(BigDecimal value) {
            addCriterion("SUM_PRE_ASSITSCOPE <", value, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_PRE_ASSITSCOPE <=", value, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeIn(List<BigDecimal> values) {
            addCriterion("SUM_PRE_ASSITSCOPE in", values, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeNotIn(List<BigDecimal> values) {
            addCriterion("SUM_PRE_ASSITSCOPE not in", values, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_PRE_ASSITSCOPE between", value1, value2, "sumPreAssitscope");
            return this;
        }

        public Criteria andSumPreAssitscopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_PRE_ASSITSCOPE not between", value1, value2, "sumPreAssitscope");
            return this;
        }

        public Criteria andAssistTypexIsNull() {
            addCriterion("ASSIST_TYPEX is null");
            return this;
        }

        public Criteria andAssistTypexIsNotNull() {
            addCriterion("ASSIST_TYPEX is not null");
            return this;
        }

        public Criteria andAssistTypexEqualTo(String value) {
            addCriterion("ASSIST_TYPEX =", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexNotEqualTo(String value) {
            addCriterion("ASSIST_TYPEX <>", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexGreaterThan(String value) {
            addCriterion("ASSIST_TYPEX >", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPEX >=", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexLessThan(String value) {
            addCriterion("ASSIST_TYPEX <", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexLessThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPEX <=", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexLike(String value) {
            addCriterion("ASSIST_TYPEX like", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexNotLike(String value) {
            addCriterion("ASSIST_TYPEX not like", value, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexIn(List<String> values) {
            addCriterion("ASSIST_TYPEX in", values, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexNotIn(List<String> values) {
            addCriterion("ASSIST_TYPEX not in", values, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPEX between", value1, value2, "assistTypex");
            return this;
        }

        public Criteria andAssistTypexNotBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPEX not between", value1, value2, "assistTypex");
            return this;
        }

        public Criteria andHospitalIdIsNull() {
            addCriterion("HOSPITAL_ID is null");
            return this;
        }

        public Criteria andHospitalIdIsNotNull() {
            addCriterion("HOSPITAL_ID is not null");
            return this;
        }

        public Criteria andHospitalIdEqualTo(Integer value) {
            addCriterion("HOSPITAL_ID =", value, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdNotEqualTo(Integer value) {
            addCriterion("HOSPITAL_ID <>", value, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdGreaterThan(Integer value) {
            addCriterion("HOSPITAL_ID >", value, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("HOSPITAL_ID >=", value, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdLessThan(Integer value) {
            addCriterion("HOSPITAL_ID <", value, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdLessThanOrEqualTo(Integer value) {
            addCriterion("HOSPITAL_ID <=", value, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdIn(List<Integer> values) {
            addCriterion("HOSPITAL_ID in", values, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdNotIn(List<Integer> values) {
            addCriterion("HOSPITAL_ID not in", values, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdBetween(Integer value1, Integer value2) {
            addCriterion("HOSPITAL_ID between", value1, value2, "hospitalId");
            return this;
        }

        public Criteria andHospitalIdNotBetween(Integer value1, Integer value2) {
            addCriterion("HOSPITAL_ID not between", value1, value2, "hospitalId");
            return this;
        }

        public Criteria andDiagnoseTypeIdIsNull() {
            addCriterion("DIAGNOSE_TYPE_ID is null");
            return this;
        }

        public Criteria andDiagnoseTypeIdIsNotNull() {
            addCriterion("DIAGNOSE_TYPE_ID is not null");
            return this;
        }

        public Criteria andDiagnoseTypeIdEqualTo(Integer value) {
            addCriterion("DIAGNOSE_TYPE_ID =", value, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdNotEqualTo(Integer value) {
            addCriterion("DIAGNOSE_TYPE_ID <>", value, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdGreaterThan(Integer value) {
            addCriterion("DIAGNOSE_TYPE_ID >", value, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("DIAGNOSE_TYPE_ID >=", value, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdLessThan(Integer value) {
            addCriterion("DIAGNOSE_TYPE_ID <", value, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("DIAGNOSE_TYPE_ID <=", value, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdIn(List<Integer> values) {
            addCriterion("DIAGNOSE_TYPE_ID in", values, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdNotIn(List<Integer> values) {
            addCriterion("DIAGNOSE_TYPE_ID not in", values, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("DIAGNOSE_TYPE_ID between", value1, value2, "diagnoseTypeId");
            return this;
        }

        public Criteria andDiagnoseTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("DIAGNOSE_TYPE_ID not between", value1, value2, "diagnoseTypeId");
            return this;
        }

        public Criteria andIcdIdIsNull() {
            addCriterion("ICD_ID is null");
            return this;
        }

        public Criteria andIcdIdIsNotNull() {
            addCriterion("ICD_ID is not null");
            return this;
        }

        public Criteria andIcdIdEqualTo(Integer value) {
            addCriterion("ICD_ID =", value, "icdId");
            return this;
        }

        public Criteria andIcdIdNotEqualTo(Integer value) {
            addCriterion("ICD_ID <>", value, "icdId");
            return this;
        }

        public Criteria andIcdIdGreaterThan(Integer value) {
            addCriterion("ICD_ID >", value, "icdId");
            return this;
        }

        public Criteria andIcdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ICD_ID >=", value, "icdId");
            return this;
        }

        public Criteria andIcdIdLessThan(Integer value) {
            addCriterion("ICD_ID <", value, "icdId");
            return this;
        }

        public Criteria andIcdIdLessThanOrEqualTo(Integer value) {
            addCriterion("ICD_ID <=", value, "icdId");
            return this;
        }

        public Criteria andIcdIdIn(List<Integer> values) {
            addCriterion("ICD_ID in", values, "icdId");
            return this;
        }

        public Criteria andIcdIdNotIn(List<Integer> values) {
            addCriterion("ICD_ID not in", values, "icdId");
            return this;
        }

        public Criteria andIcdIdBetween(Integer value1, Integer value2) {
            addCriterion("ICD_ID between", value1, value2, "icdId");
            return this;
        }

        public Criteria andIcdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ICD_ID not between", value1, value2, "icdId");
            return this;
        }

        public Criteria andSpecbizIsNull() {
            addCriterion("SPECBIZ is null");
            return this;
        }

        public Criteria andSpecbizIsNotNull() {
            addCriterion("SPECBIZ is not null");
            return this;
        }

        public Criteria andSpecbizEqualTo(String value) {
            addCriterion("SPECBIZ =", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizNotEqualTo(String value) {
            addCriterion("SPECBIZ <>", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizGreaterThan(String value) {
            addCriterion("SPECBIZ >", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizGreaterThanOrEqualTo(String value) {
            addCriterion("SPECBIZ >=", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizLessThan(String value) {
            addCriterion("SPECBIZ <", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizLessThanOrEqualTo(String value) {
            addCriterion("SPECBIZ <=", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizLike(String value) {
            addCriterion("SPECBIZ like", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizNotLike(String value) {
            addCriterion("SPECBIZ not like", value, "specbiz");
            return this;
        }

        public Criteria andSpecbizIn(List<String> values) {
            addCriterion("SPECBIZ in", values, "specbiz");
            return this;
        }

        public Criteria andSpecbizNotIn(List<String> values) {
            addCriterion("SPECBIZ not in", values, "specbiz");
            return this;
        }

        public Criteria andSpecbizBetween(String value1, String value2) {
            addCriterion("SPECBIZ between", value1, value2, "specbiz");
            return this;
        }

        public Criteria andSpecbizNotBetween(String value1, String value2) {
            addCriterion("SPECBIZ not between", value1, value2, "specbiz");
            return this;
        }

        public Criteria andCalcmsgIsNull() {
            addCriterion("CALCMSG is null");
            return this;
        }

        public Criteria andCalcmsgIsNotNull() {
            addCriterion("CALCMSG is not null");
            return this;
        }

        public Criteria andCalcmsgEqualTo(String value) {
            addCriterion("CALCMSG =", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgNotEqualTo(String value) {
            addCriterion("CALCMSG <>", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgGreaterThan(String value) {
            addCriterion("CALCMSG >", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgGreaterThanOrEqualTo(String value) {
            addCriterion("CALCMSG >=", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgLessThan(String value) {
            addCriterion("CALCMSG <", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgLessThanOrEqualTo(String value) {
            addCriterion("CALCMSG <=", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgLike(String value) {
            addCriterion("CALCMSG like", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgNotLike(String value) {
            addCriterion("CALCMSG not like", value, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgIn(List<String> values) {
            addCriterion("CALCMSG in", values, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgNotIn(List<String> values) {
            addCriterion("CALCMSG not in", values, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgBetween(String value1, String value2) {
            addCriterion("CALCMSG between", value1, value2, "calcmsg");
            return this;
        }

        public Criteria andCalcmsgNotBetween(String value1, String value2) {
            addCriterion("CALCMSG not between", value1, value2, "calcmsg");
            return this;
        }

        public Criteria andOtherTypeIsNull() {
            addCriterion("OTHER_TYPE is null");
            return this;
        }

        public Criteria andOtherTypeIsNotNull() {
            addCriterion("OTHER_TYPE is not null");
            return this;
        }

        public Criteria andOtherTypeEqualTo(String value) {
            addCriterion("OTHER_TYPE =", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeNotEqualTo(String value) {
            addCriterion("OTHER_TYPE <>", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeGreaterThan(String value) {
            addCriterion("OTHER_TYPE >", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeGreaterThanOrEqualTo(String value) {
            addCriterion("OTHER_TYPE >=", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeLessThan(String value) {
            addCriterion("OTHER_TYPE <", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeLessThanOrEqualTo(String value) {
            addCriterion("OTHER_TYPE <=", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeLike(String value) {
            addCriterion("OTHER_TYPE like", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeNotLike(String value) {
            addCriterion("OTHER_TYPE not like", value, "otherType");
            return this;
        }

        public Criteria andOtherTypeIn(List<String> values) {
            addCriterion("OTHER_TYPE in", values, "otherType");
            return this;
        }

        public Criteria andOtherTypeNotIn(List<String> values) {
            addCriterion("OTHER_TYPE not in", values, "otherType");
            return this;
        }

        public Criteria andOtherTypeBetween(String value1, String value2) {
            addCriterion("OTHER_TYPE between", value1, value2, "otherType");
            return this;
        }

        public Criteria andOtherTypeNotBetween(String value1, String value2) {
            addCriterion("OTHER_TYPE not between", value1, value2, "otherType");
            return this;
        }

        public Criteria andInsuranceIsNull() {
            addCriterion("INSURANCE is null");
            return this;
        }

        public Criteria andInsuranceIsNotNull() {
            addCriterion("INSURANCE is not null");
            return this;
        }

        public Criteria andInsuranceEqualTo(BigDecimal value) {
            addCriterion("INSURANCE =", value, "insurance");
            return this;
        }

        public Criteria andInsuranceNotEqualTo(BigDecimal value) {
            addCriterion("INSURANCE <>", value, "insurance");
            return this;
        }

        public Criteria andInsuranceGreaterThan(BigDecimal value) {
            addCriterion("INSURANCE >", value, "insurance");
            return this;
        }

        public Criteria andInsuranceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INSURANCE >=", value, "insurance");
            return this;
        }

        public Criteria andInsuranceLessThan(BigDecimal value) {
            addCriterion("INSURANCE <", value, "insurance");
            return this;
        }

        public Criteria andInsuranceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INSURANCE <=", value, "insurance");
            return this;
        }

        public Criteria andInsuranceIn(List<BigDecimal> values) {
            addCriterion("INSURANCE in", values, "insurance");
            return this;
        }

        public Criteria andInsuranceNotIn(List<BigDecimal> values) {
            addCriterion("INSURANCE not in", values, "insurance");
            return this;
        }

        public Criteria andInsuranceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INSURANCE between", value1, value2, "insurance");
            return this;
        }

        public Criteria andInsuranceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INSURANCE not between", value1, value2, "insurance");
            return this;
        }

        public Criteria andHospitalLevelIsNull() {
            addCriterion("HOSPITAL_LEVEL is null");
            return this;
        }

        public Criteria andHospitalLevelIsNotNull() {
            addCriterion("HOSPITAL_LEVEL is not null");
            return this;
        }

        public Criteria andHospitalLevelEqualTo(String value) {
            addCriterion("HOSPITAL_LEVEL =", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelNotEqualTo(String value) {
            addCriterion("HOSPITAL_LEVEL <>", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelGreaterThan(String value) {
            addCriterion("HOSPITAL_LEVEL >", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelGreaterThanOrEqualTo(String value) {
            addCriterion("HOSPITAL_LEVEL >=", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelLessThan(String value) {
            addCriterion("HOSPITAL_LEVEL <", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelLessThanOrEqualTo(String value) {
            addCriterion("HOSPITAL_LEVEL <=", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelLike(String value) {
            addCriterion("HOSPITAL_LEVEL like", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelNotLike(String value) {
            addCriterion("HOSPITAL_LEVEL not like", value, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelIn(List<String> values) {
            addCriterion("HOSPITAL_LEVEL in", values, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelNotIn(List<String> values) {
            addCriterion("HOSPITAL_LEVEL not in", values, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelBetween(String value1, String value2) {
            addCriterion("HOSPITAL_LEVEL between", value1, value2, "hospitalLevel");
            return this;
        }

        public Criteria andHospitalLevelNotBetween(String value1, String value2) {
            addCriterion("HOSPITAL_LEVEL not between", value1, value2, "hospitalLevel");
            return this;
        }
    }
}