package com.mingda.model;

import java.math.BigDecimal;

public class JzMedicalafterfile {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTERFILE.FILE_ID
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    private BigDecimal fileId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTERFILE.BIZ_ID
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    private BigDecimal bizId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTERFILE.FILENAME
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    private String filename;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTERFILE.REALPATH
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    private String realpath;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column MEDICAL.JZ_MEDICALAFTERFILE.REALFILENAME
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    private String realfilename;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.FILE_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTERFILE.FILE_ID
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public BigDecimal getFileId() {
        return fileId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.FILE_ID
     *
     * @param fileId the value for MEDICAL.JZ_MEDICALAFTERFILE.FILE_ID
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public void setFileId(BigDecimal fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.BIZ_ID
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTERFILE.BIZ_ID
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public BigDecimal getBizId() {
        return bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.BIZ_ID
     *
     * @param bizId the value for MEDICAL.JZ_MEDICALAFTERFILE.BIZ_ID
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public void setBizId(BigDecimal bizId) {
        this.bizId = bizId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.FILENAME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTERFILE.FILENAME
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.FILENAME
     *
     * @param filename the value for MEDICAL.JZ_MEDICALAFTERFILE.FILENAME
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.REALPATH
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTERFILE.REALPATH
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public String getRealpath() {
        return realpath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.REALPATH
     *
     * @param realpath the value for MEDICAL.JZ_MEDICALAFTERFILE.REALPATH
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public void setRealpath(String realpath) {
        this.realpath = realpath;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.REALFILENAME
     *
     * @return the value of MEDICAL.JZ_MEDICALAFTERFILE.REALFILENAME
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public String getRealfilename() {
        return realfilename;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column MEDICAL.JZ_MEDICALAFTERFILE.REALFILENAME
     *
     * @param realfilename the value for MEDICAL.JZ_MEDICALAFTERFILE.REALFILENAME
     *
     * @ibatorgenerated Thu Nov 22 20:45:30 CST 2012
     */
    public void setRealfilename(String realfilename) {
        this.realfilename = realfilename;
    }
}