package com.mingda.model;

import java.math.BigDecimal;
import java.util.Date;

public class SecondBill {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.BILL_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private BigDecimal billId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.BATCH_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private BigDecimal batchId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.MEMBER_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private String memberId;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.MEMBER_TYPE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private String memberType;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.PAPERID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private String paperid;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.FAMILYNO
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private String familyno;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.SALMONEY
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private BigDecimal salmoney;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.OPER_TIME
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private Date operTime;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column MEDICAL.SECOND_BILL.MEMBERNAME
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	private String membername;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.BILL_ID
	 * @return  the value of MEDICAL.SECOND_BILL.BILL_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public BigDecimal getBillId() {
		return billId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.BILL_ID
	 * @param billId  the value for MEDICAL.SECOND_BILL.BILL_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setBillId(BigDecimal billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.BATCH_ID
	 * @return  the value of MEDICAL.SECOND_BILL.BATCH_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public BigDecimal getBatchId() {
		return batchId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.BATCH_ID
	 * @param batchId  the value for MEDICAL.SECOND_BILL.BATCH_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setBatchId(BigDecimal batchId) {
		this.batchId = batchId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.MEMBER_ID
	 * @return  the value of MEDICAL.SECOND_BILL.MEMBER_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public String getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.MEMBER_ID
	 * @param memberId  the value for MEDICAL.SECOND_BILL.MEMBER_ID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.MEMBER_TYPE
	 * @return  the value of MEDICAL.SECOND_BILL.MEMBER_TYPE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public String getMemberType() {
		return memberType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.MEMBER_TYPE
	 * @param memberType  the value for MEDICAL.SECOND_BILL.MEMBER_TYPE
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.PAPERID
	 * @return  the value of MEDICAL.SECOND_BILL.PAPERID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public String getPaperid() {
		return paperid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.PAPERID
	 * @param paperid  the value for MEDICAL.SECOND_BILL.PAPERID
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setPaperid(String paperid) {
		this.paperid = paperid;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.FAMILYNO
	 * @return  the value of MEDICAL.SECOND_BILL.FAMILYNO
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public String getFamilyno() {
		return familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.FAMILYNO
	 * @param familyno  the value for MEDICAL.SECOND_BILL.FAMILYNO
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setFamilyno(String familyno) {
		this.familyno = familyno;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.SALMONEY
	 * @return  the value of MEDICAL.SECOND_BILL.SALMONEY
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public BigDecimal getSalmoney() {
		return salmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.SALMONEY
	 * @param salmoney  the value for MEDICAL.SECOND_BILL.SALMONEY
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setSalmoney(BigDecimal salmoney) {
		this.salmoney = salmoney;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.OPER_TIME
	 * @return  the value of MEDICAL.SECOND_BILL.OPER_TIME
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public Date getOperTime() {
		return operTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.OPER_TIME
	 * @param operTime  the value for MEDICAL.SECOND_BILL.OPER_TIME
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setOperTime(Date operTime) {
		this.operTime = operTime;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column MEDICAL.SECOND_BILL.MEMBERNAME
	 * @return  the value of MEDICAL.SECOND_BILL.MEMBERNAME
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public String getMembername() {
		return membername;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column MEDICAL.SECOND_BILL.MEMBERNAME
	 * @param membername  the value for MEDICAL.SECOND_BILL.MEMBERNAME
	 * @ibatorgenerated  Tue Sep 20 14:51:08 CST 2011
	 */
	public void setMembername(String membername) {
		this.membername = membername;
	}
}