package com.mingda.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class TempApproveExample {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public TempApproveExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    protected TempApproveExample(TempApproveExample example) {
        this.orderByClause = example.orderByClause;
        this.oredCriteria = example.oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table MEDICAL.TEMP_APPROVE
     *
     * @ibatorgenerated Fri Nov 13 13:40:13 CST 2015
     */
    public static class Criteria {
        protected List<String> criteriaWithoutValue;

        protected List<Map<String, Object>> criteriaWithSingleValue;

        protected List<Map<String, Object>> criteriaWithListValue;

        protected List<Map<String, Object>> criteriaWithBetweenValue;

        protected Criteria() {
            super();
            criteriaWithoutValue = new ArrayList<String>();
            criteriaWithSingleValue = new ArrayList<Map<String, Object>>();
            criteriaWithListValue = new ArrayList<Map<String, Object>>();
            criteriaWithBetweenValue = new ArrayList<Map<String, Object>>();
        }

        public boolean isValid() {
            return criteriaWithoutValue.size() > 0
                || criteriaWithSingleValue.size() > 0
                || criteriaWithListValue.size() > 0
                || criteriaWithBetweenValue.size() > 0;
        }

        public List<String> getCriteriaWithoutValue() {
            return criteriaWithoutValue;
        }

        public List<Map<String, Object>> getCriteriaWithSingleValue() {
            return criteriaWithSingleValue;
        }

        public List<Map<String, Object>> getCriteriaWithListValue() {
            return criteriaWithListValue;
        }

        public List<Map<String, Object>> getCriteriaWithBetweenValue() {
            return criteriaWithBetweenValue;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteriaWithoutValue.add(condition);
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("value", value);
            criteriaWithSingleValue.add(map);
        }

        protected void addCriterion(String condition, List<? extends Object> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", values);
            criteriaWithListValue.add(map);
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            List<Object> list = new ArrayList<Object>();
            list.add(value1);
            list.add(value2);
            Map<String, Object> map = new HashMap<String, Object>();
            map.put("condition", condition);
            map.put("values", list);
            criteriaWithBetweenValue.add(map);
        }

        public Criteria andApproveIdIsNull() {
            addCriterion("APPROVE_ID is null");
            return this;
        }

        public Criteria andApproveIdIsNotNull() {
            addCriterion("APPROVE_ID is not null");
            return this;
        }

        public Criteria andApproveIdEqualTo(Long value) {
            addCriterion("APPROVE_ID =", value, "approveId");
            return this;
        }

        public Criteria andApproveIdNotEqualTo(Long value) {
            addCriterion("APPROVE_ID <>", value, "approveId");
            return this;
        }

        public Criteria andApproveIdGreaterThan(Long value) {
            addCriterion("APPROVE_ID >", value, "approveId");
            return this;
        }

        public Criteria andApproveIdGreaterThanOrEqualTo(Long value) {
            addCriterion("APPROVE_ID >=", value, "approveId");
            return this;
        }

        public Criteria andApproveIdLessThan(Long value) {
            addCriterion("APPROVE_ID <", value, "approveId");
            return this;
        }

        public Criteria andApproveIdLessThanOrEqualTo(Long value) {
            addCriterion("APPROVE_ID <=", value, "approveId");
            return this;
        }

        public Criteria andApproveIdIn(List<Long> values) {
            addCriterion("APPROVE_ID in", values, "approveId");
            return this;
        }

        public Criteria andApproveIdNotIn(List<Long> values) {
            addCriterion("APPROVE_ID not in", values, "approveId");
            return this;
        }

        public Criteria andApproveIdBetween(Long value1, Long value2) {
            addCriterion("APPROVE_ID between", value1, value2, "approveId");
            return this;
        }

        public Criteria andApproveIdNotBetween(Long value1, Long value2) {
            addCriterion("APPROVE_ID not between", value1, value2, "approveId");
            return this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("MEMBER_ID is null");
            return this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("MEMBER_ID is not null");
            return this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("MEMBER_ID =", value, "memberId");
            return this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("MEMBER_ID <>", value, "memberId");
            return this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("MEMBER_ID >", value, "memberId");
            return this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID >=", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("MEMBER_ID <", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_ID <=", value, "memberId");
            return this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("MEMBER_ID like", value, "memberId");
            return this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("MEMBER_ID not like", value, "memberId");
            return this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("MEMBER_ID in", values, "memberId");
            return this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("MEMBER_ID not in", values, "memberId");
            return this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("MEMBER_ID between", value1, value2, "memberId");
            return this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("MEMBER_ID not between", value1, value2, "memberId");
            return this;
        }

        public Criteria andMemberTypeIsNull() {
            addCriterion("MEMBER_TYPE is null");
            return this;
        }

        public Criteria andMemberTypeIsNotNull() {
            addCriterion("MEMBER_TYPE is not null");
            return this;
        }

        public Criteria andMemberTypeEqualTo(String value) {
            addCriterion("MEMBER_TYPE =", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotEqualTo(String value) {
            addCriterion("MEMBER_TYPE <>", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeGreaterThan(String value) {
            addCriterion("MEMBER_TYPE >", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeGreaterThanOrEqualTo(String value) {
            addCriterion("MEMBER_TYPE >=", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLessThan(String value) {
            addCriterion("MEMBER_TYPE <", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLessThanOrEqualTo(String value) {
            addCriterion("MEMBER_TYPE <=", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeLike(String value) {
            addCriterion("MEMBER_TYPE like", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotLike(String value) {
            addCriterion("MEMBER_TYPE not like", value, "memberType");
            return this;
        }

        public Criteria andMemberTypeIn(List<String> values) {
            addCriterion("MEMBER_TYPE in", values, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotIn(List<String> values) {
            addCriterion("MEMBER_TYPE not in", values, "memberType");
            return this;
        }

        public Criteria andMemberTypeBetween(String value1, String value2) {
            addCriterion("MEMBER_TYPE between", value1, value2, "memberType");
            return this;
        }

        public Criteria andMemberTypeNotBetween(String value1, String value2) {
            addCriterion("MEMBER_TYPE not between", value1, value2, "memberType");
            return this;
        }

        public Criteria andYbSickenIsNull() {
            addCriterion("YB_SICKEN is null");
            return this;
        }

        public Criteria andYbSickenIsNotNull() {
            addCriterion("YB_SICKEN is not null");
            return this;
        }

        public Criteria andYbSickenEqualTo(String value) {
            addCriterion("YB_SICKEN =", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenNotEqualTo(String value) {
            addCriterion("YB_SICKEN <>", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenGreaterThan(String value) {
            addCriterion("YB_SICKEN >", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenGreaterThanOrEqualTo(String value) {
            addCriterion("YB_SICKEN >=", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenLessThan(String value) {
            addCriterion("YB_SICKEN <", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenLessThanOrEqualTo(String value) {
            addCriterion("YB_SICKEN <=", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenLike(String value) {
            addCriterion("YB_SICKEN like", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenNotLike(String value) {
            addCriterion("YB_SICKEN not like", value, "ybSicken");
            return this;
        }

        public Criteria andYbSickenIn(List<String> values) {
            addCriterion("YB_SICKEN in", values, "ybSicken");
            return this;
        }

        public Criteria andYbSickenNotIn(List<String> values) {
            addCriterion("YB_SICKEN not in", values, "ybSicken");
            return this;
        }

        public Criteria andYbSickenBetween(String value1, String value2) {
            addCriterion("YB_SICKEN between", value1, value2, "ybSicken");
            return this;
        }

        public Criteria andYbSickenNotBetween(String value1, String value2) {
            addCriterion("YB_SICKEN not between", value1, value2, "ybSicken");
            return this;
        }

        public Criteria andYbSickenvalIsNull() {
            addCriterion("YB_SICKENVAL is null");
            return this;
        }

        public Criteria andYbSickenvalIsNotNull() {
            addCriterion("YB_SICKENVAL is not null");
            return this;
        }

        public Criteria andYbSickenvalEqualTo(String value) {
            addCriterion("YB_SICKENVAL =", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalNotEqualTo(String value) {
            addCriterion("YB_SICKENVAL <>", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalGreaterThan(String value) {
            addCriterion("YB_SICKENVAL >", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalGreaterThanOrEqualTo(String value) {
            addCriterion("YB_SICKENVAL >=", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalLessThan(String value) {
            addCriterion("YB_SICKENVAL <", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalLessThanOrEqualTo(String value) {
            addCriterion("YB_SICKENVAL <=", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalLike(String value) {
            addCriterion("YB_SICKENVAL like", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalNotLike(String value) {
            addCriterion("YB_SICKENVAL not like", value, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalIn(List<String> values) {
            addCriterion("YB_SICKENVAL in", values, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalNotIn(List<String> values) {
            addCriterion("YB_SICKENVAL not in", values, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalBetween(String value1, String value2) {
            addCriterion("YB_SICKENVAL between", value1, value2, "ybSickenval");
            return this;
        }

        public Criteria andYbSickenvalNotBetween(String value1, String value2) {
            addCriterion("YB_SICKENVAL not between", value1, value2, "ybSickenval");
            return this;
        }

        public Criteria andTsSickenIsNull() {
            addCriterion("TS_SICKEN is null");
            return this;
        }

        public Criteria andTsSickenIsNotNull() {
            addCriterion("TS_SICKEN is not null");
            return this;
        }

        public Criteria andTsSickenEqualTo(String value) {
            addCriterion("TS_SICKEN =", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenNotEqualTo(String value) {
            addCriterion("TS_SICKEN <>", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenGreaterThan(String value) {
            addCriterion("TS_SICKEN >", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenGreaterThanOrEqualTo(String value) {
            addCriterion("TS_SICKEN >=", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenLessThan(String value) {
            addCriterion("TS_SICKEN <", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenLessThanOrEqualTo(String value) {
            addCriterion("TS_SICKEN <=", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenLike(String value) {
            addCriterion("TS_SICKEN like", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenNotLike(String value) {
            addCriterion("TS_SICKEN not like", value, "tsSicken");
            return this;
        }

        public Criteria andTsSickenIn(List<String> values) {
            addCriterion("TS_SICKEN in", values, "tsSicken");
            return this;
        }

        public Criteria andTsSickenNotIn(List<String> values) {
            addCriterion("TS_SICKEN not in", values, "tsSicken");
            return this;
        }

        public Criteria andTsSickenBetween(String value1, String value2) {
            addCriterion("TS_SICKEN between", value1, value2, "tsSicken");
            return this;
        }

        public Criteria andTsSickenNotBetween(String value1, String value2) {
            addCriterion("TS_SICKEN not between", value1, value2, "tsSicken");
            return this;
        }

        public Criteria andTsSickenvalIsNull() {
            addCriterion("TS_SICKENVAL is null");
            return this;
        }

        public Criteria andTsSickenvalIsNotNull() {
            addCriterion("TS_SICKENVAL is not null");
            return this;
        }

        public Criteria andTsSickenvalEqualTo(String value) {
            addCriterion("TS_SICKENVAL =", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalNotEqualTo(String value) {
            addCriterion("TS_SICKENVAL <>", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalGreaterThan(String value) {
            addCriterion("TS_SICKENVAL >", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalGreaterThanOrEqualTo(String value) {
            addCriterion("TS_SICKENVAL >=", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalLessThan(String value) {
            addCriterion("TS_SICKENVAL <", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalLessThanOrEqualTo(String value) {
            addCriterion("TS_SICKENVAL <=", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalLike(String value) {
            addCriterion("TS_SICKENVAL like", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalNotLike(String value) {
            addCriterion("TS_SICKENVAL not like", value, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalIn(List<String> values) {
            addCriterion("TS_SICKENVAL in", values, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalNotIn(List<String> values) {
            addCriterion("TS_SICKENVAL not in", values, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalBetween(String value1, String value2) {
            addCriterion("TS_SICKENVAL between", value1, value2, "tsSickenval");
            return this;
        }

        public Criteria andTsSickenvalNotBetween(String value1, String value2) {
            addCriterion("TS_SICKENVAL not between", value1, value2, "tsSickenval");
            return this;
        }

        public Criteria andSaltypeIsNull() {
            addCriterion("SALTYPE is null");
            return this;
        }

        public Criteria andSaltypeIsNotNull() {
            addCriterion("SALTYPE is not null");
            return this;
        }

        public Criteria andSaltypeEqualTo(String value) {
            addCriterion("SALTYPE =", value, "saltype");
            return this;
        }

        public Criteria andSaltypeNotEqualTo(String value) {
            addCriterion("SALTYPE <>", value, "saltype");
            return this;
        }

        public Criteria andSaltypeGreaterThan(String value) {
            addCriterion("SALTYPE >", value, "saltype");
            return this;
        }

        public Criteria andSaltypeGreaterThanOrEqualTo(String value) {
            addCriterion("SALTYPE >=", value, "saltype");
            return this;
        }

        public Criteria andSaltypeLessThan(String value) {
            addCriterion("SALTYPE <", value, "saltype");
            return this;
        }

        public Criteria andSaltypeLessThanOrEqualTo(String value) {
            addCriterion("SALTYPE <=", value, "saltype");
            return this;
        }

        public Criteria andSaltypeLike(String value) {
            addCriterion("SALTYPE like", value, "saltype");
            return this;
        }

        public Criteria andSaltypeNotLike(String value) {
            addCriterion("SALTYPE not like", value, "saltype");
            return this;
        }

        public Criteria andSaltypeIn(List<String> values) {
            addCriterion("SALTYPE in", values, "saltype");
            return this;
        }

        public Criteria andSaltypeNotIn(List<String> values) {
            addCriterion("SALTYPE not in", values, "saltype");
            return this;
        }

        public Criteria andSaltypeBetween(String value1, String value2) {
            addCriterion("SALTYPE between", value1, value2, "saltype");
            return this;
        }

        public Criteria andSaltypeNotBetween(String value1, String value2) {
            addCriterion("SALTYPE not between", value1, value2, "saltype");
            return this;
        }

        public Criteria andInhospitalsickenIsNull() {
            addCriterion("INHOSPITALSICKEN is null");
            return this;
        }

        public Criteria andInhospitalsickenIsNotNull() {
            addCriterion("INHOSPITALSICKEN is not null");
            return this;
        }

        public Criteria andInhospitalsickenEqualTo(String value) {
            addCriterion("INHOSPITALSICKEN =", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenNotEqualTo(String value) {
            addCriterion("INHOSPITALSICKEN <>", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenGreaterThan(String value) {
            addCriterion("INHOSPITALSICKEN >", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenGreaterThanOrEqualTo(String value) {
            addCriterion("INHOSPITALSICKEN >=", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenLessThan(String value) {
            addCriterion("INHOSPITALSICKEN <", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenLessThanOrEqualTo(String value) {
            addCriterion("INHOSPITALSICKEN <=", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenLike(String value) {
            addCriterion("INHOSPITALSICKEN like", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenNotLike(String value) {
            addCriterion("INHOSPITALSICKEN not like", value, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenIn(List<String> values) {
            addCriterion("INHOSPITALSICKEN in", values, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenNotIn(List<String> values) {
            addCriterion("INHOSPITALSICKEN not in", values, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenBetween(String value1, String value2) {
            addCriterion("INHOSPITALSICKEN between", value1, value2, "inhospitalsicken");
            return this;
        }

        public Criteria andInhospitalsickenNotBetween(String value1, String value2) {
            addCriterion("INHOSPITALSICKEN not between", value1, value2, "inhospitalsicken");
            return this;
        }

        public Criteria andPayTotalIsNull() {
            addCriterion("PAY_TOTAL is null");
            return this;
        }

        public Criteria andPayTotalIsNotNull() {
            addCriterion("PAY_TOTAL is not null");
            return this;
        }

        public Criteria andPayTotalEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL =", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalNotEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL <>", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalGreaterThan(BigDecimal value) {
            addCriterion("PAY_TOTAL >", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL >=", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalLessThan(BigDecimal value) {
            addCriterion("PAY_TOTAL <", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_TOTAL <=", value, "payTotal");
            return this;
        }

        public Criteria andPayTotalIn(List<BigDecimal> values) {
            addCriterion("PAY_TOTAL in", values, "payTotal");
            return this;
        }

        public Criteria andPayTotalNotIn(List<BigDecimal> values) {
            addCriterion("PAY_TOTAL not in", values, "payTotal");
            return this;
        }

        public Criteria andPayTotalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_TOTAL between", value1, value2, "payTotal");
            return this;
        }

        public Criteria andPayTotalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_TOTAL not between", value1, value2, "payTotal");
            return this;
        }

        public Criteria andPayOutmedicareIsNull() {
            addCriterion("PAY_OUTMEDICARE is null");
            return this;
        }

        public Criteria andPayOutmedicareIsNotNull() {
            addCriterion("PAY_OUTMEDICARE is not null");
            return this;
        }

        public Criteria andPayOutmedicareEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE =", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareNotEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE <>", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareGreaterThan(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE >", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE >=", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareLessThan(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE <", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_OUTMEDICARE <=", value, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareIn(List<BigDecimal> values) {
            addCriterion("PAY_OUTMEDICARE in", values, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareNotIn(List<BigDecimal> values) {
            addCriterion("PAY_OUTMEDICARE not in", values, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_OUTMEDICARE between", value1, value2, "payOutmedicare");
            return this;
        }

        public Criteria andPayOutmedicareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_OUTMEDICARE not between", value1, value2, "payOutmedicare");
            return this;
        }

        public Criteria andPayMedicareIsNull() {
            addCriterion("PAY_MEDICARE is null");
            return this;
        }

        public Criteria andPayMedicareIsNotNull() {
            addCriterion("PAY_MEDICARE is not null");
            return this;
        }

        public Criteria andPayMedicareEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE =", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareNotEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE <>", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareGreaterThan(BigDecimal value) {
            addCriterion("PAY_MEDICARE >", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE >=", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareLessThan(BigDecimal value) {
            addCriterion("PAY_MEDICARE <", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MEDICARE <=", value, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareIn(List<BigDecimal> values) {
            addCriterion("PAY_MEDICARE in", values, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareNotIn(List<BigDecimal> values) {
            addCriterion("PAY_MEDICARE not in", values, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MEDICARE between", value1, value2, "payMedicare");
            return this;
        }

        public Criteria andPayMedicareNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MEDICARE not between", value1, value2, "payMedicare");
            return this;
        }

        public Criteria andPayYouhuiIsNull() {
            addCriterion("PAY_YOUHUI is null");
            return this;
        }

        public Criteria andPayYouhuiIsNotNull() {
            addCriterion("PAY_YOUHUI is not null");
            return this;
        }

        public Criteria andPayYouhuiEqualTo(BigDecimal value) {
            addCriterion("PAY_YOUHUI =", value, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiNotEqualTo(BigDecimal value) {
            addCriterion("PAY_YOUHUI <>", value, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiGreaterThan(BigDecimal value) {
            addCriterion("PAY_YOUHUI >", value, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_YOUHUI >=", value, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiLessThan(BigDecimal value) {
            addCriterion("PAY_YOUHUI <", value, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_YOUHUI <=", value, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiIn(List<BigDecimal> values) {
            addCriterion("PAY_YOUHUI in", values, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiNotIn(List<BigDecimal> values) {
            addCriterion("PAY_YOUHUI not in", values, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_YOUHUI between", value1, value2, "payYouhui");
            return this;
        }

        public Criteria andPayYouhuiNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_YOUHUI not between", value1, value2, "payYouhui");
            return this;
        }

        public Criteria andPayMinlineIsNull() {
            addCriterion("PAY_MINLINE is null");
            return this;
        }

        public Criteria andPayMinlineIsNotNull() {
            addCriterion("PAY_MINLINE is not null");
            return this;
        }

        public Criteria andPayMinlineEqualTo(BigDecimal value) {
            addCriterion("PAY_MINLINE =", value, "payMinline");
            return this;
        }

        public Criteria andPayMinlineNotEqualTo(BigDecimal value) {
            addCriterion("PAY_MINLINE <>", value, "payMinline");
            return this;
        }

        public Criteria andPayMinlineGreaterThan(BigDecimal value) {
            addCriterion("PAY_MINLINE >", value, "payMinline");
            return this;
        }

        public Criteria andPayMinlineGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MINLINE >=", value, "payMinline");
            return this;
        }

        public Criteria andPayMinlineLessThan(BigDecimal value) {
            addCriterion("PAY_MINLINE <", value, "payMinline");
            return this;
        }

        public Criteria andPayMinlineLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_MINLINE <=", value, "payMinline");
            return this;
        }

        public Criteria andPayMinlineIn(List<BigDecimal> values) {
            addCriterion("PAY_MINLINE in", values, "payMinline");
            return this;
        }

        public Criteria andPayMinlineNotIn(List<BigDecimal> values) {
            addCriterion("PAY_MINLINE not in", values, "payMinline");
            return this;
        }

        public Criteria andPayMinlineBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MINLINE between", value1, value2, "payMinline");
            return this;
        }

        public Criteria andPayMinlineNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_MINLINE not between", value1, value2, "payMinline");
            return this;
        }

        public Criteria andPayAssistscopeIsNull() {
            addCriterion("PAY_ASSISTSCOPE is null");
            return this;
        }

        public Criteria andPayAssistscopeIsNotNull() {
            addCriterion("PAY_ASSISTSCOPE is not null");
            return this;
        }

        public Criteria andPayAssistscopeEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSISTSCOPE =", value, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeNotEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSISTSCOPE <>", value, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeGreaterThan(BigDecimal value) {
            addCriterion("PAY_ASSISTSCOPE >", value, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSISTSCOPE >=", value, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeLessThan(BigDecimal value) {
            addCriterion("PAY_ASSISTSCOPE <", value, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSISTSCOPE <=", value, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeIn(List<BigDecimal> values) {
            addCriterion("PAY_ASSISTSCOPE in", values, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeNotIn(List<BigDecimal> values) {
            addCriterion("PAY_ASSISTSCOPE not in", values, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_ASSISTSCOPE between", value1, value2, "payAssistscope");
            return this;
        }

        public Criteria andPayAssistscopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_ASSISTSCOPE not between", value1, value2, "payAssistscope");
            return this;
        }

        public Criteria andHospitalnameIsNull() {
            addCriterion("HOSPITALNAME is null");
            return this;
        }

        public Criteria andHospitalnameIsNotNull() {
            addCriterion("HOSPITALNAME is not null");
            return this;
        }

        public Criteria andHospitalnameEqualTo(String value) {
            addCriterion("HOSPITALNAME =", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameNotEqualTo(String value) {
            addCriterion("HOSPITALNAME <>", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameGreaterThan(String value) {
            addCriterion("HOSPITALNAME >", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameGreaterThanOrEqualTo(String value) {
            addCriterion("HOSPITALNAME >=", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameLessThan(String value) {
            addCriterion("HOSPITALNAME <", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameLessThanOrEqualTo(String value) {
            addCriterion("HOSPITALNAME <=", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameLike(String value) {
            addCriterion("HOSPITALNAME like", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameNotLike(String value) {
            addCriterion("HOSPITALNAME not like", value, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameIn(List<String> values) {
            addCriterion("HOSPITALNAME in", values, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameNotIn(List<String> values) {
            addCriterion("HOSPITALNAME not in", values, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameBetween(String value1, String value2) {
            addCriterion("HOSPITALNAME between", value1, value2, "hospitalname");
            return this;
        }

        public Criteria andHospitalnameNotBetween(String value1, String value2) {
            addCriterion("HOSPITALNAME not between", value1, value2, "hospitalname");
            return this;
        }

        public Criteria andMedicaltimeIsNull() {
            addCriterion("MEDICALTIME is null");
            return this;
        }

        public Criteria andMedicaltimeIsNotNull() {
            addCriterion("MEDICALTIME is not null");
            return this;
        }

        public Criteria andMedicaltimeEqualTo(Date value) {
            addCriterion("MEDICALTIME =", value, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeNotEqualTo(Date value) {
            addCriterion("MEDICALTIME <>", value, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeGreaterThan(Date value) {
            addCriterion("MEDICALTIME >", value, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeGreaterThanOrEqualTo(Date value) {
            addCriterion("MEDICALTIME >=", value, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeLessThan(Date value) {
            addCriterion("MEDICALTIME <", value, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeLessThanOrEqualTo(Date value) {
            addCriterion("MEDICALTIME <=", value, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeIn(List<Date> values) {
            addCriterion("MEDICALTIME in", values, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeNotIn(List<Date> values) {
            addCriterion("MEDICALTIME not in", values, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeBetween(Date value1, Date value2) {
            addCriterion("MEDICALTIME between", value1, value2, "medicaltime");
            return this;
        }

        public Criteria andMedicaltimeNotBetween(Date value1, Date value2) {
            addCriterion("MEDICALTIME not between", value1, value2, "medicaltime");
            return this;
        }

        public Criteria andApplytimeIsNull() {
            addCriterion("APPLYTIME is null");
            return this;
        }

        public Criteria andApplytimeIsNotNull() {
            addCriterion("APPLYTIME is not null");
            return this;
        }

        public Criteria andApplytimeEqualTo(Date value) {
            addCriterion("APPLYTIME =", value, "applytime");
            return this;
        }

        public Criteria andApplytimeNotEqualTo(Date value) {
            addCriterion("APPLYTIME <>", value, "applytime");
            return this;
        }

        public Criteria andApplytimeGreaterThan(Date value) {
            addCriterion("APPLYTIME >", value, "applytime");
            return this;
        }

        public Criteria andApplytimeGreaterThanOrEqualTo(Date value) {
            addCriterion("APPLYTIME >=", value, "applytime");
            return this;
        }

        public Criteria andApplytimeLessThan(Date value) {
            addCriterion("APPLYTIME <", value, "applytime");
            return this;
        }

        public Criteria andApplytimeLessThanOrEqualTo(Date value) {
            addCriterion("APPLYTIME <=", value, "applytime");
            return this;
        }

        public Criteria andApplytimeIn(List<Date> values) {
            addCriterion("APPLYTIME in", values, "applytime");
            return this;
        }

        public Criteria andApplytimeNotIn(List<Date> values) {
            addCriterion("APPLYTIME not in", values, "applytime");
            return this;
        }

        public Criteria andApplytimeBetween(Date value1, Date value2) {
            addCriterion("APPLYTIME between", value1, value2, "applytime");
            return this;
        }

        public Criteria andApplytimeNotBetween(Date value1, Date value2) {
            addCriterion("APPLYTIME not between", value1, value2, "applytime");
            return this;
        }

        public Criteria andApprovetimeIsNull() {
            addCriterion("APPROVETIME is null");
            return this;
        }

        public Criteria andApprovetimeIsNotNull() {
            addCriterion("APPROVETIME is not null");
            return this;
        }

        public Criteria andApprovetimeEqualTo(Date value) {
            addCriterion("APPROVETIME =", value, "approvetime");
            return this;
        }

        public Criteria andApprovetimeNotEqualTo(Date value) {
            addCriterion("APPROVETIME <>", value, "approvetime");
            return this;
        }

        public Criteria andApprovetimeGreaterThan(Date value) {
            addCriterion("APPROVETIME >", value, "approvetime");
            return this;
        }

        public Criteria andApprovetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("APPROVETIME >=", value, "approvetime");
            return this;
        }

        public Criteria andApprovetimeLessThan(Date value) {
            addCriterion("APPROVETIME <", value, "approvetime");
            return this;
        }

        public Criteria andApprovetimeLessThanOrEqualTo(Date value) {
            addCriterion("APPROVETIME <=", value, "approvetime");
            return this;
        }

        public Criteria andApprovetimeIn(List<Date> values) {
            addCriterion("APPROVETIME in", values, "approvetime");
            return this;
        }

        public Criteria andApprovetimeNotIn(List<Date> values) {
            addCriterion("APPROVETIME not in", values, "approvetime");
            return this;
        }

        public Criteria andApprovetimeBetween(Date value1, Date value2) {
            addCriterion("APPROVETIME between", value1, value2, "approvetime");
            return this;
        }

        public Criteria andApprovetimeNotBetween(Date value1, Date value2) {
            addCriterion("APPROVETIME not between", value1, value2, "approvetime");
            return this;
        }

        public Criteria andApprovestsIsNull() {
            addCriterion("APPROVESTS is null");
            return this;
        }

        public Criteria andApprovestsIsNotNull() {
            addCriterion("APPROVESTS is not null");
            return this;
        }

        public Criteria andApprovestsEqualTo(String value) {
            addCriterion("APPROVESTS =", value, "approvests");
            return this;
        }

        public Criteria andApprovestsNotEqualTo(String value) {
            addCriterion("APPROVESTS <>", value, "approvests");
            return this;
        }

        public Criteria andApprovestsGreaterThan(String value) {
            addCriterion("APPROVESTS >", value, "approvests");
            return this;
        }

        public Criteria andApprovestsGreaterThanOrEqualTo(String value) {
            addCriterion("APPROVESTS >=", value, "approvests");
            return this;
        }

        public Criteria andApprovestsLessThan(String value) {
            addCriterion("APPROVESTS <", value, "approvests");
            return this;
        }

        public Criteria andApprovestsLessThanOrEqualTo(String value) {
            addCriterion("APPROVESTS <=", value, "approvests");
            return this;
        }

        public Criteria andApprovestsLike(String value) {
            addCriterion("APPROVESTS like", value, "approvests");
            return this;
        }

        public Criteria andApprovestsNotLike(String value) {
            addCriterion("APPROVESTS not like", value, "approvests");
            return this;
        }

        public Criteria andApprovestsIn(List<String> values) {
            addCriterion("APPROVESTS in", values, "approvests");
            return this;
        }

        public Criteria andApprovestsNotIn(List<String> values) {
            addCriterion("APPROVESTS not in", values, "approvests");
            return this;
        }

        public Criteria andApprovestsBetween(String value1, String value2) {
            addCriterion("APPROVESTS between", value1, value2, "approvests");
            return this;
        }

        public Criteria andApprovestsNotBetween(String value1, String value2) {
            addCriterion("APPROVESTS not between", value1, value2, "approvests");
            return this;
        }

        public Criteria andImplstsIsNull() {
            addCriterion("IMPLSTS is null");
            return this;
        }

        public Criteria andImplstsIsNotNull() {
            addCriterion("IMPLSTS is not null");
            return this;
        }

        public Criteria andImplstsEqualTo(String value) {
            addCriterion("IMPLSTS =", value, "implsts");
            return this;
        }

        public Criteria andImplstsNotEqualTo(String value) {
            addCriterion("IMPLSTS <>", value, "implsts");
            return this;
        }

        public Criteria andImplstsGreaterThan(String value) {
            addCriterion("IMPLSTS >", value, "implsts");
            return this;
        }

        public Criteria andImplstsGreaterThanOrEqualTo(String value) {
            addCriterion("IMPLSTS >=", value, "implsts");
            return this;
        }

        public Criteria andImplstsLessThan(String value) {
            addCriterion("IMPLSTS <", value, "implsts");
            return this;
        }

        public Criteria andImplstsLessThanOrEqualTo(String value) {
            addCriterion("IMPLSTS <=", value, "implsts");
            return this;
        }

        public Criteria andImplstsLike(String value) {
            addCriterion("IMPLSTS like", value, "implsts");
            return this;
        }

        public Criteria andImplstsNotLike(String value) {
            addCriterion("IMPLSTS not like", value, "implsts");
            return this;
        }

        public Criteria andImplstsIn(List<String> values) {
            addCriterion("IMPLSTS in", values, "implsts");
            return this;
        }

        public Criteria andImplstsNotIn(List<String> values) {
            addCriterion("IMPLSTS not in", values, "implsts");
            return this;
        }

        public Criteria andImplstsBetween(String value1, String value2) {
            addCriterion("IMPLSTS between", value1, value2, "implsts");
            return this;
        }

        public Criteria andImplstsNotBetween(String value1, String value2) {
            addCriterion("IMPLSTS not between", value1, value2, "implsts");
            return this;
        }

        public Criteria andPayAssistIsNull() {
            addCriterion("PAY_ASSIST is null");
            return this;
        }

        public Criteria andPayAssistIsNotNull() {
            addCriterion("PAY_ASSIST is not null");
            return this;
        }

        public Criteria andPayAssistEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST =", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistNotEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST <>", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistGreaterThan(BigDecimal value) {
            addCriterion("PAY_ASSIST >", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST >=", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistLessThan(BigDecimal value) {
            addCriterion("PAY_ASSIST <", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_ASSIST <=", value, "payAssist");
            return this;
        }

        public Criteria andPayAssistIn(List<BigDecimal> values) {
            addCriterion("PAY_ASSIST in", values, "payAssist");
            return this;
        }

        public Criteria andPayAssistNotIn(List<BigDecimal> values) {
            addCriterion("PAY_ASSIST not in", values, "payAssist");
            return this;
        }

        public Criteria andPayAssistBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_ASSIST between", value1, value2, "payAssist");
            return this;
        }

        public Criteria andPayAssistNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_ASSIST not between", value1, value2, "payAssist");
            return this;
        }

        public Criteria andPaySumassistInIsNull() {
            addCriterion("PAY_SUMASSIST_IN is null");
            return this;
        }

        public Criteria andPaySumassistInIsNotNull() {
            addCriterion("PAY_SUMASSIST_IN is not null");
            return this;
        }

        public Criteria andPaySumassistInEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN =", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInNotEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN <>", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInGreaterThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN >", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN >=", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInLessThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN <", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_IN <=", value, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_IN in", values, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInNotIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_IN not in", values, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_IN between", value1, value2, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistInNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_IN not between", value1, value2, "paySumassistIn");
            return this;
        }

        public Criteria andPaySumassistOutIsNull() {
            addCriterion("PAY_SUMASSIST_OUT is null");
            return this;
        }

        public Criteria andPaySumassistOutIsNotNull() {
            addCriterion("PAY_SUMASSIST_OUT is not null");
            return this;
        }

        public Criteria andPaySumassistOutEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT =", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutNotEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT <>", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutGreaterThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT >", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT >=", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutLessThan(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT <", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_SUMASSIST_OUT <=", value, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_OUT in", values, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutNotIn(List<BigDecimal> values) {
            addCriterion("PAY_SUMASSIST_OUT not in", values, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_OUT between", value1, value2, "paySumassistOut");
            return this;
        }

        public Criteria andPaySumassistOutNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_SUMASSIST_OUT not between", value1, value2, "paySumassistOut");
            return this;
        }

        public Criteria andSumMedicarescopeIsNull() {
            addCriterion("SUM_MEDICARESCOPE is null");
            return this;
        }

        public Criteria andSumMedicarescopeIsNotNull() {
            addCriterion("SUM_MEDICARESCOPE is not null");
            return this;
        }

        public Criteria andSumMedicarescopeEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE =", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeNotEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE <>", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeGreaterThan(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE >", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE >=", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeLessThan(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE <", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SUM_MEDICARESCOPE <=", value, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeIn(List<BigDecimal> values) {
            addCriterion("SUM_MEDICARESCOPE in", values, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeNotIn(List<BigDecimal> values) {
            addCriterion("SUM_MEDICARESCOPE not in", values, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_MEDICARESCOPE between", value1, value2, "sumMedicarescope");
            return this;
        }

        public Criteria andSumMedicarescopeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SUM_MEDICARESCOPE not between", value1, value2, "sumMedicarescope");
            return this;
        }

        public Criteria andPayCiassistIsNull() {
            addCriterion("PAY_CIASSIST is null");
            return this;
        }

        public Criteria andPayCiassistIsNotNull() {
            addCriterion("PAY_CIASSIST is not null");
            return this;
        }

        public Criteria andPayCiassistEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST =", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistNotEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST <>", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistGreaterThan(BigDecimal value) {
            addCriterion("PAY_CIASSIST >", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST >=", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistLessThan(BigDecimal value) {
            addCriterion("PAY_CIASSIST <", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PAY_CIASSIST <=", value, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistIn(List<BigDecimal> values) {
            addCriterion("PAY_CIASSIST in", values, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistNotIn(List<BigDecimal> values) {
            addCriterion("PAY_CIASSIST not in", values, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_CIASSIST between", value1, value2, "payCiassist");
            return this;
        }

        public Criteria andPayCiassistNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PAY_CIASSIST not between", value1, value2, "payCiassist");
            return this;
        }

        public Criteria andAssistTypeIsNull() {
            addCriterion("ASSIST_TYPE is null");
            return this;
        }

        public Criteria andAssistTypeIsNotNull() {
            addCriterion("ASSIST_TYPE is not null");
            return this;
        }

        public Criteria andAssistTypeEqualTo(String value) {
            addCriterion("ASSIST_TYPE =", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotEqualTo(String value) {
            addCriterion("ASSIST_TYPE <>", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeGreaterThan(String value) {
            addCriterion("ASSIST_TYPE >", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPE >=", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeLessThan(String value) {
            addCriterion("ASSIST_TYPE <", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeLessThanOrEqualTo(String value) {
            addCriterion("ASSIST_TYPE <=", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeLike(String value) {
            addCriterion("ASSIST_TYPE like", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotLike(String value) {
            addCriterion("ASSIST_TYPE not like", value, "assistType");
            return this;
        }

        public Criteria andAssistTypeIn(List<String> values) {
            addCriterion("ASSIST_TYPE in", values, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotIn(List<String> values) {
            addCriterion("ASSIST_TYPE not in", values, "assistType");
            return this;
        }

        public Criteria andAssistTypeBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPE between", value1, value2, "assistType");
            return this;
        }

        public Criteria andAssistTypeNotBetween(String value1, String value2) {
            addCriterion("ASSIST_TYPE not between", value1, value2, "assistType");
            return this;
        }

        public Criteria andMedicaltimeEndIsNull() {
            addCriterion("MEDICALTIME_END is null");
            return this;
        }

        public Criteria andMedicaltimeEndIsNotNull() {
            addCriterion("MEDICALTIME_END is not null");
            return this;
        }

        public Criteria andMedicaltimeEndEqualTo(Date value) {
            addCriterion("MEDICALTIME_END =", value, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndNotEqualTo(Date value) {
            addCriterion("MEDICALTIME_END <>", value, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndGreaterThan(Date value) {
            addCriterion("MEDICALTIME_END >", value, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndGreaterThanOrEqualTo(Date value) {
            addCriterion("MEDICALTIME_END >=", value, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndLessThan(Date value) {
            addCriterion("MEDICALTIME_END <", value, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndLessThanOrEqualTo(Date value) {
            addCriterion("MEDICALTIME_END <=", value, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndIn(List<Date> values) {
            addCriterion("MEDICALTIME_END in", values, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndNotIn(List<Date> values) {
            addCriterion("MEDICALTIME_END not in", values, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndBetween(Date value1, Date value2) {
            addCriterion("MEDICALTIME_END between", value1, value2, "medicaltimeEnd");
            return this;
        }

        public Criteria andMedicaltimeEndNotBetween(Date value1, Date value2) {
            addCriterion("MEDICALTIME_END not between", value1, value2, "medicaltimeEnd");
            return this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("ID_CARD is null");
            return this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("ID_CARD is not null");
            return this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("ID_CARD =", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("ID_CARD <>", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("ID_CARD >", value, "idCard");
            return this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("ID_CARD >=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("ID_CARD <", value, "idCard");
            return this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("ID_CARD <=", value, "idCard");
            return this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("ID_CARD like", value, "idCard");
            return this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("ID_CARD not like", value, "idCard");
            return this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("ID_CARD in", values, "idCard");
            return this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("ID_CARD not in", values, "idCard");
            return this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("ID_CARD between", value1, value2, "idCard");
            return this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("ID_CARD not between", value1, value2, "idCard");
            return this;
        }

        public Criteria andBusinessYearIsNull() {
            addCriterion("BUSINESS_YEAR is null");
            return this;
        }

        public Criteria andBusinessYearIsNotNull() {
            addCriterion("BUSINESS_YEAR is not null");
            return this;
        }

        public Criteria andBusinessYearEqualTo(String value) {
            addCriterion("BUSINESS_YEAR =", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearNotEqualTo(String value) {
            addCriterion("BUSINESS_YEAR <>", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearGreaterThan(String value) {
            addCriterion("BUSINESS_YEAR >", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearGreaterThanOrEqualTo(String value) {
            addCriterion("BUSINESS_YEAR >=", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearLessThan(String value) {
            addCriterion("BUSINESS_YEAR <", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearLessThanOrEqualTo(String value) {
            addCriterion("BUSINESS_YEAR <=", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearLike(String value) {
            addCriterion("BUSINESS_YEAR like", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearNotLike(String value) {
            addCriterion("BUSINESS_YEAR not like", value, "businessYear");
            return this;
        }

        public Criteria andBusinessYearIn(List<String> values) {
            addCriterion("BUSINESS_YEAR in", values, "businessYear");
            return this;
        }

        public Criteria andBusinessYearNotIn(List<String> values) {
            addCriterion("BUSINESS_YEAR not in", values, "businessYear");
            return this;
        }

        public Criteria andBusinessYearBetween(String value1, String value2) {
            addCriterion("BUSINESS_YEAR between", value1, value2, "businessYear");
            return this;
        }

        public Criteria andBusinessYearNotBetween(String value1, String value2) {
            addCriterion("BUSINESS_YEAR not between", value1, value2, "businessYear");
            return this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("ADDRESS is null");
            return this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("ADDRESS is not null");
            return this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("ADDRESS =", value, "address");
            return this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("ADDRESS <>", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("ADDRESS >", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("ADDRESS >=", value, "address");
            return this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("ADDRESS <", value, "address");
            return this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("ADDRESS <=", value, "address");
            return this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("ADDRESS like", value, "address");
            return this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("ADDRESS not like", value, "address");
            return this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("ADDRESS in", values, "address");
            return this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("ADDRESS not in", values, "address");
            return this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("ADDRESS between", value1, value2, "address");
            return this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("ADDRESS not between", value1, value2, "address");
            return this;
        }
    }
}